### ISSUE TITLE
 ImportError: DLL load failed: The specified procedure could not be found.

### ISSUE THREAD

**Issue by Firnagzen** [kivy/kivy#1355]
Ok... So I've finally managed to compile Kivy for Windows with Python 3.3, using the latest zip downloaded from the master branch of this git. However, I can't run any of the examples. For instance, when I try to run touchtracer, I get this: https://gist.github.com/Firnagzen/77bc000de7b738c8ebc7

This error is consistently reproducible simply by trying to run any of the bundled demo programs. I've also tried compiling the same download of the master branch with Python 2.7, and that works perfectly fine. Any idea what could be wrong? Should I be using the download from the py-3 branch instead? (The py-3 branch apparently has no differences from the main branch, however, according to the github comparison.)

Additionally, I am unable to find config.ini to change my log_level to debug, should anyone be able to tell me where to find it (or do I have to create it?), I'd be happy to post the debug log.

**Comment by hambi-hemts** [comment]
I also encountered this problem after installing kivy 1.9.1 and the kivy designer on Windows 10, Anaconda 2.4.1 (Python v3.4.3)

**Kivy installation:**
`python -m pip install --upgrade pip wheel setuptools`
`python -m pip install kivy`
> import kivy in python works. 

**Kivy-designer-installation:**
I followed https://kivy-designer.readthedocs.org/en/latest/installation.html
This step didn't work for me:
>  (on windows use kivy.bat in the kivy folder)

 since I couldn't find the kivy.bat file anywhere. 
> garden install filebrowser

worked for me though (maybe I had "garden" installed already).

**Starting the kivy-designer**
Running 
`python main.py`
results in 

` from kivy.graphics.instructions import Callback, Canvas, CanvasBase, \ 
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.`

**Following these steps by** @tito 

#. open a command line, same as the one you would use for kivy
#. go into the kivy/graphics directory
#. open a python shell
#. import ctypes
#: ctypes.CDLL('fbo.pyd')

results in 

`>>> ctypes.CDLL('fbo.pyd')`
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda3\lib\ctypes\__init__.py", line 351, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] Das angegebene Modul wurde nicht gefunden`

Any help is appreciated : )

**Comment by reflechant** [comment]
Glew... last updated in 2006 for python 2.4 and stuck in 0.7.x version. Do you really want to depend on such things?

**Comment by dessant** [comment]
@reflechant, that's correct.
http://glew.sourceforge.net/

**Comment by kived** [comment]
GLEW is not out-of-date at all. GLEWpy, a package providing Python bindings for GLEW which **we do not use**, is an old piece of crap.

**Comment by reflechant** [comment]
Thanks for the explanation.
I'm trying to install kivy on Internetless PC with Windows for 2 days.
Is it possible to include the dependencies in some package? Maybe an .exe or .msi? It would facilitate things a lot.

**Comment by dessant** [comment]
@reflechant, you can download the wheels from pypi and install them from a local copy.
If you have further issues, post on the mailing list or irc.

**Comment by Kentanz** [comment]
install modules separately to know which one is at fault, may have missed out the dependencies installation.  
instead of a one liner installation 
python -m pip install --upgrade docutils pygments pypiwin32 kivy.deps.sdl2 kivy.deps.glew 
try the following-
python -m pip install pypiwin32 
python -m pip install kivy.deps.sdl2
python -m pip install kivy.deps.glew
