### ISSUE TITLE
Filechooser: no way to get error

### ISSUE THREAD

**Issue by tito** [kivy/kivy#140]
If we have an error in the filechooser when listing file, we have no way to get that error.
Use case would be to log error on a notification, or take appropriate action ... dunno.
##

**Comment by KeyWeeUsr** [comment]
If it's that error a user can see in the console and the output is created with Logger.exeption, then I'd support @rubik 's idea, but with a split into two solutions:

1) each specific exception in logger would have a return code/string for `on_error` that would be something like `gcc`'s blah blah error, returned <number>, so that it could be checked what exactly happened.

2) multiple `on_`, meaning = multiple events for specific stuff, which might be clearer for users and for debugging too.

**Comment by FeralBytes** [comment]
@KeyWeeUsr I don't think I understand your plan here? 
I was thinking on_error would be good for notification and then the variable that is passed to the on_error function would be the error code. What do you think?

**Comment by KeyWeeUsr** [comment]
@FeralBytes I think I was considering all possible errors thrown during the listing of files e.g.

* [.sys error](https://github.com/kivy/kivy/issues/4374)
* unicode en/decoding error (filename)
* other possible errors, maybe even drawing related errors if called [update](https://github.com/kivy/kivy/blob/master/kivy/uix/filechooser.py#L680)

and making appropriate on_* event(s) for that, so that the end-user knew if it was just a simple thing like with `.sys`, or it threw something worse. I'm not sure if it's even possible to get such feedback from the filechooser related to updating/redrawing though, but it can happen quite often if you:

* use multiple FileChooser widgets
* trigger too often

Although now I'm not really sure which one had @tito in mind. Probably only the `.sys` related error?

**Comment by FeralBytes** [comment]
I vote yes.

**Comment by Julian-O** [comment]
Closed, again, as stale.

If you think this is in error, please let us know.
