### ISSUE TITLE
Capturing exceptions inside Kv

### ISSUE THREAD

**Issue by Davideddu** [kivy/kivy#1572]
Hello,
I suggested this in another issue, but I want to repropose it as I think it will be a lot useful. It happens sometimes that something inside the Kv raises an unwanted exception that you cannot avoid. The only alternative is creating some python function that contains a try-except and prevents the app from crashing, but this makes the kv language itself unuseful.

Will you do that? For example one could wrap from a few properties to an entire tree in a try-except; the builder checks, when an exception occurs, if there was a try-excepts and avoids it in that case, or reraises it if there wasn't any.

**Comment by nadrimajstor** [comment]
For what it's worth, I would write it as:
```qml
Image:
    source: mymodule.get_image()
    size: "64dp", "64dp"
    on_error: self.source = "atlas://data/images/defaulttheme/image-missing"
```

**Comment by matham** [comment]
That seems too vague, i.e. to what does the `on_error` apply? To the whole rule including instantiation of Image? Or just a few of the rules. And if it's for the whole rule then it's too limiting. Also, this would clash with a property names `error`.

I think we should close this issue as this is unlikely to happen, at least in the way it's currently proposed.

**Comment by dessant** [comment]
The use case snippet is a bit unfortunate, it seems to be referring to handling a not found image, which has nothing to do with this thread because a wrong file path produces a white texture, not an exception.

For the original proposal, i don't see a need for try except in kv either, normally, kv should never fail in that way, and if it does, the code should be fixed, not exceptions handled. Exceptions originating from python function calls can also be handled on the python side.
