### ISSUE TITLE
Rotation window + shader = fail

### ISSUE THREAD

**Issue by tito** [kivy/kivy#180]
If you rotate the window and use a shader, it will fail: the rotation is not applied to the shader.
We should have an uniq way for using the parent matrix for model and projection from shader in graphics.
##

**Comment by tshirtman** [comment]
5 years passed… here is an example to reproduce, at least, and yes, it's not yet fixed.

`python2 examples/shader/plasma.py -c graphics:rotation:90`

vs 

`python2 examples/shader/plasma.py`

![shader_rotation](https://cloud.githubusercontent.com/assets/22759/14055236/73c939b0-f2e0-11e5-9bb6-9b85e310a61a.png)

multiple issues visible:
- The shader doesn't cover the correct part of the window, if you resize, you see it's size is [windows.height, windows.width] instead of the opposite.
- The animation looks exactly the same as the un-rotated version, instead of rotated.

**Comment by IgorCode** [comment]
I'm seeing the behaviour that @tshirtman described without using shader (that I know of). Everytime I pause and return to app I get this, that is if I'm holding the device in different orientation from the one app was meant to be in (i.e. device is in portrait mode, app is in landscape mode).

**Comment by parabolize** [comment]
In a effort to understand kivy a little better I explored this problem a bit. I will try to describe what is happening. If you see any inaccuracies please correct me.
The short description is rotations, translations and other manipulations of the parent RenderingContext arn't applied to any custom vertex or fragment shader you create unless you implement what is normally done in the default.vs and default.fs.

The longer explanation:
I will use the examples/shader/plasma.py as the example. 
kivy.core.window.Window is a giant, magical singleton that is normally created in App.run() after App.build() returns your root Widget. Window collects the graphics:rotation:90 argument and uses it along with other information to create two matrices and attaches them to its RenderContext as 'projection_mat' and 'modelview_mat'. This is done in two methods Window._get_size() and Window.update_viewport(). The RenderContext passes these matrices to its Shader. The Shader passes them to cgl. The default vector shader kivy/data/glsl/default.vs multiplies these against each vector. default.vs passes frag_color and tex_coord0 to default.fs.
The plasma.py example creates its own RenderContext and requests its parents 'projection_mat' but not its 'modelview_mat'. The projection matrix stores information for what is in view and Window uses its size (created with respect to rotation) to create that projection. The model view matrix stores the rotation information. If the 'modelview_mat' isn't requested from the parent its just going to use a identity matrix as a default. If the default fragment shader is overwritten with a shader that shader needs to use the variables exported by the vector shader or the uniform variables passed in by the RenderContext in some way to replicate the rotation.
The only way I can imagin solving this problem is using some kind of Fbo that you can resize for the custom shaders and rotating the Fbo.

Below is a altertered plasma.py. Its intended to be a example of how to work around the problem. Both of plasma.py rendering contexts request both parent matrices and uses the model view in the fragment shader to apply the rotation.

![kivy_rotating_kinda](https://user-images.githubusercontent.com/19229768/32096378-85a9015e-bac3-11e7-882d-2ff266b53924.png)


```python
'''
Plasma Shader
=============

This shader example have been taken from
http://www.iquilezles.org/apps/shadertoy/ with some adaptation.

This might become a Kivy widget when experimentation will be done.
'''
from kivy.app import App
from kivy.lang import Builder
from kivy.clock import Clock
from kivy.graphics import RenderContext
from kivy.properties import StringProperty
from kivy.uix.floatlayout import FloatLayout
from kivy.uix.widget import Widget

# imported early for side effects needed for Shader
import kivy.core.window

kv = '''#:kivy 1.1.0

<MiniShaderWidget>:
    size_hint: .2, .2
    pos_hint: {'x': .05, 'y': .05}
    canvas:
        Color:
            rgb: 1., .6, .3
        Rectangle:
            pos: self.pos
            size: self.size

<MainWidget>:
    canvas:
        Color:
            rgb: .9, .6, .3
        Rectangle:
            pos: self.pos
            size: self.size

        Color:
            rgb: .3, .6, .9
        Ellipse:
            pos: self.width * 3 / 8, self.top * 3 / 4
            size: self.width / 4, self.top / 4

    Label:
        text: 'far out'
        font_size: 60
        outline_width: 3
        pos_hint: {'center_x': .75, 'center_y': .25}
        canvas.before:
            PushMatrix
            Rotate:
                angle: 45
                origin: self.center
        canvas.after:
            PopMatrix

    MiniShaderWidget
'''


shared_code = '''
$HEADER$

uniform mat4 modelview_mat;
uniform float time;

float plasmaFunc(float n1, float n2, float n3, float n4)
{
   vec4 fPos = modelview_mat * vec4(gl_FragCoord.xy, 0, 1);
   return abs(sin(
                  sin(sin(fPos.x / n1) + time) +
                  sin(fPos.y / n2 + time) +
                  sin((fPos.x + fPos.y) / n3) * n4));
}
'''


plasma_shader = shared_code + '''
void main(void)
{
   float green = plasmaFunc(40., 30., 100., 3.5);
   vec4 tex = texture2D(texture0, tex_coord0);
   gl_FragColor = vec4(1.0, green, 1.0, 1.0) * frag_color * tex;
}
'''


plasma_shader2 = shared_code + '''
void main(void)
{
   float red = plasmaFunc(30., 20., 10., .5);
   vec4 tex = texture2D(texture0, tex_coord0);
   gl_FragColor = vec4(red, 1.0, 1.0, 1.0) * frag_color * tex;
}
'''


class ShaderWidget(Widget):
    def __init__(self, **kwargs):
        # Instead of using Canvas, we will use a RenderContext,
        # and change the default fragment shader used.
        self.canvas = RenderContext(fs=self._fs, 
                                    use_parent_projection=True,
                                    use_parent_modelview=True)

        # call the constructor of parent
        # if they are any graphics object, they will be added on our new canvas
        super(ShaderWidget, self).__init__(**kwargs)

        # We'll update our glsl variables in a clock
        Clock.schedule_interval(self.update_glsl, 1 / 60.)

    def update_glsl(self, *largs):
        self.canvas['time'] = Clock.get_boottime()


class MiniShaderWidget(ShaderWidget):
    _fs = StringProperty(plasma_shader2)


class MainWidget(ShaderWidget, FloatLayout):
    _fs = StringProperty(plasma_shader)


class PlasmaApp(App):
    def build(self):
        Builder.load_string(kv)
        return MainWidget()


if __name__ == '__main__':
    PlasmaApp().run()
```

**Comment by pythonic64** [comment]
Solved in https://github.com/kivy/kivy/pull/5470 by adding `frag_modelview_mat` uniform in `RenderContext`.
