### ISSUE TITLE
Setting the icon doesn't work on Ubuntu 14.04

### ISSUE THREAD

**Issue by jgandert** [kivy/kivy#2261]
I'm on Ubuntu 14.04 (Unity) / 64bit, using Python3.4. (I haven't tested other platforms.)

My app icon is set like this and `icon.png` is in the main directory next to `main.py`.

``` python
class MyApp(App):
    def build(self):
        self.icon = 'icon.png'
```

My `icon.png`:
![icon](https://cloud.githubusercontent.com/assets/3063858/3279589/d9c11944-f405-11e3-89a7-bdb1efe19e04.png)

This is how it looks:
![iantinet](https://cloud.githubusercontent.com/assets/3063858/3279578/2f703074-f405-11e3-9aa6-91233e528d5b.png)

(si2: Is kivy's default icon available as svg or at a higher resolution?)

**Comment by AndreMiras** [comment]
That's a very funny one since I could reproduce exactly as described...
So the icon is not showing in Ubuntu 16.04 (Unity), I get the unknown icon or the Kivy default one.
Then I install pygame and run your pygame code example, I can now see the icon.
And when I run my application again now I can see the icon.
Now I tried to reproduce it in a virtualenv, but no way, my icon is always showing. I think it's because once the icon is being created with pygame it's then cached by Unity. So once we find a way to invalidate icon cache we would probably be able to reproduce.

More info, my test directory contains:

- kivy_icon.py
- pygame_icon.py
- icon.png

kivy_icon.py
```
from kivy.app import App
from kivy.uix.button import Button

class MyApp(App):
    def build(self):
        self.icon = 'icon.png'
        return Button(text='hello world')


if __name__ == '__main__':
    MyApp().run()
```

pygame_icon.py
```
import pygame
from pygame.locals import QUIT

icon = pygame.image.load('icon.png')
pygame.display.set_icon(icon)
pygame.display.set_mode((640, 480))

while True:
    for event in pygame.event.get():
        if event.type == QUIT:
            pygame.quit()

    pygame.display.update()
```

Running `kivy==1.10.0` (well more or less...)

**Comment by AmarVK** [comment]
I am facing a similar issue as @CreamyCookie. Unfortunately, it did not get solved. I tried running a pygame_icon.py. The icon was seen, the kivy one is still not seen. Running kivy version 1.10.0 on python 2.7
