### ISSUE TITLE
Changing the color of button changes the tint of the background image

### ISSUE THREAD

**Issue by jgandert** [kivy/kivy#2379]
This is the code for creating the upper right button:

```
    button = Button(size_hint_y=None, text='Einstellungen')
    # button.color = get_color_from_hex('#e0080d')
```

and the resulting app: (please ignore the crappy pixel art etc. :wink:)

![normal working app screenshot](https://cloud.githubusercontent.com/assets/3063858/3771442/20a9cd92-18f5-11e4-88cb-6b760da9153d.png)

but when I uncomment the line to change the text color of the button, this is what it looks like:

![bildschirmfoto vom 2014-07-31 22 55 06](https://cloud.githubusercontent.com/assets/3063858/3771454/383cb582-18f5-11e4-8293-2b960f806645.png)

**Comment by Dalker** [comment]
Just found this issue when googling for the exact same problem, two years later. 

I encountered this while trying to do a minor modification to the _Pong_ tutorial. I wanted to change the score labels at the end of the game to reflect the winner/loser. 

The only modification I did for this purpose to the tutorial code was adding `id`s for the labels, and then instructions akin to `self.label1.color = [0, 1, 0, 1]` after an endgame condition. The result is that the second such color contaminates all of the other widgets. I added no widget outside of those defined on the tutorial, and didn't play with any other property of those widgets.

So I have to agree with @CreamyCookie that this is definitely contrary to the _Principle of least astonishment_ that he mentioned. I really don't understand how it can be considered normal that modifying the color of a widget from its default white to something else should affect every widget that didn't have a color explicitly defined first.

Encountering such weird behaviour when trying to add a minor modification to the **first tutorial** of a library, and then reading that it's supposed to be "a feature, not a bug", is quite surprising, to say the least.

**Comment by inclement** [comment]
@Dalker I don't think the way Button behaves here is good, you're right that it's surprising. We may be able to change this for kivy 2.0 (taking the opportunity for a few breaking changes of this type).

For the Color propagation, that's probably just something to learn to live with, but I'm not sure you've understood it fully - the order of classes in the kv file does not matter, only the order of canvas instructions in the canvas tree of the actual app. In that case, the most recent Color instruction before the PongBall is likely to come from e.g. a widget added to the PongBall's parent first. You should put the Color instruction before the Ellipse specifically because you want it to affect the Ellipse.

**Comment by Dalker** [comment]
@inclement Thanks for taking the time to reply. 

I now see that it does make sense that the order between the properties can matter in this situation. Well, not "properties" per se, but "canvas instructions", as you point out, which I guess is the initial source of confusion: when looking at a .kv file for the first time, these really do "look" like if they were "properties" (and that's why the newcomer can be confused by the "contamination" behaviour). 

 > I'm not sure you've understood it fully 

I definitely didn't.

May I suggest adding a little paragraph around the end of the Pong tutorial (as an extra bullet to the _Where to go now?_ section, where suggested extra features are mentioned, inviting the reader to try and modify/improve the game) explicitly mentioning something similar to:

> - Make the ball yellow while keeping everything else white.
> Warning: anything under `canvas:` in a `.kv` file is not a _class property_, but rather a _canvas instruction_. This can have effects that seem unexpected to the newcomer. For instance, a `Color:` canvas instruction changes the color of the "brush" globally, and can thus affect other objects drawn by any subsequent _canvas instructions_ of any object. It is therefore good practice to always specify a `Color:` explicitly at the beginning of the `canvas:` section of every class.  In this suggested improvement to Pong, this is however not necessary: it is enough to surround the `Ellipse:` instruction of the ball's canvas to change the brush to yellow right before drawing it, and then back to the default white right afterwards.

That way, the newcomer would immediately have the opportunity to be confronted to this behaviour and understand what to be aware of.

**Comment by selstos** [comment]
Hi! How to change color  of text in button?
