### ISSUE TITLE
The default window title and icon are flashed before the custom ones

### ISSUE THREAD

**Issue by dessant** [kivy/kivy#2415]
The window pops up with the default kivy icon and title ('Kivy') before the custom ones are applied to the window, seen on Windows.
##

**Comment by victor-rene** [comment]
Only solution I could find is to remove hard-coded title value from Window core (https://github.com/kivy/kivy/blob/master/kivy/core/window/__init__.py#L507) and inject values from Config module. Also, it might be necessary to be more consistent with such settings. Why can we set icon from app, window and config? If ConfigParser is loaded before Window is created there is no reason why we can fetch the values directly from it.

My 2 cents, this is not easy, remove label please. Gotcha, I dunno if this impacts older versions of Kivy or not.

**Comment by pythonic64** [comment]
Still present in master branch https://github.com/kivy/kivy/blob/67d02cdcd7f077bdf7f6c9568c4720aef2746dcd/kivy/core/window/__init__.py#L840

**Comment by Julian-O** [comment]
Still present in master branch

**Comment by ElliotGarbus** [comment]
@Julian-O 
I set the title in build and have not had this issue on WIndows or Mac.
The app icon should be set using the config object, to avoid the icon flashing.  My apps that target Mac and Windows use the code below.

```python
if platform == 'macosx':
    Config.set('kivy', 'window_icon','Images/app_logo_512.png') # macos uses a 512x512 png
else:
    Config.set('kivy', 'window_icon','Images/app_logo_64.png')  # Windows uses a small 64x64 png
```

**Comment by Julian-O** [comment]
@ElliotGarbus: I am just saying that code, which defaults to 'Kivy' as a title is still present. It would be interesting to learn if is still flashing, just very quickly, or that problem is solved.

Meanwhile the unclear icon sizing should be document with an example like yours.
I am surprised an .ico file doesn't work on Windows. [It is designed for precisely this situation](https://learn.microsoft.com/en-gb/windows/win32/uxguide/vis-icons), and may include multiple sizes. Supporting ico (as well as png) seems appropriate. Supporting .ico on other platforms sounds like it would be simple too.

**Comment by Julian-O** [comment]
There are two issues here. Leaving this one as the flashing icon. Creating a new one for icon size issues.

**Comment by ElliotGarbus** [comment]
@Julian-O 
The .ico file on Windows, and .incs file for MacOS are used in pyinstaller to associate the Icon with the exe (or .app). 
I've found I need to use both the icon file and a png.

The title does not flash.

**Comment by Julian-O** [comment]
@ElliotGarbus: Understood. There is a need for an icon before the app loads, and then another one that is requested when the app loads. Further discussion on this should be in #8456,

Meanwhile I am closing this issue about the flashing of the title and icon, because, as described above, it doesn't happen any more.

The OP, Dessant, is no longer on the project, but if anyone else sees this behaviour continuing, please let us know.
