### ISSUE TITLE
ScreenManager.clear_widgets()

### ISSUE THREAD

**Issue by cropleyb** [kivy/kivy#2655]
What should ScreenManager.clear_widgets() do?
At the moment, it can change its "current" attribute as it is iterating through the screens:
https://gist.github.com/cropleyb/b3f65d29fddc579ce741
(unless the current screen is the last screen to be iterated over)

**Comment by rastogiachyut** [comment]
Looking into this one.
@dessant if we make it remove all screens than will it not violate the removes all children rule that is given in documentation?

**Comment by dessant** [comment]
@rastogiachyut could you link and quote? I'm not sure which rule that is.

**Comment by rastogiachyut** [comment]
I meant this -> http://kivy.org/docs/api-kivy.uix.widget.html?highlight=clear_widget#kivy.uix.widget.Widget.clear_widgets
Did I misinterpret it?

**Comment by dessant** [comment]
It means with no arguments, all children are removed, but only the specified widgets are removed if you pass a list to that method.

**Comment by rastogiachyut** [comment]
from your first comment I understood that you want to delete the current screen too(along with all the children) which I think strays from its regular implementation, is that what you think it should do?. should I ask other devs for their opinions?

**Comment by dessant** [comment]
I really don't see the problem there, an empty screenmanager is a legit use case, by calling sm.clear_widgets(), we should achieve the same state that a newly initialized screenmanager has, without any children.

Can you explain exactly what do you find problematic in this behavior?

**Comment by rastogiachyut** [comment]
Yes, it is a valid use case. I was confusing theory with implementation cause when i set screenmanager.current = None it throws an exception. I think I understand the problem now,when we do  ScreenManager.clear_widgets() it removes only the current screen instead of all screens(which should be behavior shown by  Screen.clear_widgets()). I can delete all screens but that would mean doing screenmanager.current = None which is not possible, so should I instead delete the screenmanager after creating one identical to it(identical except the screens).
