### ISSUE TITLE
Kivy touch events not working on Raspberry PI with Adafruit PiTFT

### ISSUE THREAD

**Issue by iluminite** [kivy/kivy#2656]
Hi!

I have an Adafruit 2.8in LCD with a resistive touchscreen [1], connected to a Raspberry Pi and working with Kivy. I have had to use fbcp [2] to get this setup to work with Kivy, but that is fine. While I have seen issues with idle apps using 30-40% CPU (as per htop), the primary blocker in my setup is that the touchscreen errors out with Kivy.

I can create a Button in a Kivy App and press it, Kivy does see the touch, but errors out:

```
[INFO              ] [HIDMotionEvent] using <stmpe-ts>
 Exception in thread Thread-1:
 Traceback (most recent call last):
   File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
     self.run()
   File "/usr/lib/python2.7/threading.py", line 505, in run
     self.__target(*self.__args, **self.__kwargs)
   File "/home/pi/kivy/kivy/input/providers/hidinput.py", line 580, in _thread_run
     process_as_mouse_or_keyboard(*infos)
   File "/home/pi/kivy/kivy/input/providers/hidinput.py", line 456, in process_as_mouse_or_keyboard
   l = keyboard_keys[ev_code][-1 if 'shift' in Window._modifiers else 0]
 KeyError: 330
```

Here are a few additional notes:
- After this, I am unable to get another button press to register in the log, but the app is still running and updating the screen.
- The above errors were seen with kKivy installed from git master from a few days ago, I will update to latest master and retry.
- I can debug, build, etc, specific branches, patches, etc.. anything to help this move along.

[1] https://www.adafruit.com/prohttps://www.adafruit.com/product/1601duct/1601
[2] https://github.com/tasanakorn/rpi-fbcp

**Comment by nurgasemetey** [comment]
Sorry, I know this thread is closed. @tito, would you make tutorial-like post for other who began work with PiTFT + Kivy + Raspberry, because for example I can't fully understand what you've done to work this touchscreen. It would be good because all who have issues will be clarified by your post and will not disturb you. Thanks

**Comment by phaneesh** [comment]
@tito I am facing issue even displaying anything on the touchscreen. The screen is calibrated (I don't use X either). Event test works (ts_test & evtest). Please let me know how to display the UI on touch display instead of HDMI. (I have tried the usual methods FRAMEBUFFER variable & DISPLAY variable)
