### ISSUE TITLE
interpolate example converges, but never reaches the end value

### ISSUE THREAD

**Issue by jgandert** [kivy/kivy#2788]
https://github.com/kivy/kivy/blob/master/kivy/utils.py#L49

```
 # use interpolate, and you'll have a nicer transition
self.pos = interpolate(self.pos, new_pos)
```

The example will never reach the end point. It only works when the step value is decreased, after every step.
##

**Comment by victor-rene** [comment]
After writing the tests for this unit, I conclude that we must either clarify its intent or make it work differently. Now, I think it's behavior is correct because if you want to reach the end value, you use Animation. Interpolate might just a function that you use if you think you need some kind of progressive  slowing movement towards a endpoint, even though you never reach it.

**Comment by snapy666** [comment]
@victor-rene Maybe it should be called [asymptote](http://en.wikipedia.org/wiki/Asymptote), but the comment `use interpolate, and you'll have a nicer transition` then definitely doesn't fit, because `transition` to me means, that the position actually reaches the new position, after `step` steps.

**Comment by Julian-O** [comment]
Let me restate the problem. I think it is worse than described above.

(Linear) interpolation is simple enough mathematical concept. You have two known points, (x1, y1) and (x2, y2) and you ask "If we drew a line between them, what would the value of y be at when x is set to a value between x1 and x2."

You can either express x as an absolute value (for which there is a standard formula), or you can assume x1=0 and x2=1, and express x as a float between 0 and 1 (for which there is a similar standard formula), or you can express x as a ratio by provided the total number of steps and the current step number, and convert that to a float. (This is useful when you have a known number of steps, but providing a float is more general.)

Interpolation also makes sense where x is replaced by time (what will be the value of y at a certain time). Interpolation also makes sense where y is replaced by a coordinate (a tuple).

The animation feature of Kivy offers a "linear" transition which uses linear interpolation, where one axis is time and the other is an screen coordinate.

So far, so good. But this is where I get a little harsh.

`kivy.utils` offers a function called `interpolate()` and the problem is... it is completely useless for performing interpolations!

It takes the two values of y (`value_from` and `value_to`), it assumes x1= 0 and x2 = 1, but rather than take x as a fraction, or taking two parameters, `step_no` and `total_steps`, it only takes one parameter (called `step` but effectively `total_steps`) and assumes `step_no` = 1.

You can find out where y would be when x=1/10. By changing the parameters, you could find out where y would be when x is 1/2, 1/3, 1/4 etc.

This is a blatant bug. The function is useless for its purpose.

What is worse is that it has a comment that overpromises what it can achieve:

         '''Interpolate between two values. This can be useful for smoothing some
         transitions. For example::

        # instead of setting directly
        self.pos = pos

        # use interpolate, and you'll have a nicer transition
        self.pos = interpolate(self.pos, new_pos)

Firstly, the first line is a single operation and it is done, where the second one needs to be scheduled to be repeated over and over again. There is already infrastructure to do this on the user's behalf: `animation`, and we should recommend that.

Secondly, because of the not-fit-for-purpose bug in the function signature, using this will not linearly move something towards its destination, but merely move it 10% of the remaining distance each time, so that, like Zeno's arrow, it never makes it.

To fix the function, we need to fix the signature, so it takes a fraction.

This is an API break - and a challenging one because some old code may not fail, just give bad answers. However, I don't feel bad because I can't believe the existing function is actually used as is by any substantial piece of software; it doesn't do anything useful. 

In fact, I think a much better suggestion is just to deprecate the whole thing and remove it as soon as we can. It isn't worth saving.
