### ISSUE TITLE
Add a way to manually add frames to an Image animation

### ISSUE THREAD

**Issue by CreamyCookie** [kivy/kivy#2848]
The `Image` class (from `kivy.uix.image`) currently doesn't allow to add (or remove) frames from an atlas or other sources, like multiple `.png` files (not `zip` or `gif`).

It also seems that the current index (which determines the current frame) isn't exposed, so one can't synchronize all the animations to the same index.
##

**Comment by victor-rene** [comment]
Wait... sorry, I think you have  to do the synch work yourself. It should not be so difficult, and extra work is always necessary when you need such fine control. Also you didn't define exactly what is Image animation. Is it zip/png or gif?

**Comment by snapy666** [comment]
@victor-rene No, I don't want to use `.zip` or `.gif`, but plain `.png` files or images from an atlas. But there's `anim_delay`, `anim_loop` — why not expose `_anim_index`?

**Comment by victor-rene** [comment]
@snapy666 From what I understand, the Image isn't supposed to support such behavior. Providing the ability to add / remove frames means that the texture array has to be rebuilt. Also exposing the anim_index can lead to problems such as getting or setting an invalid one, because the size of the texture array has become variable.

Maybe one last thing. [Open for extension/Closed to change](http://en.wikipedia.org/wiki/Open/closed_principle). Unless there is bug with the class, it would be better to create another one that does what you need it to do.

**Comment by dessant** [comment]
We are closing some of the stale issues, please create a new issue/pr if you'd like to work on this feature, or get in touch with us on #kivy-dev.
