### ISSUE TITLE
Old licensing info

### ISSUE THREAD

**Issue by dessant** [kivy/kivy#2902]
https://github.com/kivy/kivy/pull/2901/files#r23507160

He mentioned finding old licensing info in 16 places.

**Comment by thopiekar** [comment]
16 places?
We've got 10 different packages per architecture also somewhere else then debian/control?

**Comment by dessant** [comment]
He probably missed something.

**Comment by dessant** [comment]
No, he was right:
https://github.com/kivy/kivy/blob/master/kivy/tools/packaging/linux/debian/control

**Comment by dessant** [comment]
@thopiekar are these files usually synced with your debian branches?
https://github.com/kivy/kivy/tree/master/kivy/tools/packaging/linux/debian

**Comment by thopiekar** [comment]
Ahh ok, needs to be synced with the upstream files..

**Comment by thopiekar** [comment]
@dessant , yes, often before release. Sometimes @tito is to fast and synced afterwards ;)

When do you plan to release 1.9.0?

**Comment by dessant** [comment]
@thopiekar we plan it every day :D, but i'm not sure.

**Comment by thopiekar** [comment]
There should be everything you want in #2910 and #2911 ;)
But be careful there are also other changes I made which I found very useful, e.g. https://github.com/kivy/kivy/pull/2911/files#diff-b67911656ef5d18c4ae36cb6741b7965R34
It will make doc builds in different formats faster because kivy does not need to be recompiled...

**Comment by dessant** [comment]
Fixed, awesome job @thopiekar. :ice_cream:

**Comment by thopiekar** [comment]
Thanks :)
