### ISSUE TITLE
Feature Request: Section on unit testing Kivy apps, esp. kvlang portions, in the Prog. Guide

### ISSUE THREAD

**Issue by OlyDLG** [kivy/kivy#3018]
Hi! I'd like to suggest/request that a section on methods for unit testing Kivy apps, especially those portions that rely on kvlang files, be added to the "Programming Guide."  Example topics: efficient instantiation of kivy objects for the purpose of testing; strategies for testing event triggering and handling; efficient ways to test kv file-assigned attribute values; etc. (Suggestions from people with experience unit testing Kivy apps encouraged.) Thanks!
##

**Comment by merriam** [comment]
Are you foreseeing:

* Expanding on http://kivy.org/docs/contribute-unittest.html#gl-unit-tests. 
* Getting a better profiling, like 'profiling with on_start' in http://kivy.org/docs/api-kivy.app.html
* Better KIVY_PROFILE_LANG=1
* Better debugging like http://kivy.org/docs/api-kivy.modules.webdebugger.html.
* Better interaction like demo/kivycatalog?

Something else?

**Comment by OlyDLG** [comment]
Thanks for the links, I'll check them out.  When you say "foreseeing," do you mean that these pages are still "pre-official-release"?

DLG

**Comment by KeyWeeUsr** [comment]
Quite dead here, but no docs yet, afaik. It'd be nice to have a section about unittesting the apps themselves, so I have an idea. I made a mini-tutorial for [KivyUnitTest](https://github.com/KeyWeeUsr/KivyUnitTest/) when I was kind of lost in testing the app directly(not separate functions, working with running `App`). Read it, I can edit it and make a PR.

About testing layouts/widgets/attributes written in kv-lang, there's even `Factory` for that(e.g. `<Custom@Label>` == `Factory.Custom`). If you get into the main loop, it's super-easy to locate an instance of whatever class you like and then it's only about writing it correctly. Even unregistered classes, such as the icon image in `ActionBar`, because you can still access `<widget>.children` and trace it through that.

@merriam not sure, but I bet he didn't mean testing the core directly :yum: (and what's with that profiling anyway?)

@victor-rene ping

**Comment by KeyWeeUsr** [comment]
Closed by #5433
