### ISSUE TITLE
on_touch_down on defined widgets triggers on all widgets of the same type

### ISSUE THREAD

**Issue by fscz** [kivy/kivy#3079]
Steps to reproduce: 
1. Take the official pong example
2. add method

    def on_touch_down(self, touch):
        print ('down')
        return super(PongPaddle, self).on_touch_down(touch)

3. start the game
4. click one of the paddles
5. keep your composure while watching how 'down' is printed twice.

**Comment by victor-rene** [comment]
I usually do it this way instead:

    def on_touch_down(self, touch):
        if self.collide_point(touch.x, touch.y):
            print ('down')
        return super(PongPaddle, self).on_touch_down(touch)

Hope it helps.

**Comment by victor-rene** [comment]
I had to search for a while. From http://kivy.org/docs/api-kivy.uix.widget.html, at the top in the description of the module.

> Widget.on_touch_down(), Widget.on_touch_move(), Widget.on_touch_up() don’t do any sort of collisions. If you want to know if the touch is inside your widget, use Widget.collide_point().

**Comment by fscz** [comment]
Thanks. I fixed it in kivy/uix/widget.py by modifying the on_touch_down method there

    def on_touch_down(self, touch):
        '''Receive a touch down event.                                                                                                                                                        
                                                                                                                                                                                              
        :Parameters:                                                                                                                                                                          
            `touch`: :class:`~kivy.input.motionevent.MotionEvent` class                                                                                                                       
                Touch received. The touch is in parent coordinates. See                                                                                                                       
                :mod:`~kivy.uix.relativelayout` for a discussion on                                                                                                                           
                coordinate systems.                                                                                                                                                           
                                                                                                                                                                                              
        :Returns:                                                                                                                                                                             
            bool. If True, the dispatching of the touch event will stop.                                                                                                                      
        '''

        if self.disabled and self.collide_point(*touch.pos):
            return True

        for child in self.children[:]:
            if not child.collide_point(touch.pos[0], touch.pos[1]):
                continue

            if child.dispatch('on_touch_down', touch):
                return True


The change is in the for loop, where I dispatch the event only to children that have actually been hit.

**Comment by victor-rene** [comment]
Hmm, this is an interesting change indeed. I always thought this behavior was not intuitive. Although I could live with it. I wonder what the core team thinks of this.

**Comment by fscz** [comment]
Me too. Why should a user do the hit test himself? Is this a performance issue? I really doubt that the impact of this is critical in 99% of the cases. There could be a  config option: perform_hit_tests myself. Though I somehow doubt, it would be used very often.

**Comment by fscz** [comment]
You can add the same procedure to the 'on_touch_up' and 'on_touch_move' methods in widget.py

**Comment by jeffsenn** [comment]
Illuminating thought experiment (or you could actually try it for real):  

With such changes in place, implement a button that has the normal "highlight on touch down", "maintain highlight when touch is within or moves back within" and "actuate on touch up but only when touch is within button".  Put more than one of these next to each other on the screen.

**Comment by dessant** [comment]
This happens by design, use ButtonBehavior with on_press/on_release if you need collision detection.

**Comment by fscz** [comment]
And then he just closed it... this is ridiculous. @jeffsenn I have implemented what you asked for. Seriously guys. You cant' call a touch listener on a widget that was not touched. You library will go nowhere. If you stick with this nonsense. And I would hate to see that, because it has potential and I've made the changes to fix this event mess.

**Comment by tshirtman** [comment]
on_touch_* methods are low level, they give flexibility to implement a lot of things, including invisible widgets that handle inputs from everywhere, this is very useful, and introducing such a change would break a *lot* of applications, just try the showcase example, i'm pretty sure it's broken all over the place.

**Comment by akshayaurora** [comment]
Kivy's philosophy on widget is to keep them open for adjustment,  there are many use cases for when you need to detect touch collision with another widget or when a widget needs to know when some place else on the screen was touched,  this opens the possibility of a lot of new and interesting use cases that are needed in custom user interfaces.

This has been asked and answered numerous times before.  This is mentioned in the documentation clearly that you need to do your collision check yourself. This is also  mentioned on numerous posts on kivy-users and issues here.

If we limit the widgets the way you mention then it will not only stop most of the apps that depend on this feature from working, this would then force users to create their own base classes from scratch.

Base classes like widget need to be open,  take a look at Button, that implements this collision cause it needs it.

**Comment by fscz** [comment]
So Kivy wants to offer to both game development and ui/form application development. I have done both and I see why you would want a notion of some object that has coordinates and can somehow be rendered on a screen.

Yet as of now these two concepts (game / form) collide in somewhat unfavourably in kivy. Another spot where people tend to get confused is the thing with relative / absolute positions of widgets.

When you are developing a regular user interface this and the ontouch events for untouched widgets feels awkward and wrong.

A simple way out might be to offer 2 application classes to derive from. --- FormApplication does all the hittesting for you and positions child widgets relative by default
- GameApplication leaves all that to you

Another way would be to implement 2 view trees.
- One gameview (which might contain only the root node Widget in the beginning)
- Another AppView tree, where things behave like in a normal application

**Comment by fscz** [comment]
One other thing: In game development I can't think of a case where you would want to make one view object a child of another. In games you have objects at positions in a unified coordinate system and a camera that moves and looks around. You are trying two things that are very different. They should be clearly separate.

**Comment by inclement** [comment]
Are you aware of the canvas and how it works? This is the low level absolute-coordinates system that one would generally base the graphical part of a game on, though the widget system is very suitable for the rest of the interface.

You could also build simpler games (where the python parts and events of widgets don't cause too much slowdown) with widget composition alone, taking full advantage of the widget tree to draw everything. There isn't really a barrier to using an absolute coordinate system here. But the main reason for not doing this on a large scale is that widgets are relatively slow (not in an absolute sense, but when working with many at once).

(Of course there's also a large class of games for which widgets are fine, but I think you aren't talking about these?)

**Comment by fscz** [comment]
I am aware of the canvas and I am using it to some degree in my project. Just backgrounds and so on. Well. I think if widget IS intended for form applications than all widgets should act as relative layouts for their children and they should hittest.Having a base game object sounds like a good idea, but one thing I learned about game dev is that there usually is no single base game object. Whether a GO needs to be drawn, collides, listens to events, etc depends on each GO. 

I like the idea of keeping widget or SOME notion of a widget as open as possible. But in this case the current widget already does too much. In my game there were little pets on the map that moved around (and barked, etc) but they did not collide with the player, the enemies or projectiles. Also they didnt respond to user input. There was no need to deliver such events to them.

**Comment by inclement** [comment]
If you want to optimise the widget system to work with game objects, you can create your own widgets that improve dispatching in the way you want.

>  Also they didnt respond to user input. There was no need to deliver such events to them.

For instance, you could arrange for touch events to not be dispatched to these children by modifying on_touch_down of their parent appropriately.

However, what I really meant in my previous post is that widgets will tend to be unsuitable when used in bulk like this precisely because they are not performant at large scales due to all the events etc associated with them - widgets are not necessarily designed to function well as game objects, or optimised much for that purpose, though I guess you've already found that they can work okay at reasonable scales.

What I meant with the canvas instructions is that a normal way to handle a more complex game would be to have a main Widget rendering the game, and have each game object rendered with a canvas instruction optimised to your purpose. This will be much faster and more scalabel in multiple ways, at the cost of being lower level and needing more management.

If you haven't already seen it, you might be interested in [kivent](https://github.com/Kovak/KivEnt). This makes an interesting use of the widget system to manage components of an entity system, and the user interface of a game, but then manages everything else in an optimised way via canvas instructions (including advanced mesh combination etc).

**Comment by tshirtman** [comment]
Seriously, you want to change a very fundamental assumption of the framework, when there are clear solutions to the "issue" you are facing, and that this assumption is clearly documented, it may be a surprise to newcomers, but it's like this for a reason, and i don't see in changing any time soon.

**Comment by dessant** [comment]
@fscz perhaps it would make more sense to continue this discussion in the comments of a PR which implements the changes you mentioned.

**Comment by fscz** [comment]
@inclement Thanks. I am developing a form application right now. But already have another game project on the table.

@tshirtman Pity.

@dessant I agree. Here is the thing. I want to get my project done. Thats first. However I really like Kivy. I think there is nothing comparable right now. And I would like to use it in the future. I would put in the work to rebase my changes to 1.9 (currently 1.8) if people are open minded towards such changes. As @tshirtman has said, what I want to have presents a drastic change. However more philosophically. It's actually not too much code to change.

**Comment by tshirtman** [comment]
It's not much code to change *here*, but it'll break thing all over the place, *in* and *out* of kivy (in projects using it). *and* it's an important philosophical change too, that we don't really want, because it brings flexibility at a very small cost, and that the way you propose to solving it (adding a few new base classes) would bring quite some unneeded complexity, for everybody, seriously, no.

**Comment by fscz** [comment]
We are already past the need for new base classes. From earlier comments I thought that the idea for Widget was to serve as both a base GameObject and you know a widget/view. As we found out that is not the case. So I think without too much trouble you could make Widget by default a) hittest for collision b) layout its children relative to its own position. That is the change I propose. 

If you put that into a new release it doesnt break existing projects. New users will love it. 

What are the use cases where this flexibility you @tshirtman mentioned would suffer?

**Comment by tshirtman** [comment]
```
 So I think without too much trouble you could make Widget by default a) hittest for collision b) layout its children relative to its own position. That is the change I propose. 
```

So you think we can change like, two of the most fundamental assumptions of the framework, without much trouble? I'll have to respectfully — but strongly — disagree.

I could come up with use cases, and you'd come up with classes we could have to segment these in different needs and behavior, but it wouldn't change the fact that introducing such change would break everything under the sun in kivy land, and that it's totally superfluous, because it wouldn't fix any existing problems.

In the hope that this will close this debate for good, sincerly.

**Comment by tito** [comment]
Hi,

Honestly, when i try to think about the argument of having or not collision testing by default,  i feel myself in a bad position. As both side have great point / disadvantage. 

Based on the current situtation / choice:

Pro:
- performance: the less you do in the touch down, the better it is when dispatching events.
- what you see visually can actually be touched. Because our canvas is abstract and have no visual limitation, If you put a Scatter inside any Widget, the Widget will always pass the event to the Scatter.
- it's easy to put another layer widget that just watch touch and do gesture detection, or add visual graphics in top of a current one

Cons:
- not widely understood. Again, this issue raise the fact our documentation might not been understood
- if we put collision detection, it would consume more CPU (especially with Matrix-based widget), and lead to a direct impact on the application performance.
- the solution took the decision to do it only on the touch_down. What about all the move / up? If you decide to do the collision detection, why not after it? If the touch is not grabbed, collision detection must be done as well. If the touch is grabbed, when it really depend on the final usage. There is no ideal solution here.
- doing collision detection might help to reduce the cost of a tree traversal, but the balance is unknown (doing it VS not doing it, depending the tree).
- if it's done, it need to be customizable / deactivable. For the Scatter issue, you need a way to get touch no matter the parent said, if the Scatter is going a little bit out of the bounds.

Whatever we choose, you can see in others toolkit that to be able to achieve all the possible things, they still do the collision detection by default, but implemeted lot of various way to get events and work with them.

Even your solution is not ideal, you took the decision to restrict the event dispatching from the parent. You could have taken the path to do it in the widget itself.

Appart from that, we cannot agreed for a such change, as it's an API breaker. Any changes like that can be proposed and discussed for what we call Kivy 2.0. See https://github.com/kivy/kivy/wiki/Kivy-2.0-api-breaks for more informations. :)
