### ISSUE TITLE
uix.switch.Switch widget should use non graphic design

### ISSUE THREAD

**Issue by jtownley** [kivy/kivy#3163]
To support il8n efforts and customizability of switch widget. I would suggest that the switch widget be made without a requirement on the ON/OFF graphics. I would further expected that optional text fields could be set for both the on on off positions.
##

**Comment by picibucor** [comment]
:+1:

**Comment by dessant** [comment]
The text was removed from the images, though we concluded that customizing the text is not a general solution for i18n, because the relevant words can have a varying length, producing incosistent and ugly results in some cases. This is why most ui toolkits are now opting to show a label near the switch.

**Comment by KeyWeeUsr** [comment]
However, the instructions on canvas are separated, therefore now you can use the last piece of code to cover the text manually. #4586
