### ISSUE TITLE
Installation fail on mac os (clang: error: no such file or directory camera_avfoundation_implem.m)

### ISSUE THREAD

**Issue by satels** [kivy/kivy#3320]
pip install kivy==1.9.0

```bash
static CYTHON_INLINE long __Pyx_PyInt_As_long(PyObject *x) {

                          ^

12 warnings generated.

cc -fno-strict-aliasing -fno-common -dynamic -arch x86_64 -arch i386 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch x86_64 -arch i386 -pipe -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c /Users/admin/workspace/exapp/env/build/kivy/kivy/core/camera/camera_avfoundation_implem.m -o build/temp.macosx-10.10-intel-2.7/Users/admin/workspace/exapp/env/build/kivy/kivy/core/camera/camera_avfoundation_implem.o -F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks -ObjC++

clang: error: no such file or directory: '/Users/admin/workspace/exapp/env/build/kivy/kivy/core/camera/camera_avfoundation_implem.m'

clang: error: no input files

 error: command 'cc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /Users/admin/workspace/exapp/env/bin/python -c "import setuptools, tokenize;__file__='/Users/admin/workspace/exapp/env/build/kivy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/b8/2fbbzdj14dzdfzgxyk7qlqqh0000gn/T/pip-9Ok6LR-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/admin/workspace/exapp/env/include/site/python2.7 failed with error code 1 in /Users/admin/workspace/exapp/env/build/kivy
Storing debug log for failure in /Users/admin/.pip/pip.log
```

**Comment by dessant** [comment]
Have you installed all the deps which are normally taken care of in the osx package?

**Comment by SuperFoodIQ** [comment]
Taken from my github post:

AVFoundation has never worked properly w/ MacOSX after 10, 6. If you are trying to build, do the following. 

This is what I did to build from source -- (Do the obvious & make sure xcode is at latest, etc..)
1:) git clone http://github.com/kivy/kivy 
2:) cd kivy
3:) Make backup of setup.py: cp setup.py setup.py.bk
4:) Edit setup.py: vi setup.py 
5:) :712 (go to line 712) and you will see this 
if mac_ver >= [10, 7]:

Comment out this line w/ a #
#if mac_ver >=[10, 7]:
and add:
if mac_ver <= [10, 6]:

To determine your mac_ver use the above line in a simple python script:

import platform as _platform
mac_ver = [int(x) for x in _platform.mac_ver()[0].split('.')[:2]]
print mac_ver

Or make sure that 'use_avfoundation' returns false/0

6:) make 
7:) if no further errors run: make install

Fixed... 
End result:
running install_egg_info
Writing /Library/Python/2.7/site-packages/Kivy-1.9.1_dev-py2.7.egg-info

After more digging and playing w/ this in objc and going through lots of header files, you can see that after 10.6 this functionality is deprecated.  I understand why the kivy team has not updated this since it is *NOT* documented by Apple. Not that its an excuse as the header files that are needed are out there to update the Kivy code to make this compile properly w/ camera support and the other functionality given by these objects.

/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/ApplicationServices.framework/Frameworks/QD.framework/Headers

ColorSyncDeprecated.h shows that this functionality has been deprecated since 10.6.

Setup.py should be updated to use the old frame work if you are <= 10, 6 and if you are >=[10, 7] then use the new functions.  This is a bug - I have verified the build and functionality on 10, 6 but, have yet to do the work to fix on >= [10, 7] and since i do not use this functionality am providing this information.

**Comment by andreif** [comment]
Related discussion in #3309

**Comment by garyjohnson** [comment]
Occurs with the latest on PyPi (1.9.0) but doesn't occur when building from source (1.9.1). Has this been fixed? Hopefully a new PyPi package will be created soon. The current one just doesn't install on OSX.

**Comment by JasonBates** [comment]
Confirm this is still a problem. 'pip install kivy' generates error message above on OSX 10.10.4

**Comment by m1yag1** [comment]
I've installed all deps and have encountered this issue using pip on OSX 10.10.5

**Comment by codyit** [comment]
Confirm that building with 1.9.0 fails and `pip install git+https://github.com/kivy/kivy.git@master` works fine

**Comment by cbenhagen** [comment]
What is even funnier is that `pip install git+https://github.com/kivy/kivy.git@1.9.0` also works. Why could that be?

Btw a full installation of version 1.9.0 on OSX can be done like this:
```
brew install sdl2 sdl2_image sdl2_ttf sdl2_mixer gstreamer
USE_OSX_FRAMEWORKS=0 pip install -vU git+https://github.com/kivy/kivy.git@1.9.0
```

**Comment by krazybean** [comment]
@cbenhagen second set of instructions worked for me, looks like i was missing the sd12 deps.

**Comment by cbenhagen** [comment]
Actually I don't think this is what's causing this. As `USE_OSX_FRAMEWORKS=0 pip install kivy==1.9.0` would not work on my system. So there must be something with the installation from the pypi repo.

**Comment by m1yag1** [comment]
Would it be a good idea to update the docs to include the brew dependencies sdl2, sdl2_image, etc.?

**Comment by cbenhagen** [comment]
https://github.com/kivy/kivy/pull/3679 ;)
