### ISSUE TITLE
No readme.txt & example folder in Mac OS X dmg

### ISSUE THREAD

**Issue by angadgill** [kivy/kivy#3337]
I just installed Kivy on Mac OS X 10.10.3. I followed the instructions on http://kivy.org/docs/installation/installation-macosx.html and downloaded http://kivy.org/downloads/1.9.0/Kivy-1.9.0-rev3-osx.dmg. The instructions say that it should have a Readme.txt and an example folder, but these aren't actually there, see attached.
![screen shot 2015-05-05 at 7 25 02 pm](https://cloud.githubusercontent.com/assets/3976441/7486620/ad9382e2-f35c-11e4-9099-e745841ee605.png)

Either the dmg is missing something or the instructions need to be updated (or I'm missing something).

Kivy installed just fine.

**Comment by Luthien-in-edhil** [comment]
I can confirm this on OSX 10.10.3 / Python 2.7.6
Downloaded the installer, opened .dmg: contains Kivy.app and executable MakeSymLinks script, but no readme file. 
However, if you open the Kivy.app (right mouse click, "Show Package Contents, you'll find everything missing under Contents/Resources/Kivy: not just the readme, but all the documentation, examples, etcetera.
It looks as if it wasn't packaged properly and all user accesible content ended up inside the .app folder (which normally appears as a file). This is indeed a bit confusing, I hope it will be fixed in the next release. 
For now you can copy the contents that you want to access and put it in a more convenient place

I ran the MakeSymLinks script and can run Kivy on the command line, which gives me a Python environment. But Kivy as application doesn't start up by double clicking it ... I'm trying to figure out why, as soon as I figure that out I'll update this reply.

**Comment by dessant** [comment]
Doc will be updated to reflect this in https://github.com/kivy/kivy/pull/3878/files#diff-2811d5f56dda479f26ed6be099b7d522R20.
