### ISSUE TITLE
Regression: Scrollview is Jumpy not smooth

### ISSUE THREAD

**Issue by rainbowdesign** [kivy/kivy#3516]
Hello,
i made a program with Scrollview in kivy 1.7 it holds a gridlayout which holds several 100 buttons and is rather heavy.
On kivy 1.7 it work just fine.
On kivy 1.9 it does the scrolling is not smooth it rather jumps also it forgets input in other words its totally not useable.
In both cases the cpu usage is going up i did test it on windows only.

**Comment by rainbowdesign** [comment]
One More addition this issue seems to concern scatter too so it is likely a bit deeper in the system.

**Comment by matham** [comment]
I'm sorry, but this is not a real reproducible issue. Just saying that CPU increased and that it "forgets input" (what does that even mean?) or that it jumps is not a substitute for reproducible code showing a issue or at least an intelligible description of the issue.

And what does "One More addition this issue seems to concern scatter too however in my case not directly after loading but after trying a bit so it is likely a bit deeper in the system." even mean?

I'd thank you to stop opening issues about already documented usage, or vague issues lacking any attempt to fully describe the problem.
