### ISSUE TITLE
OS X 10.10 not compiling package for osx

### ISSUE THREAD

**Issue by ryansehrlich** [kivy/kivy#3527]
Hi, I'm trying to compile a simple Kivy Application into a package for OS X. I'm doing what it says to do in the documentation, and here is the result:

rEhrlichs' MBP:Kivy Ryan$ git clone https://github.com/kivy/kivy-sdk-packager
Cloning into 'kivy-sdk-packager'...
remote: Counting objects: 333, done.
remote: Total 333 (delta 0), reused 0 (delta 0), pack-reused 333
Receiving objects: 100% (333/333), 206.00 KiB | 248.00 KiB/s, done.
Resolving deltas: 100% (174/174), done.
Checking connectivity... done
rEhrlichs' MBP:Kivy Ryan$ cd kivy-sdk-packager/osx/
rEhrlichs' MBP:osx Ryan$ cp -a /Applications/Kivy.app/ ./Kivy.app
rEhrlichs' MBP:osx Ryan$ ./package-app.sh /Users/Ryan/Desktop/Email\ Finder/Kivy/test1.py
+ '[' 'X/Users/Ryan/Desktop/Email Finder/Kivy/test1.py' == X ']'
+ set -e
+ SCRIPT_PATH=./package-app.sh
+ '[' -h ./package-app.sh ']'
++ python -c 'import os; print os.path.realpath(os.path.dirname('\''./package-app.sh'\''))'
+ SCRIPT_PATH='/Users/Ryan/Desktop/Email Finder/Kivy/kivy-sdk-packager/osx'
+ KIVY_APP='/Users/Ryan/Desktop/Email Finder/Kivy/kivy-sdk-packager/osx/Kivy.app'
+ '[' '!' -f '/Users/Ryan/Desktop/Email Finder/Kivy/kivy-sdk-packager/osx/Kivy.app' ']'
+ echo 'No Kivy.app generated, use create-osx-bundle.sh first.'
No Kivy.app generated, use create-osx-bundle.sh first.
+ echo '-- Get the name of your app'
-- Get the name of your app
++ basename /Users/Ryan/Desktop/Email Finder/Kivy/test1.py
+ APPNAME=Email
+ APPPATH='/Users/Ryan/Desktop/Email Finder/Kivy/kivy-sdk-packager/osx/Email.app'
+ echo 'Hello, Email'
Hello, Email
+ echo '-- Duplicate the Kivy.app to Email.app'
-- Duplicate the Kivy.app to Email.app
+ cp -a /Users/Ryan/Desktop/Email Finder/Kivy/kivy-sdk-packager/osx/Kivy.app /Users/Ryan/Desktop/Email Finder/Kivy/kivy-sdk-packager/osx/Email.app
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file ... target_directory
rEhrlichs' MBP:osx Ryan$ ls
Kivy.app		create-osx-bundle.sh	data
README.md		create-osx-dmg.sh	package-app.sh
rEhrlichs' MBP:osx Ryan$ 

Any Help is apprecaited. Thank You so much

**Comment by kived** [comment]
To work around this for now, try removing the space from the path - i.e.
EmailFinder instead of Email Finder. Also, I've never packaged apps for OS
X, but I would imagine it works like the other packaging tools. So you
should be providing the path to the app folder, rather than a single Python
file, and that folder should contain a main.py which will be the entry
point to your application. Also the folder needs to match the name of your
app - .../EmailFinder/Kivy will result in an app named Kivy.

Also, this is a bug in kivy-sdk-packager, not kivy. Please submit this bug
report at https://github.com/kivy/kivy-sdk-packager/issues/new

**Comment by ryansehrlich** [comment]
Thank you so much! I really appreciate it!
