### ISSUE TITLE
Kivy Truck Factor

### ISSUE THREAD

**Issue by gavelino** [kivy/kivy#3544]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **Kivy** and obtained a value of **1**.

The developer responsible for this TF is:

Mathieu Virbel - author of 78% of the files 

To validate our results, we would like to ask **Kivy** developers the following three brief questions:

(a) Do you agree that the listed developer is the main developer of **Kivy**?

(b) Do you agree that **Kivy** will be in trouble if the listed developer leave the project (e.g., if he wins in the lottery, to be less morbid)?

(b) Does **Kivy** have some characteristics that would attenuate the loss of the listed developer (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by dessant** [comment]
Give us a break.

**Comment by tshirtman** [comment]
@tito has been crutial in kivy's inception, and his contribution is always a great factor of advances, but kivy has lived on and improved even when he focused on other projects (including his own business) and for about two years, the project have proven to be able to live on without his continued engagement.

so 
a) yes and no, historically yes, currently no, a team has been picking up the activity, your analysis seems to be biased on capital (existing files) rather than activity (current commits).

b) no, although it would be an immense loss, the project is living on

c) the documentation has not only contributed to the community expansion, but has also been contributed back a lot by the rest of the core team and other external contributors. Other factors could be the relative uniqueness of kivy properties, and the popularity of one of its use case, with an essential lack of alternatives, driving a lot of people to use kivy and improve it. Also, the code being considered very legible (for the most part), makes for shortcomings of the documentation, and allows for external contributors to quickly contribute improvements.

You may be interested of models of "ownership" taking into consideration the "adoption" of files — or rather, features — by new contributors, commits changing a file indicate that new knowledge is acquired by them, and that they now partially "own" the file.

reading the beginning of your paper, i don't think your assumption that DL and AC can't contribute as much as FA is valid, if the file has been extensively reworked, even in 1 commit, the original author may have no idea of the current content.

**Comment by tshirtman** [comment]
Also, this issue was closed and locked because we don't consider it an issue, but you can contact us on the kivy-dev google groups if you wish to continue this discussion.

Thanks for your consideration.
