### ISSUE TITLE
ScatterLayout objects inside a StencilView still receive clicks outside of stencil area

### ISSUE THREAD

**Issue by snuq** [kivy/kivy#3562]
Kivy Version: 1.9.0
When a ScatterLayout object is placed inside a StencilView, and if the ScatterLayout is larger than the StencilView, it will still receive click/touch events in the areas that are not visible, blocking other widgets.
I got around this by overriding the on_touch_down function with:
```
if self.collide_point(*touch.pos): super(ScatterImage, self).on_touch_down(touch)
```
but this seems to be unexpected default behavior.

An example program to show the issue follows - just move the stencil area object up a bit to see it block the button.
```
import kivy
from kivy.app import App
from kivy.lang import Builder
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.scatterlayout import ScatterLayout

mainscreen = '''
<MainScreen>
    orientation: 'vertical'
    Button:
        text: "Click Me, But Only If I'm Not Blocked!"
        size_hint: 1, .2
    StencilView:
        size_hint: 1, .8
        ScatterLayout:
            width: root.width
            height: self.parent.height
            size_hint: None, None
            Label:
                canvas.before:
                    Color:
                        rgb: .5, .5, .5
                    Rectangle:
                        size: self.size
                        pos: self.pos
                text: 'Stencil Area'
'''

class MainScreen(BoxLayout):
    Builder.load_string(mainscreen)

class StencilTest(App):
    def build(self):
        return MainScreen()

if __name__ in ('__main__', '__android__'):
    StencilTest().run()
```

**Comment by tshirtman** [comment]
Do you mean StencilView should only propagate if self.collide_point() returns True? It would be quite a change, since most (all?) widgets in kivy don't check for that by default, so it could be counter intuitive to people that are used to the way kivy works, it could also break current applications, if they do rely on this behavior (it would be an api change),

**Comment by matham** [comment]
Exactly what @tshirtman said. It'd be inconsistent with the rest of kivy and to make it work for your example just requires checking `if collide`.

**Comment by snuq** [comment]
I was just thinking of a small change in the way stencilview works - that you shouldn't be able to click on an area that is stenciled out and no longer visible, and that a non-visible area should not block clicks to other widgets that are visible.
If you are afraid that changing the default behavior might break an app, what about adding a boolean option to the stencilview widget - stencil_touches = True, or something?
If nothing else, there should be a notice in the documentation for the stencilview widget that lets people know that it does not stencil clicks, and the best way to make it do so.

**Comment by tshirtman** [comment]
the best way, as with any widget on which you want this behavior, is to subclass and override 'on_touch_down' / 'on_touch_move' / 'on_touch_up', to use 'collide_point' before calling super and grab (in down), and check 'grab_current' before calling super (in the others).

**Comment by tshirtman** [comment]
now, that, maybe, could be made into a simple behavior, to. eas

**Comment by schneeammer** [comment]
I'm sorry but as snuq mentioned it is really counter-intuitive that you click on the invisible widget (that has been "stenciled out") instead of the visible button.

Could you help me how to achieve the other behavior (i.e. i can click on the visible button)? I started with kivy only yesterday and I can't really follow your advises:
>  just requires checking `if collide`.

> the best way, as with any widget on which you want this behavior, is to subclass and override 'on_touch_down' / 'on_touch_move' / 'on_touch_up', to use 'collide_point' before calling super and grab (in down), and check 'grab_current' before calling super (in the others).

Do I have to add all these to my custom class ScatterImage:
```
def on_touch_down(self, touch):
    if self.collide_point(*touch.pos):
        super(ScatterImage, self).on_touch_down(touch)
def on_touch_move(self, touch):
    if self.grab_current(*touch.pos):
        super(ScatterImage, self).on_touch_down(touch)
def on_touch_up(self, touch):
    if self.grab_current(*touch.pos):
        super(ScatterImage, self).on_touch_down(touch)
```

Can you also give an example, where you would prefer the current behavior (I.e. that a click should be "handled" by the invisible Stecil part instead of the visible widget below it)?

Sorry for asking stupid questions ^^
