### ISSUE TITLE
ScrollView stops working after exporting its content to png using export_to_png

### ISSUE THREAD

**Issue by wzet** [kivy/kivy#3589]
Example to reproduce the error: 
http://pastebin.com/jv3vu0iW

Output:
Exception ValueError: 'list.remove(x): x not in list' in 'kivy.graphics.instructions.Instruction.rremove' ignored

**Comment by tshirtman** [comment]
The issue likely comes from the `self.parent.canvas.remove` line, since ScrollView manipulates its canvas (as seen in its add_widget overriding), and indeed, a dirty workaround is to add an intermediate widget between the widget to capture and the ScrollView (i used another GridLayout, but anything correctly containing the current GridLayout would do).

This doesn't give an easy solution, though, maybe ScrollView should avoid adding an indirection to its canvas, or export_to_png should use a function or AliasProperty to get the actual canvas, and ScrollView would override it.

**Comment by tshirtman** [comment]
hm, actually, checking that `canvas_parent_index' is not -1 does seem to fix the issue, not sure it's 100% harmless though.
