### ISSUE TITLE
.kv file encoding issue

### ISSUE THREAD

**Issue by bamanow** [kivy/kivy#364]
My setup is Win7 x64 Ultimate with latest version of Kivy. I use 
 Notepad++ for python development. 
 Now Notepad++ by default is set to use UTF-8 encoding. When I save .kv 
 files in this encoding 
 parser fails. But when I encode it in ANSI there is no problem. 
 I know it is not a very big problem. But it annoys a little. 
 Is it by design?

Parser says: 
'Invalid data after declaration'
kivy.lang.ParserError: File "<inline>", line 0:

to reproduce:
go to \Kivy-1.0.9-w32\kivy\examples\guide\designwithkv
replace controller.kv file with exactly same file, BUT with utf-8 encoding (with BOM)
now run main.py
voila :)
error!

**Comment by VinGarcia** [comment]
Sorry to re-open an old issue, but I have a problem that is very similar to this one.

I'm developing a multi-platform app for Linux and Windows 7. All my files were first written on Linux and encoded as `utf-8`, but when I open this same project on Windows the `kv` file is read as if encoded with `cp1252`. The same thing does not seems to happen to my `.py` files maybe because I'm using python3.

As a consequence the Unicode characters written on the `kv` file won't render correctlly on the Kivy app. The string `'Título'` will show as `TÃ-tulo`.

My settings are: Kivy=1.9.1, Python=3.4.4, Windows 7 x64 Home Premium.

### To reproduce the problem:

Write a `kv` file encoded with Unicode:

```python
# test.kv
<myButton@Button>:
    text: 'Título'
```

On python interpreter or `.py` script:

```python
import kivy
from kivy.lang import Builder
from kivy.uix.button import Button

Builder.load_file('test.kv')
class myButton(Button):
    pass

print( myButton().text == 'Título' ) # False
print( myButton().text.encode('cp1252').decode() == 'Título' ) # True
```

The multi-platform workaround I found was this:

```python
# test.kv
<myButton@Button>:
    text: str(b'T\xc3\xadtulo'.decode())
```

**Comment by kived** [comment]
@VinGarcia This is a different problem. Please open a separate issue.

**Comment by VinGarcia** [comment]
Ok, thank you.
