### ISSUE TITLE
3Drendering example is not working

### ISSUE THREAD

**Issue by cbenhagen** [kivy/kivy#3716]
It only shows a black window. I tested on OSX 10.11.1 and 10.10.5 with kivy 1.8.0 and 1.9.0 app and 1.9.0 and 1.9.1-dev installed via pip.

trace: http://pastebin.com/JxDRMqBp
using pygame does not change anything: http://pastebin.com/uzYjDx6E

**Comment by cbenhagen** [comment]
This might not be a OSX problem after all. I just tried it on a raspberry pi with raspbian jessie with the same result. What bugs me the most is that there is no error message.

trace: http://pastebin.com/M59zeFCH

**Comment by TheVento** [comment]
Sometimes the solution is sooo simple that its hard to find:

Simply when you install Kivy via PIP on MacOS or Debian Jessie, in the examples/3Drendering directory the required file "simple.glsl" is missing... putting it there solves everything! *facepalm*

We just could not see the forrest because of all the trees... :-/

Please double-check and confirm!

**Comment by akshayaurora** [comment]
I just tested this on OS X el capitan and on yosemite,  the example works
without any issues, I installed by simply cloning the repo, installing the
frameworks for sadly, gstreamer and using a virtualenv.

The examples work as expected. I am not using brew though.
