### ISSUE TITLE
app crashes on TextInput().do_cursor_movement('cursor_end') on empty TextInput().text

### ISSUE THREAD

**Issue by Pymancer** [kivy/kivy#3765]
kivy.__version__ = '1.9.0'
OS: Win7 x64 sp1
```python
from kivy.base import runTouchApp
from kivy.lang import Builder
from kivy.uix.textinput import TextInput

class MyTI(TextInput):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        # uncomment next line to avoid crash
#         self.text = 'ok'
        self.move_it()

    def move_it(self):
        # e.g. cursor_home is ok
        self.do_cursor_movement('cursor_home')
        # 'cursor_end' crashes
        self.do_cursor_movement('cursor_end')

if __name__ == '__main__':
    runTouchApp(Builder.load_string("""
BoxLayout:
    orientation: 'vertical'
    size_hint: (None, None)
    size: (400, 100)
    MyTI:
        text: 'test'
    """))
```

**Comment by KeyWeeUsr** [comment]
@Pymancer Although I can reproduce, it doesn't seem like an issue to me. If you put into kv `MyTI` with `text: 'test'`, the `__init__` is executed sooner, because well.. you need an object to place. When you use `self.move_it()` in `__init__` without the TextInput having a text, obviously functions working with lists that handle TextInput's text will crash the app. It's not that `cursor_home` works, because if that would work with indicies, it'd crash too and the only reason why it works is that it puts cursor to the "zero" position, therefore it doesn't have reason to crash.

```
        elif action == 'cursor_home':
            col = 0
            if control:
                row = 0
```

anything else will just throw IndexError or something like that.

Anyway, it still wouldn't work for you in `__init__`, because something (probably `_insert_text` or `._trigger_cursor_reset`, I'm lazy to dig through that code :smile:) *will* change your cursor's position back to the last column (and last row?). I made a patch that won't throw an error(basically won't allow you to do cursor movement), but otherwise it'll work. See the console here:

```
from kivy.base import runTouchApp
from kivy.lang import Builder
from kivy.uix.textinput import TextInput

class MyTI(TextInput):
    def __init__(self, **kwargs):
        super(MyTI, self).__init__(**kwargs)
        self.text = 'test'
        self.move_it()

    def move_it(self):
        self.do_cursor_movement('cursor_left')
        print self.cursor

if __name__ == '__main__':
    runTouchApp(Builder.load_string("""
BoxLayout:
    orientation: 'vertical'
    MyTI:
        id: ti
        on_cursor: print self.cursor
    Button:
        on_release: ti.do_cursor_movement('cursor_left')
    """))
```

**Comment by Pymancer** [comment]
@KeyWeeUsr, couldn't disagree with you, preventing the app from crashing is enough in this case, ta
