### ISSUE TITLE
the constraints for the widget property 'right' in the kivy do not work properly

### ISSUE THREAD

**Issue by hrashk** [kivy/kivy#3774]
Here is a minimum example. When the window comes up, the label is located above the button (see the attached image). When the button is moved, the label position gets corrected. A similar problem occurs for the top property.
![right-overlap](https://cloud.githubusercontent.com/assets/1180859/11225884/ae21812a-8d8d-11e5-9705-a428f864913b.PNG)

```python
from kivy.app import App
from kivy.interactive import InteractiveLauncher
from kivy.lang import Builder

kv = '''
FloatLayout:
    Button:
        id: btn
        text: 'hello world'
        size_hint: None, None
        pos: 100, 100
        on_press: app.move(self)
    Label:
        size_hint: None, None
        size: self.texture_size
        text: 'label'
        # x: btn.x - self.width
        right: btn.x
        y: btn.y
'''


class ScalingApp(App):
    def move(self, btn):
        btn.x += 10

    def build(self):
        return Builder.load_string(kv)


ScalingApp().run()
```

**Comment by pythonic64** [comment]
You can use halign and text_size instead of texture_size:
```python
'''
    Label:
        id: label
        size_hint: None, None
        text_size: self.size
        halign: 'right'
        # size: self.texture_size
        text: 'label'
        # x: btn.x - self.width
        right: btn.x
        y: btn.y
'''
```

**Comment by matham** [comment]
Ok, this is something that has been brought up many times. But it's a very easy mistake to make and not so easy to figure out when you initially encounter it. This is explained at http://kivy.org/docs/api-kivy.uix.widget.html#usage-of-widget-center-widget-right-and-widget-top for a similar scenario.

Basically, the problem is that you read this rule, `right: btn.x` in English. So you read it as: the `right` will be whatever `btn.x` is. But that's not what the rule says. You need to read it like a robot instead! Reading instead like a robot, the rule now says, `right` will be set to `btn.x`, whenever the value of `btn.x` changes.

So what happens is that initially, the button is put at the position `100, 100`. At that time, right is set to `100`. But at that time, the label has no text, so its right is also at `100` since the width is zero. Then, the label size increases to match the texture size, but since `btn.x` has not changed, the label width will increase and overlap with the button.

A hack to get this working is to do `right: btn.x if True else self.right`.
