### ISSUE TITLE
TextInput should inherit from something else besides Widget

### ISSUE THREAD

**Issue by ngoonee** [kivy/kivy#3796]
As things currently stand, extending <Label> with a pre-set font_name and font_size will apply that to all text labels. E.G.
```
<Label>
    font_name: 'my_cool_font.ttf'
    font_size: '32sp'
```

However, TextInput (and I guess CodeInput which inherits from it) does not inherit from Label. This is correct as text input widgets are fundamentally not labels. However this does mean that my_cool_font.ttf is not used in TextInput widgets.

My previous workaround was to just extend <Widget> instead, but this adds font_name and font_size presets to all items including layouts etc. Meaning my BoxLayout has a font_name and font_size attribute.

```
<Widget>
    font_name: 'my_cool_font.ttf'
    font_size: '32sp'
```
This also means that, if my subclass of BoxLayout needs a font_size attribute, it CANNOT be set reliably from __init__. The example below would give me a custom widget with font_size '32sp' rather than the font_size I've explicitly selected.

```
m = myBoxLayout(font_size=15)
```

Currently I just extend both <Label> and <TextInput>, which works, but it may make more sense to have an additional <Text> class which both <Label> and <TextInput> can inherit from and which inherits from <Widget>. In summary:-

```
class Label(Text):
    ... content here...

class TextInput(Text):
    ... content here...

class Text(Widget):
    pass  # no need anything here, user can add font_size/font_name etc if they want
```

This results in no change to current behaviour as far as I can tell.

**Comment by matham** [comment]
You seem to be missing parts of the text. Can you please edit the issue so it's more understandable?

**Comment by ngoonee** [comment]
Sorry, it's probably just the normal way I speak/write, which can be pretty clipped. Edited.

**Comment by matham** [comment]
Actually, since a very recent master commit, doing `m = myBoxLayout(font_size=15)` will actually make font_size be 15. See http://kivy.org/docs/api-kivy.lang.html#order-of-kwargs-and-kv-rule-application.

Regarding your issue, i"m not sure that TextInput and Label share enough attributes and their meaning to allow a shared base class.

A better solution is one using tags. There has been some talk about adding tags to kivy, but so far nothing has been added. Tags would allow changing properties that match, en masse.

Proper theming support is also a better solution for this

As I don't think this will happen, I'll close it for now.

**Comment by ngoonee** [comment]
Thanks, that all makes much more sense.
