### ISSUE TITLE
Can't install on windows 10 with python35

### ISSUE THREAD

**Issue by gantlion** [kivy/kivy#3829]
python -m pip install --upgrade pip wheel setuptools 
python -m pip install docutils pygments pypiwin32 kivy.deps.sdl2 kivy.deps.glew

Fails with: 
    Could not find a version that satisfies the requirement kivy.deps.sdl2 (from versions: )
    No matching distribution found for kivy.deps.sdl2

This happens with both 32 and 64 bit python versions, on both git-bash and the normal command line

**Comment by matham** [comment]
Python 35 is not currently supported on windows. This is a problem with MinGW and as far as I know no builds with mingw exists yet, including numpy etc. See http://stevedower.id.au/blog/building-for-python-3-5/ and this thread: https://mail.python.org/pipermail/python-dev/2015-September/141411.html.

There's nothing we can do other than wait for MinGW to be fixed to support the new python 3.5 arch.

**Comment by gantlion** [comment]
Alright Ill use python34 then. Is there a note somewhere on the website that says python35 is not supported? If not, it could be worth just mentioning it somewhere on the install instructions page

**Comment by matham** [comment]
Yeah, that page was optimistically updated for the 1.9.1 release. Currently we don't have any packages on pypi so you have to use the nightly until the release. But definitely the main page will say we don't support 3.5 once the release is created..

**Comment by IamTheDonnie** [comment]
i'm having the exact same problem with python 3.3 ...  installs docutils, pygments and pypiwin32 just fine.  when it gets to kivy.deps.sdl2 and kivy.deps.gstreamer I get the same response.  Could not find a version that satisfies the requirement.   any help would be appreciated.. thanks in advance.

**Comment by matham** [comment]
We don't have wheels for 3.3. To be honest, gstreamer, sdl2, and glew can be shared among python 3.x versions. I.e. you can install a 3.4 wheel to 3.3. Maybe try renaming the wheel names and try installing with pip or wheel commands to see if it allows you to install them. Otherwise, I'd just copy the files from a 3.4 install to 3.3.

However, for kivy you actually will need to install a 3.3 version wheel. Since we don';t have any you'll need to compile it yourself as described in https://kivy.org/docs/installation/installation-windows.html#use-development-kivy.

**Comment by IamTheDonnie** [comment]
I actually bit the bullet and upgraded to python 3.4   that made everything
100 times smoother.. install was quick and easy.   Thank you for the prompt
reply.  very appreciative of your help.
