### ISSUE TITLE
kivy Keyboard issues on Raspberry : "ctrl" key crashes kivy

### ISSUE THREAD

**Issue by public-hons** [kivy/kivy#4007]
kivy 1.9.1 from the latest KivyPie Version 0.7: 

There seems to be a "ctrl" entry missing in Keyboard.keycodes - whenever i hit the "ctrl" key i get an exception:
 Exception in thread Thread-2:
 Traceback (most recent call last):
   File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
     self.run()
   File "/usr/lib/python2.7/threading.py", line 763, in run
     self.__target(_self.__args, *_self.__kwargs)
   File "/usr/local/lib/python2.7/dist-packages/kivy/input/providers/hidinput.py", line 701, in _thread_run
     process_as_mouse_or_keyboard(*infos)
   File "/usr/local/lib/python2.7/dist-packages/kivy/input/providers/hidinput.py", line 551, in process_as_mouse_or_keyboard
     Keyboard.keycodes[l.lower()],
 KeyError: 'ctrl'

I have a logitech Keyboard with german keyboard-layout. 
Can be tested with kivy-examples/widgets/keyboardlistener.py or any other example that binds to the keyboard.
I can work around this by manually setting 
Window._system_keyboard.keycodes['ctrl'] = 305
in on_start(..), but this seems to be rather ugly.

**Comment by Andrewnetwork** [comment]
Just got this error.

**Comment by KeyWeeUsr** [comment]
@public-hons @Andrewnetwork only on rpi, or does it happen on other platforms with the same keyboard?

**Comment by public-hons** [comment]
only on rpi, have not had it on other platforms yet

**Comment by Andrewnetwork** [comment]
Only on RPI

**Comment by KeyWeeUsr** [comment]
@public-hons is there any difference in the error when you press right or left `ctrl`? If not, I think it may be the provider's fault of not being able to differentiate between those keys (or basically using wrong key in dictionary), because there actually is `ctrl` value but in two separate keys as [`lctrl == 305` and `rctrl == 306`](https://github.com/kivy/kivy/blob/master/kivy/core/window/__init__.py#L63)

**Comment by public-hons** [comment]
no, there is no difference for left and right control key and yes, that seems to be the problem (that is why i added Window._system_keyboard.keycodes['ctrl'] = 305 in the startup routine to prevent this crash)

even if it is the providers fault i think that kivy should not crash on an unknown key. so my humble suggestion would be to add a "ctrl" entry to the keycodes (since we now know that it is used) or to return an "unknown" entry or something if the keycodes can not be resolved. 
just my two cents.

**Comment by KeyWeeUsr** [comment]
I meant that it'd be better to edit the input provider itself, so that the provider would return a correct key(even if it doesn't differentiate) e.g. that line 202 in hidinput.py would have `lctrl` instead of `ctrl`. This way it'd match the Window's dictionary.

Blindly adding keys to Window may cause more harm than correcting the provider. To stop the crashing, I think you need to catch some value in `string_to_keycode` or `keycode_to_string`.

**Comment by public-hons** [comment]
ah ok. yes, that is probably much better..

**Comment by fsinisi90** [comment]
Just got this error too on a Raspberry Pi 3 with Raspbian latest version.

**Comment by davelawr** [comment]
Seen here too, using a vnc connection to dispmanx_vnc

**Comment by Julian-O** [comment]
This appears to have been fixed in 2019.

@public-hons: Could you please confirm if you are still encountering this

**Comment by public-hons** [comment]
Ok this is looong ago, and i have not encountered this since then, 
so i guess this is fixed.
