### ISSUE TITLE
shouldn't App.root be an object property?

### ISSUE THREAD

**Issue by jligeza** [kivy/kivy#4018]
I've been discussing with dessant this issue on irc:
http://pastebin.com/WVD0L0a2

I couldn't easily bind screen_manager to app.root, because App.root isn't an object property.
https://github.com/kivy/kivy/blob/master/kivy/app.py#L487

Shouldn't the `App.root` be an ObjectProperty?

**Comment by tito** [comment]
Making it an ObjectProperty might work, but you'll do more processing that needed, and use rebind approach.

To be clear: if you create your widget before App.root is set, it will just return None. So your code will not bind. Rebind will re-evaluate your code to be able to bind when App.root change. Which is (in my point of view) unecessary.

In your App.build(), instead of returning the widget to be the root widget, just assign it first, then create the widget that require App.root. You'll have less headache, less CPU used, faster application.
