### ISSUE TITLE
Galaxy Tab 10.5 - failure to run apps

### ISSUE THREAD

**Issue by shayo** [kivy/kivy#4033]
Hi,

I'm new to kivy. Installed it on my Android. I'm trying to run one of the example apps, but the launcher doesn't launch the app.
Here is the scenario:
I've installed kivy. The launcher loads up and said to place apps in the /storage/kivy folder.
I placed several example apps under /sdcard/kivy.
They were recognized by the launcher. However, when I pick one (say,  the compass example ), the screen freezes, and several seconds later, the launcher closes.

Is there a log file I can check for run time errors?
How can I debug this further?

**Comment by KeyWeeUsr** [comment]
Logs from kivy are in <code>.kivy</code> folder inside your /sdcard/kivy/<app> folder. Post a log from logcat when you run the launcher with app here.
What is your launcher version? I guess it's the latest one from google play(which is buggy). Anyway, try to change orientation to <code>landscape</code> in <code>android.txt</code> in your app folder, or just run kivy showcase.
If showcase works, the issue is already here, search "portrait".

**Comment by shayo** [comment]
Yes. Modifying to landscape solved the problem.
Thanks.
