### ISSUE TITLE
Pygame text provider does not render text opacity properly

### ISSUE THREAD

**Issue by mixedCase** [kivy/kivy#4043]
Text renders as if opacity is set to 100% regardless of what's set in a Label's color attribute.

SDL2 works just fine.

Tested with master pulled today on Linux.

**Comment by dessant** [comment]
This was broken while fixing color handling for sdl2 because the global Color from style.kv was removed.

I'm not sure what would be our policy here, since pygame was deprecated, and this is not a critical bug, but we're probably open for a fix if someone provides a patch.

One the other hand the pillow text provider should be updated to reflect these color changes.

**Comment by dessant** [comment]
@mixedCase, does the pr work for you?

**Comment by mixedCase** [comment]
I switched all my machines to SDL2 and setting the KIVY_TEXT env to pygame fails with a `Unable to get a Text provider` error.

If you can run the KivyMD kitchen sink, open the menu, go to text fields and are able to see a difference in opacity between the labels "Primary color", "Secondary color" and "Hint color" with pygame provider, then it's working in the same context where I noticed the bug.

**Comment by dessant** [comment]
Yes, I did not intend to set up an env with pygame, I was figuring you might still have one. :yum:
