### ISSUE TITLE
TestInput Bubbles don't work anymore and is bad design, needs redesigning.

### ISSUE THREAD

**Issue by akshayaurora** [kivy/kivy#4174]

**Comment by dessant** [comment]
Could you share an example and describe the issue?

**Comment by dessant** [comment]
Please reopen with a way to reproduce the bug.

**Comment by akshayaurora** [comment]
@dessant as I told you on irc bubbles just don't work anymore on mobiles.

**Comment by dessant** [comment]
@akshayaurora, I've tested with the showcase textinputs on android and bubbles do work there, that's why I asked for a way to reproduce the issue.

**Comment by akshayaurora** [comment]
@dessant the issue is when you use bubbles on a high dpi display, related to other issues highlighted and caused by always_released being set to False

**Comment by dessant** [comment]
Ok, I was testing with a normal dpi phone.

**Comment by kived** [comment]
I agree with @dessant that this issue should have a better description of what doesn't work right and what a better design should be, rather than "No description provided." But I also have issues with the bubble on the Nexus 9, which is only 288 DPI. It doesn't show up at all when selecting text, Select All doesn't work, Paste probably doesn't work.

**Comment by dessant** [comment]
Fixed in https://github.com/kivy/kivy/pull/4844.
