### ISSUE TITLE
unicode text_hint in TextInput

### ISSUE THREAD

**Issue by tshirtman** [kivy/kivy#4201]
using a unicode value for `hint_text` in kv (loaded with load_file) fails, i get encoding issues.

```
TextInput:
    hint_text: u'é'
```

a successful workaround is to use `decode` instead of `u''`

```
TextInput:
   hint_text: 'é'.decode('utf-8')
```

edit, this is not specific to `hint_text`, `text` has the same issue.

**Comment by andong777** [comment]
Hi, @tshirtman 
I don't know if there is a kv language equivalent of `# -*- coding: utf-8 -*-`? I think the u'é' doesn't work because we doesn't specify the encoding of the .kv file.
If I add that line of comment to the head of a python file, using something like u'é' in code works just fine. But if you don't specify the encoding of the file, you will also get encoding/decoding error like:

> UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 157: ordinal not in range(128)

**Comment by tshirtman** [comment]
yes, but everything should be unicode anyway, as we were doing it already for `text` in `Label` (and even `TextInput`, so we shouldn't have to tell kivy that the file is unicode, that should be the default, hopefully it's fixed now :).
