### ISSUE TITLE
Kivy-iOS needs attention >= Android 

### ISSUE THREAD

**Issue by admincoder** [kivy/kivy#4231]
Kivy-iOS is the only toolchain NOT supporting python 3, which is stopping Kivy from being a python 3 complete framework. I am new to Kivy, as well as Github but immediately fell in love with Kivy and the way it organizes it's sister projects with such modularity. 
From what I have seen Kivy has had slow release cycles, which is acceptable but only if the entire project benefits from a major release or rather have shorter release cycles that update bits of the framework at a time.

As a new mobile developer, I am ecstatic to use something like Kivy and take advantage of Python and it's ecosystem for cross platform development. But I noticed that in the mobile space, Android & Pyjnius are given way more attention than iOS & Pyobjus. This is very bad as the majority of the developer community worldwide prefers to release apps for iOS first before Android; better from a business point of view. Whether this is because of a lack of interest in iOS or a lack of devices to test, the issues must be made clearer and the core Kivy developers must ask for specific community help if needed.

Conclusion: @tito, @akshayaurora, @Kovak, @tshirtman, @dessant, @kived, @inclement, @Zen-CODE, and others.
Far more attention should be paid to iOS as a whole: Kivy-iOS [Python 3], Pyobjus, Plyer (iOS) and updated/more Kivy-iOS recipes. If for whatever reason (eg. No interest, No devices, etc.), Kivy core developers have trouble, they should explicitly list the kind of help wanted from the community.

I think it would be a good idea if people pledged their willingness to help.@Allactaga

+1 to help Kivy-iOS

**Comment by admincoder** [comment]
+1 to help Kivy-iOS.

**Comment by dessant** [comment]
@admincoder, if you would like to help out, fixing kivy-ios bugs is certainly welcome.
https://github.com/kivy/kivy-ios/issues

**Comment by admincoder** [comment]
My biggest concern with Kivy-iOS is Python 3.
So, @dessant I respectfully demand to know what is stopping iOS from supporting Python 3, and what if anything can the community do to help. 
Listing out problems and requests of help will further enhance Kivy and it's community😄; we're on the same team 👍

**Comment by admincoder** [comment]
I would appreciate it if you reopened the issue to help drive more attention to iOS. 
It is very important in the mobile development world and by extension to the Python community.

**Comment by dessant** [comment]
> respectfully demand

And I respectfully *ask* you to look at the kivy-ios and pyobjus issue list, those are the main reason for the lack of most features you're missing.

**Comment by admincoder** [comment]
@dessant 
Sorry if I seemed rude, I really don't mean to be. I have been watching Kivy for over a year now, and saw a lot of improvement for Android but not iOS which is great but still frustrating because iOS is a more important platform for a business to succeed in mobile and iOS has a significantly higher return on investment. This is why I could not understand the lack of attention it receives relative to other parts of Kivy.

**Comment by dessant** [comment]
@admincoder, the lack of attention can probably be explained by *your* lack of attention and contributions, no? :)

We all have our priorities, and they are shaped by what we use and the platforms we build for. If you want to use Python 3 on iOS, the fastest way is if you make it happen yourself, unless you have the means to fund the development of the feature.

Otherwise you can respectfully wait (without making demands) until someone else finds the time and motivation to implement the feature you need.

**Comment by tito** [comment]
@admincoder Hi. I completely understand you. Unlike bigger/others projects, projects here are shaped by the personal interest and motivation for each of us in business. As you know, none of us are working full time on it, but we all use Kivy and sisters projects in our respective jobs.

iOS is the most harder platform to work on, and break almost everytime a Xcode is out, or OS, or IOS. Yes there is a lack of interest for us, because it's the most time consuming with the less reward, and none of us actually use it day to day.

I know that, because everytime i have a project to do on iOS, the first thing to do is to fix the issue that came up from release from Apple. We have less power here, and less users interested to fix issues.
The comprehension and technical expertise required for iOS is also higher than Android (Java VS objective-C), and i guess that's also a cause of less bugfix from the community.

That's said, i personally have no time or interested in the short term to work on Python 3 :(
There is a lot to do on Pyobjus, and kivy-ios.

What you ask is normal as a newcomer. We need heros to bring the project to the light and Python 3 ready :) Will you join us?

**Comment by admincoder** [comment]
@dessant, I hear the point you are trying to hammer down. All I wanted is some clarity on the attention and support of iOS. Unlike you @dessant, @tito took a little bit of time to explain the situation with clarity instead of being rude to a newcomer. 

I promise that once I am free in the next two months, I will definitely take up those tasks. And I hope at that stage I will have more support from the core developers.

**Comment by dessant** [comment]
@dessant, I do agree about tito's answer being more nuanced, but I also agree about your comments being designed to incite an emotional response, including the last one, and I happen to have no tolerance for that.

We are looking forward to your contributions.

**Comment by KeyWeeUsr** [comment]
@admincoder Hi, non-core-dev here. What you did/do is that you came into community demanding something where pretty much no one is paid for developing(except bounties I guess) + your original post sends the feeling that you are shooting at every direction without even looking at consequences(that particular tagging of core members). That's childish and I don't even wonder it was closed so quickly.

Python 3 wasn't even on android until recently, so what's the hurry? Only difference I see between kivy-ios and kivy-android is the launcher if I leave py3 out. The pros of developing for android are that you can pretty much run VM on every machine no matter what OS and that is also the problem. I wanted only to try kivy at least for mac if not ios but I ain't going to buy another machine just for playing with stuff(and I think I'm not alone). So you can imagine how the things are going. Android also isn't perfect, but I'm not waving here "hey, do this, do that", though some things would be nice. :)

**Comment by akshayaurora** [comment]
Thread locked. This place is for issues with framework not for discussion on personal opinions. Please use Kivy-users or kiva-dev for that purpose and let's focus on fixing the issues here.

**Comment by kived** [comment]
When users come to our IRC channel asking for help with running Kivy on mobile, it's almost always about Android, not iOS. That's where the demand is. And more people world-wide use Android than iOS. And if iOS really has such a significantly higher return on investment, maybe people making money on iOS apps could donate to Kivy to get Python 3 on iOS. They're developing on the platform where you have to pay for everything, but don't pay for the development tools they use.
