### ISSUE TITLE
Kivy with Python 3 and Twisted 16.1.1 fails

### ISSUE THREAD

**Issue by rdoursenaud** [kivy/kivy#4275]
```
[INFO   ] [Kivy        ] v1.9.2-dev0
[INFO   ] [Python      ] v3.5.1 (default, Mar  3 2016, 09:29:07) 
[GCC 5.3.0]
[INFO   ] [Factory     ] 193 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
 Traceback (most recent call last):
   File "hiqontrol/main.py", line 32, in <module>
     install_twisted_reactor()
   File "/usr/lib/python3.5/site-packages/kivy/support.py", line 175, in install_twisted_reactor
     from twisted.internet import _threadedselect
 ImportError: cannot import name '_threadedselect'
```

There have been some discussions about that on https://stackoverflow.com/questions/33180667/contributing-to-unmaintained-reactor-in-twisted-or-maintain-separate-implementat
But _threadedselect seem to have been removed from Twisted 16 when running Python 3. Python 2 seem to be fine (for now).

**Comment by ngoonee** [comment]
The stackoverflow link is my question. I gave up on using _threadedselect (editing it was trivial, really), but not because the reactor didn't work, rather the protocol I was building round (AMP) wasn't ported yet.

https://twistedmatrix.com/trac/ticket/6833 indicates that that is no longer the case since Dec 2015, and https://twistedmatrix.com/trac/ticket/8205 seems to indicate that _threadedselect is on its way as well. Overall the twisted team has been progressing at a good clip, really.

For a new project starting today (and looking at twisted+kivy with AMP) I would use python3. No idea about other protocols. However my project is already python2 and I can't really justify switching until I have some free weeks to hunt for everything which needs conversion (project deals with strings extensively, so that won't be fun).

**Comment by seanroark** [comment]
I have also ran into this problem. Any workaround available? I am not averse to using asyncio if its possible.

**Comment by dessant** [comment]
The issue should be fixed with the latest development version of Kivy and Twisted.
