### ISSUE TITLE
PDF doc builds fail on travis

### ISSUE THREAD

**Issue by dessant** [kivy/kivy#4338]
The build has been disabled until a fix is found. The issue does not stem from a recent kivy commit, so it's likely a change in one of the dependencies needed for the build.
https://github.com/kivy/kivy/pull/4337
https://travis-ci.org/kivy/kivy/jobs/133713221

**Comment by KeyWeeUsr** [comment]
If you have some list of packages in a file, I may try to look for what has been updated in 28th - 29th May, because that's where it crashed and if I find it, a simple `==<version` could fix the pdf. Depends on how long it'll take to port the docs to RTD i.e. if it makes sense to even try to fix it, or just let it go, hehe.

**Comment by dessant** [comment]
Kivy does compile on their backend now and the docs are generated, but for some reason the api reference is left out both from the html and pdf version, html styling worked for the first builds, but now that is also broken.

https://kivy.readthedocs.io/en/latest/

**Comment by dessant** [comment]
Fixed in https://github.com/kivy/kivy/pull/4566, pdf builds are now managed by RTD.
