### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by zslevi0** [kivy/kivy#4378]
We are trying to use texture.get_region() method for a loading screen. We've added a percent property to our widget, and an animation increases it during the loading time. There's an empty cup and a filled cup, and as the percent property increases we want to 'fill' the cup by cropping more and more graphics on it.
It works like charm, but we have run into an issue; every time we start the animation, it increases memory usage, until we run out of memory, and the kernel kills our application. Not the first time, but after 30-40 tries.
Here's the .kv file part:
`    FloatLayout:
        Image:
                   source: 'resources/Pictures/Screen/Cups/image_load_00_.png'
	    Image:
	    	pos: -6,-31-(((100-self.parent.percent)/100.)*279)/2
	        source: 'resources/Pictures/Screen/Cups/image_load_99_.png'
                texture:self.texture.get_region(0,0,185,(self.parent.percent/100.)*279)`
And the .py part:
    `anim = Animation(percent=100,duration=t)
        anim.bind(on_complete=self.finish)
        anim.start(self)`
When I comment out texture line RAM usage fluctuates during application use but never rises above a critical value and the app works perfectly.

**Comment by bionoid** [comment]
I don't know the specifics of your case, but I've used StencilView to accomplish this exact task with success. Just draw the empty cup (in a canvas Rectangle or otherwise), and place a StencilView with limited height (height: full_image_height * percent_full) and the full cup in a Rectangle in the StencilView canvas.

**Comment by kived** [comment]
You're taking the initial texture, and creating a region of that texture with the original texture as the owner. Then you create another region, with that texture region as the owner. And another region with that region as the owner. None of these will ever be released, because they all have references. You're just creating a long chain of texture regions. The correct way to do something like this would be to keep the original texture and always get regions from that texture instead of from another region.

But the StencilView method is much better anyway. It's far more performant as it leverages the GPU and OpenGL to do all of the work, rather than doing part of work in Python.

**Comment by zslevi0** [comment]
Thank you for your help, didn't know about StencilView, but it works now :)
