### ISSUE TITLE
on_mouse_down (and up) not called when bound to the window directly in build

### ISSUE THREAD

**Issue by CreamyCookie** [kivy/kivy#4387]
However, compared to `on_mouse_down`, the `on_key_down` event is triggered.

This dosen't work:

``` python
from kivy.app import App
from kivy.core.window import Window
from kivy.uix.widget import Widget


class MyWidget(Widget):
    pass


class MouseScrollApp(App):
    def build(self):
        Window.bind(on_key_down=self.on_key_down)
        Window.bind(on_mouse_up=self.on_mouse_down)

        return MyWidget()

    def on_key_down(self, *args):
        print("I work with keys: ", *args)

    def on_mouse_down(self, *args):
        print(*args)


if __name__ == '__main__':
    MouseScrollApp().run()
```

But this does:

``` python
from kivy.app import App
from kivy.core.window import Window
from kivy.uix.widget import Widget
from kivy.clock import Clock


class MyWidget(Widget):
    pass


class MouseScrollApp(App):
    def setup_binds(self, *l):
        Window.bind(on_key_down=self.on_key_down)
        Window.bind(on_mouse_up=self.on_mouse_down)

    def build(self):
        Clock.schedule_once(self.setup_binds)
        return MyWidget()

    def on_key_down(self, *args):
        print("I work with keys: ", *args)

    def on_mouse_down(self, *args):
        print(*args)


if __name__ == '__main__':
MouseScrollApp().run()
```

**Comment by pythonic64** [comment]
Because `MouseMotionEventProvider` binds to `on_mouse_xxx` events and handlers will always accept mouse events (by returning `True`), so in the first case `MouseScrollApp` binds to `on_mouse_up` before `MouseMotionEventProvider` does and because event dispatching order is reversed, provider gets first to handle the event and accepts it which leaves `MouseScrollApp` without that same event. In the second case `MouseScrollApp` gets to handle the event first, but because it does not accept it event gets passed to provider and provider handles it. 

If you add a button in your second case:
```
from kivy.app import App
from kivy.clock import Clock
from kivy.core.window import Window
from kivy.uix.button import Button


class MouseScrollApp(App):

    def setup_binds(self, *l):
        Window.bind(on_key_down=self.on_key_down)
        Window.bind(on_mouse_down=self.on_mouse_down)

    def build(self):
        Clock.schedule_once(self.setup_binds)
        return Button(size_hint=(1, None))

    def on_key_down(self, *args):
        print("I work with keys: ", *args)

    def on_mouse_down(self, *args):
        print(*args)
        return True


if __name__ == '__main__':
    MouseScrollApp().run()
```
and accept event then provider will never get that same event and button will never get `on_touch_down` event and it won't be possible to click on it.

Maybe we can solve this by not accepting events in `MouseMotionEventProvider` and update the documentation so that users can always access events dispatched by `Window`.

**Comment by pythonic64** [comment]
Fixed by https://github.com/kivy/kivy/pull/7492. Now handlers of `on_mouse_xxx` events in `MouseMotionEventProvider` do not accept events (line `return True` is removed).
