### ISSUE TITLE
Allow text to be selectable/copyable

### ISSUE THREAD

**Issue by ryandoherty** [kivy/kivy#4401]
In our application (and I assume many others), having text be selectable/copyable would be a huge benefit to us and our users. 

The benefit of this would be making Kivy apps feel more native to each platform, easier customer support (customers can copy/paste, no more screenshots) and easier development (sometimes I need to copy/paste values displayed in our application).

Understandably the behavior may not be the same for all platforms. For desktop the normal click+drag would work, but for mobile it may be a 'long press' that copies the text to the clipboard or pops up a dialog. I tested out 3 mobile apps on Android, all either copied text immediately on long press or popped up a custom menu which had 'Copy Text' as an option. And on iOS some apps don't even have the ability to select text, but some do with a long press.

**Comment by tshirtman** [comment]
I don't think it should be part of the default Label class, but mixin Label + ButtonBehavior if you want the "mobile" behavior, or using a themed and disabled TextInput if you want the desktop behavior, could be a way to achieve that, you could even make two implementations and decide which to return at runtime, depending on kivy.utils.platform, it could be a useful addition to kivy if you find it works nicely :).

**Comment by ryandoherty** [comment]
I was thinking of it being an attribute that can be set on the Label class, or maybe a new class for text that a developer wants or assumes would need to be selectable. For some elements having selectable text may not be possible or wanted (especially UI like buttons or links, this may really screw things up). 

Using a themed and disabled TextInput seems like an abuse of TextInput and could cause problems if you have lots of text or need some styling or layout that is available via Label. 

For most applications and webpages, the default assumption of users is if something is text, they can select it and copy it. I'm thinking that the same expectations exist for developers, so either making Labels selectable/copyable by default or via an attribute would be the simplest to understand and learn.

**Comment by Kovak** [comment]
Just did a quick check of several google applications on Android, the majority of basic text (equivalent of Kivy's label) does not default to selectable in any form.

This includes:
1. The entire text of an article in Play Newsstand.
2. Elements in gmail that are not the body of an email.
3. Descriptions for Albums, Artists in Play Music

Perhaps a more minimally styled TextInput is the most appropriate solution for application text that wants to be selectable.

**Comment by ryandoherty** [comment]
Can you style text in a TextInput? Text that's in a Label and styled is a high candidate for needing to be selectable and copyable. I really think re-using TextInput isn't the best decision and is being suggested because it's currently (just barely) possible to do so.

Also, "Google doesn't do this" isn't a great argument :P, this may be an actual design decision. I can select/copy text in the Google Calendar app for an event's description. I can also copy text in the Gmail app, GDocs app and Hangouts app. There's definitely places where styled text needs to be selectable and copyable.

**Comment by Kovak** [comment]
My point was that very specific elements of apps are selectable, not the entire thing (say the way a webpage is) and my main point was to push back against the insinuation that copyable text is the default for most text elements of most apps.

The android equivalent of push label get popup that lets you click Copy is already implementable in Kivy. As Tshirtman said -> Label + ButtonBehavior = this type of copyable Label.

Reusing TextInput is being suggested because it contains the majority of the code to actually achieve selection of text, whereas label doesn't and possibly shouldn't. The base Label has to do very little processing making it an excellent, simple widget suitable for compositing with minimal concerns about the "weight" of the individual widgets. In terms of going forward with the Kivy framework, it seems to me the real thing is that TextInput needs more formatting options, not that label needs more TextInput features. 

It really comes down to whether options 1 or 2 are easier:
1. Adding more formatting options to TextInputs algorithm
2. Introducing a Label subclass that adds TextInputs text selection handling.

The other type of touch screen copy and paste where a press or long press copy's the whole text to the buffer is fairly doable now by creating some type of ButtonBehavior + Label combo, however this would indeed be somewhat awkward on a desktop platform.

**Comment by ryandoherty** [comment]
Ah, I thought the Label + ButtonBehavior was an idea, not existing solution. Nice 👍 

I agree, I don't think all text should be selectable by default, but a simple option to make a Label selectable would be easiest for people developing with Kivy. 

I still don't think reusing TextInput is a good idea. Kivy developers will start with Labels for text, and then they will probably at some point want to make it selectable once they try to select text (or their users do). Having to then change their Labels to TextInputs and possibly lose some functionality, along with adding more code to remove the TextInput's default styling, look & feel and behavior is cumbersome.

I don't know about any of the Kivy internals, but I understand from the Kivy core development team's perspective those things are important. But, as a Kivy user, how easy it is to make some text selectable is important. "I've made a Label, I need it to be selectable, how do I do this? Oh, it's a property, set to True, done." is a much easier to understand story than "Oh, I have to change it to a TextInput, now restyle it, change a few properties to False/0, etc.". Please think about how developers will be learning and using Kivy and what makes sense to them. The friction of development is important, and a papercut like having to rewrite portions of one's code to simply make some text selectable is painful.

**Comment by dessant** [comment]
I would also lean towards adding selection to a custom Label class (both desktop and mobile behavior), TextInput would be a bit heavy as a base, while lacking much of the formatting features as you guys said.

`SelectableLabel` would make a nice garden contribution if someone wants to take it up, and with time we may be able to move it to kivy when the api and interactions are figured out properly.
