### ISSUE TITLE
Library `requests` use too many CPU

### ISSUE THREAD

**Issue by dzmitrykrukouski** [kivy/kivy#4438]
When i had library `requests` in my `buildozer.requirements` Android Monitor show that my application used 30% of CPU on the phone(Motorola Moto G2) in standby. But when i delete this library from requirements Android Monitor already show that application use 15% CPU. 
It's very strange, because when i add `requests` in "Hello World" application it started to use on 15% CPU more, than before.

Any idea?

**Comment by KeyWeeUsr** [comment]
What about cpu usage on desktop? Is there any difference? Maybe there's something from your side in memory or some other way in use? Does it do something(in your code), or just sits there?

Is the percentage constant for let's say 5minutes, or it's only for a while? (e.g. `import` might increase it for a little bit, then drop to reasonable percentage).

**Comment by tshirtman** [comment]
Hello
- request is not part of kivy
- it's not part of python-for-android either
- this is a request for help, not a bug report, you should ask a question to the community using mailing lists or IRC, if the discussion find this to be caused by a bug in kivy, please use a bug report with that, but i find this highly unlikely.
