### ISSUE TITLE
Make ``App._install_settings_keys`` and ``App._on_keyboard_settings`` a public API

### ISSUE THREAD

**Issue by rnixx** [kivy/kivy#4452]
What about making `kivy.app.App._install_settings_keys` and `kivy.app.App._on_keyboard_settings` a public API?

https://github.com/kivy/kivy/blob/master/kivy/app.py#L1019 and https://github.com/kivy/kivy/blob/master/kivy/app.py#L1022

I just had the need to customize this behavior, but overriding a private function feels bad.

**Comment by KeyWeeUsr** [comment]
I wonder, what for actually? It's just handling OS stuff for pressing e.g. `| | |`(options button). Most of the keyboard cases you can handle with `on_key_down` and similar stuff. This is almost the same, but I think it's separated because it could be rebound with something else if it was in [`on_key_down`](https://github.com/kivy/kivy/blob/master/kivy/core/window/__init__.py#L152), which wouldn't be desired(and not everyone would like adding additional lines of code, just to make a button work if he'd want to fetch e.g. arrows, because it'd disappear).

Another thing would be using the options key to call your own menu, but for that it's not reasonable to play with privates. Just make your own `App.open_settings`(and probably even `App.detroy_settings`) and let it handle for you. Don't reinvent the wheel if not necessary.

Also, if you just want to purge the default settings panel - [here](https://github.com/kivy/kivy/blob/master/kivy/app.py#L181) or [here](https://github.com/kivy/kivy/blob/master/kivy/app.py#L189)

**Comment by rnixx** [comment]
I've overwritten ``_on_keyboard_settings`` to adopt opening settings on ``F1``. My application is able to password protect the settings panel, which is handles in a function called ``access_settings`` in my case which was already integrated properly but the ``F1`` case. So it was the least impact to my code doing it this way.

Sure it would be possible to implement it in another way, and maybe I'll change my implementation somewhen if it becomes necessary.

Anyway, it won't hurt to make at least ``_on_keyboard_settings`` public.

**Comment by dessant** [comment]
The Settings widget isn't really maintained and seems to need a rewrite, if that happens, we will likely strive to unbundle it rather than adding new settings methods for the App class.
