### ISSUE TITLE
Scrollview's viewport broken by rootwidget being an EffectWidget

### ISSUE THREAD

**Issue by misterdidactic** [kivy/kivy#4454]
![image](https://cloud.githubusercontent.com/assets/16311787/16648838/d29398ac-442d-11e6-90b5-07fe8f70a20e.png)
This is the scrollable inventory with option buttons above, all children of a nested tab layout for inventory. Project source code at: https://github.com/misterdidactic/PnPPipBoy/

This is with no effects even applied to the EffectWidget (the root widget):
![image](https://cloud.githubusercontent.com/assets/16311787/16648714/38a892ba-442d-11e6-8c05-a04463550a53.png)

Same thing happening with effects applied. The entire viewport just isn't hiding the children of the scrollview. The touch area is still working, i.e. I can't press a button that has been drawn outside of the scrollview. Any presses are going through to the widgets drawn underneath.

**Comment by rammie** [comment]
+1 Can confirm that this occurs if the EffectWidget is any ancestor of the ScrollView. In my case the scrollview appears as all black. Any hints about what could cause this, and how one might fix this in kivy or circumvent this?

**Comment by rammie** [comment]
I narrowed this down a bit further. It is related to the StencilView. In my case, any widgets that have an EffectWidget as and ancestor and that are placed between StencilPush/StencilUse and StencilPop instructions, are not being drawn. However, I can touch them at the positions where they would otherwise appear.

**Comment by inclement** [comment]
EffectWidget uses Fbos internally, which can easily lead to stencil problems. I think stencils should work with Fbos now, so maybe they just need the right argument to be passed.

**Comment by matham** [comment]
fbo has a `with_stencilbuffer` parameter. But that has its own problems: https://github.com/kivy-garden/garden.graph/issues/7. These fbo issues are quite pervasive and hasn't been solved yet.

**Comment by rammie** [comment]
The behavior is a bit odd. Adding a ```with_stencilbuffer=True``` to the fbo used by the EffectWidget causes the effect widget to be blank. Adding ```with_depthbuffer=True``` causes the ScrollView to render in a manner consistent with the original poster. That is, the contents of the scrollview are rendered with the desired effect, but the clipping behavior does not work. This makes sense since the effect widget fbo does not have a stencil buffer.

My suspicion is that if I can get the EffectWidget to render properly with a stencilbuffer, and then enable both a stencilbuffer and a depthbuffer enabled, that it would render properly. Unfortunately, I'm not sure how to go about investigating this further and would really appreciate any hints or guidance.

**Comment by rammie** [comment]
I found a solution to this issue by modifying the ScrollView instead. I changed it to inherit directly from Widget, and use a scissor instruction instead of a stencil to get it to clip. This seems like a good idea. It's easy to calculate the scissor rect using widget.to_window. Unfortunately, I can't figure out how to trigger a recalculation of the rect when the position of widget changes due to the position of a parent changing. For instance if a ScatterView is an ancestor of the widget and it is translated. How do I bind something to when the screen position of a widget changes?
