### ISSUE TITLE
Builder.load_file Fails to Locate .kv File

### ISSUE THREAD

**Issue by FluxIX** [kivy/kivy#4458]
I placed my UI code into a `ui` package. When I attempt to load a .kv file which is next to the accompanying Python module it fails to do so (with an error of "OError: [Errno 2] No such file or directory: '{file name}.kv'"). To correct this I need to do `Builder.load_file( "ui/{file name}.kv" )`, so it appears the builder is not following the current directory to allow loading relative to the accompanying Python module.

**Comment by rafalo1333** [comment]
It's not framework error (I thought the same with this error some time ago). The reason for this is that kivy docs do not tell a lot about its kivy.resources module. Try this, @FluxIX :+1: 

```python
import os.path
from kivy.resources import resource_add_path

KV_PATH = os.path.abspath(os.path.join(os.path.dirname(__file__), 'ui'))
'''Path of kv files.

"__file__" is the document where this code is located. I assume it's main.py.
'''

resource_add_path(KV_PATH)

```

You can add any dirs this way to kivy resource system, so you can load the files by simply specyfing their names.

`Builder.load_file('myfile.kv')`
`background_normal: "image.png"`

... and so on.

Happy coding!

@dessant seems resolved.

**Comment by FluxIX** [comment]
I could add modify the resource path to find the UI files.

Why isn't looking for a kv resource relative to the associated Python file standard behavior?

**Comment by rafalo1333** [comment]
It seems your issue is resolved. Next time try to visit the #kivy IRC channel on freenode, so we can help you with programming issues.

Answering your question, resource management as that in Kivy is found in several gui toolkits. While many are allowing the programmer to place the files only in specific dirs, kivy is liberal in this topic. But...

When you are launching the kivy program (or any other python program) all paths hardcoded like 'somedir/somefile.txt' are relative to the script executed.  So that means that depending on the directories structure, your program may or may not work. Kivy resolves this issue: if you will be adding the paths with your custom files using `kivy.resources.resource_add_path`, you can achieve your expected behavior to load files in specific directories.

Secondly, I am not sure if from language point of view `Builder` can see from which script he was called to `load_file`. So your goal may be not possible simply from Python architecture reason.

While working with filesystem, `os.path` is the preferred way to resolve path names. Kivy does it for you most of the time, if you'll be nice to tell it, where the files may be placed :)

Believe me, I was struggling with the same problem for a lot of time. The day when I found `kivy.resources` module was my savior.

Use the wheel, do not reinvent it ;)

Cheers.

**Comment by FluxIX** [comment]
I think my issue with the adding the resource path is it potentially needs to be done in every *.py file associated with a *.kv file.

I'm already looking a patching some issues in `Builder`, so I'll check if it's possible for the *.kv file parsing to be aware of the directory the file came from.
