### ISSUE TITLE
Remove and Re-add of Highest Widget in a Layout leaves the Widget Invisible

### ISSUE THREAD

**Issue by GreyGnome** [kivy/kivy#4497]
I have noticed that adding widgets to a Layout Manager does not seem to work correctly. I have tested with BoxLayout, GridLayout, and FloatLayout. I have tested with 3 widgets, and with 4 widgets. I am using Kivy 1.9.0 with Python 2.7 on Fedora 22.

I start by adding widgets to a Layout- it looks fine. Then I remove a widget- the "first" one, which is list index 3 in the list of children in my FloatLayout example (index 2 with the Grid example). See the attachments.
[app2-float.txt](https://github.com/kivy/kivy/files/388380/app2-float.txt)
[app2-grid.txt](https://github.com/kivy/kivy/files/388383/app2-grid.txt)

When I re-add the widget in a BoxLayout or GridLayout, space is used in but the widget is not displayed. Testing in my "real" app (code not given here) shows that the widget is indeed in place (I can perform actions on it) but it's just not displayed. This problem only seems to happen with the leftmost position.

**Comment by tshirtman** [comment]
Ok, this is not specific to Layouts actually, you can replace FloatLayout with Widget in your first example, and still get the issue, it also has to do with the canvas instruction order, if you change `canvas` to `canvas.before` in either example, then your examples work as intended. So your Button is actually displayed, it's just that your canvas blocks overdraw it. This only happens if you try to use the last possible index position, i.e, there are no other sibling widget drawn before it.

Incidentally, it seem we had a similar issue with canvas.before in the past (#1021).

The issue seems to be in `Widget.add_widget` when widget is insered last, using 0 as index is wrong in this case, trying to come up with a better one.

Fixing this would mean to check

**Comment by tshirtman** [comment]
https://github.com/kivy/kivy/pull/4584 should fix it, tested showcase to see if it doesn't break anything and seems good, but tests welcome.
