### ISSUE TITLE
(1.9.1) Scrollview Touch Item Selection

### ISSUE THREAD

**Issue by Lomelgande** [kivy/kivy#4543]
Buttons, amongst other things, don't register touch properly when inside a scrollview. This makes the Spinner widget completely unusable. I have tested button selection within a scrollview on kivy 1.9.0 and 1.9.1 and the issue isn't present in 1.9.0.

**Comment by Lomelgande** [comment]
After further testing this selection issue occurs in scrollviews regardless of size. Even if the scrollview is not large enough to initiate scrolling it still takes 10+ touches to successfully interact with any of the buttons in the scrollview.

**Comment by KeyWeeUsr** [comment]
The latest stable version of kivy is 1.9.1 and master 1.9.2. 1.9.0 is a little bit old. However, would you please include an example? I don't see this issue on master (put ~50 Spinners into ScrollView).

**Comment by Lomelgande** [comment]
Hey Key, I've tried using master as well. The scrollview issue is resolved in 1.9.2 but another issue is presenting itself. Here is an imgur album that illustrates my issue http://imgur.com/a/CBAt0. All popups in 1.9.2 popup in the side of the screen. This isn't an issue in 1.9.0/1.9.1. Also here is a video illustrating my issues with 1.9.1 https://vid.me/Izo0. The first app is on kivy 1.9.0 as specified by buildozer and the second one is on kivy 1.9.1. The name of the app differentiates between 1.9.0 and 1.9.1 and both are built off the same code. I will try and see if I can get some test code up by the end of the day.

**Comment by KeyWeeUsr** [comment]
Haven't tried on android, but Popup positioning shouldn't be different than on e.g. Windows and there it works for me well, soo a quickfix would be copying `scrollview.py` into old kivy, but I'm not sure if there was something new or not. The opposite thing for `popup.py`(old -> master) most likely won't work, because the file isn't edited very often as you can see [here](https://github.com/kivy/kivy/commits/master/kivy/uix/popup.py)

Still an example would be appreciated, because I think you have may have a bad positioning for the popup - `center`/`center_x` by any chance? Or `pos_hint = {'x': 0.5}` or something like that. Nice layout btw :+1:

**Comment by Lomelgande** [comment]
I'll go ahead and mess around with the py files and see if I can get it to work. I'll try and post some code later. I am just working on this project on the side so it won't be done for a LONG time so I might not deal with it right now. I'm sure Kivy 2.0 will be out long before I finish this.

**Comment by dessant** [comment]
Please open a new issue for the popup bug if you have a way to reproduce it.
