### ISSUE TITLE
Umlauts "öäü" not recognized as keys in CompoundSelection "goto_node()"

### ISSUE THREAD

**Issue by bcm0** [kivy/kivy#4596]
To reproduce: Open the "kivy-examples/widgets/compound_selection.py" example and add `print(str(key))` in the goto_node() method.

Second thing: Where can you define the timeout which resets the "key" string?

**Comment by matham** [comment]
`print(str(key))` is not correct because it's not clear if you're on py2 or and whether the text is bytes/unicode so forcing it to str doesn't seem right. What is the actual issue?

As for the timeout, its controlled by the `text_entry_timeout` property ([just added](https://github.com/kivy/kivy/pull/4599) :fast_forward: ).

**Comment by nokianhunter** [comment]
The issue is I can't find text when it contains umlauts. This is a method from "kivy-examples/widgets/compound_selection.py" I try to use.
```
      def goto_node(self, key, last_node, last_node_idx):
        ''' This function is used to go to the node by typing the number
        of the text of the button.
        '''
        node, idx = super(SelectableGrid, self).goto_node(key, last_node,
                                                          last_node_idx)
        print(str(key))
        if node == last_node:
            children = self.children
            for i in range(len(children)):
                if children[i].text == key:
                    return children[i], i
        return node, idx
```
In addition I want to adapt this method, so the selection is updated with each new keystroke, so I don't have to type in the whole word.

Thanks for merging that timeout thing.

**Comment by matham** [comment]
The problem is probably here: https://github.com/kivy/kivy/blob/master/kivy/uix/behaviors/compoundselection.py#L241. 

The I'm not too familiar with how kivy does other characters, but when I tried to type none-english chars using the [alt-code](http://symbolcodes.tlt.psu.edu/accents/codealt.html#using) it didn't work (kivy returned other unicode chars, not what I expected). I guess the question is how would I know whether the text is e.g. leftarrow etc, or whether it's actual text.

**Comment by matham** [comment]
Ok, https://github.com/kivy/kivy/pull/4600 may fix your issue. I've updated the example to better reflect the capabilities, and I have fixed issues with the code, e.g. when holding down a key continuously as well as allowing all kinds of characters. Hopefully iy fixes your issue.

On windows, kivy should allow the alt-code entry, but it doesn't. And that's an issue with the Window implementation, not with this part of the code.

**Comment by nokianhunter** [comment]
Excellent work! Thank you very much! Character encoding issues are hard to debug.
I tested the updated "compound_selection.py" example with four buttons with these texts: 
"ad" "advertise" "advertisement" "aüsli"
`c = Button(text="ad")
c.bind(on_touch_down=root.do_touch)
root.add_widget(c)
c = Button(text="advertise")
c.bind(on_touch_down=root.do_touch)
root.add_widget(c)
c = Button(text="advertisement")
c.bind(on_touch_down=root.do_touch)
root.add_widget(c)
c = Button(text="aüsli")
c.bind(on_touch_down=root.do_touch)
root.add_widget(c)`
It's cool how you can cycle through the words now. 
If you start typing "ad" and continue "vertise" on each key press during "vertise" the selection switches between "advertise" and "advertisement". 
Trying to select "aüsli" is not possible. However you can cycle through all buttons by pressing by ö, ä or ü. On each press the next button is selected.
