### ISSUE TITLE
When switching source on Image object, getting black screen after about 15 images

### ISSUE THREAD

**Issue by Soprano74** [kivy/kivy#4597]
So I have a simple loop which keeps changing the .source of an Image object. After flipping about 15 images the image goes black. This is not related to the individual image. If this same image is copied to the beginning of the queue, it shows fine. The images are also resize to fix the Raspberry Pi (800x480) and the images are about 200Kb.

Once the GPU_MEM setting is upped, it seems resolved;

/boot/config.txt:
GPU_MEM 192

Currently running with 192, 64 seems to be the default

**Comment by matham** [comment]
You're probably running out of memory because the images are not automatically deleted from memory.

**Comment by Soprano74** [comment]
ok, is there an option to flush the images?

**Comment by FluxIX** [comment]
Instead of flushing the images it would be more useful if there were a backing image cache which was configurable in size and update algorithm.

**Comment by gkanarek** [comment]
how about use an atlas?

**Comment by tshirtman** [comment]
I did a few fixes to the Cache system, and added a way to give a max_size to the Cache, one needs to declare the cache specifically to use it, and also pass a way to compute the size of an item in the cache (because a generic way to compute the memory size of an object in python seems borderline impossible), so if it was used for texture images, i guess a good way would be to pass a function multiplying texture_size[0] to texture_size[1] to pixel format's size, i'm not sure it solves the issue, but should be at least a step in the direction of what @FluxIX suggested.

**Comment by abstractdonut** [comment]
I am experiencing this issue with one of my apps as well. I have many widgets which use a few 100x100 images, but after about 15 or so source changes the images turn black. reload()ing the images fixes the issue, but only if I reload them after they turn black.
