### ISSUE TITLE
[bug] kv lang ignoring __init__.py file in a package

### ISSUE THREAD

**Issue by jligeza** [kivy/kivy#4640]
I have a package `package` which contains a widget `Pretty` in a separate file.
The __init_.py file is supposed to intercept the widget initialization. Sadly, it doesn't work with the kv lang.

main.py:
```
#!/usr/bin/env python3.5
# -*- coding: utf-8 -*-
from kivy.app import App
from kivy.lang import Builder
# from package import Pretty

gui = '''
#:import Pretty package.Pretty

Pretty
'''


class Test(App):

    def build(self):
        return Builder.load_string(gui)
        # return Pretty()


Test().run()
```
package/pretty.py:
```
from kivy.uix.button import Button


class Pretty(Button):

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        print('I am pretty')

```
package/__init_.py:
```
from .pretty import Pretty as _Pretty


class Pretty(_Pretty):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        print('intercepted')
```

The expected behavior: lines ,,I am pretty'' and ,,intercepted'' are displayed in console.
The actual behavior: only ,,I am pretty'' displays in console.

When we uncomment the commented part in `main.py` using normal import + object creation, omitting the kv lang builder, the expected behavior is fulfilled.

I use py3.5 with current kivy nightly builds.

**Comment by matham** [comment]
I believe there should be a warning about this in your log.

**Comment by jligeza** [comment]
@matham There is no warning in the logs.

**Comment by matham** [comment]
Hmm, ok. The basic problem is that you're first registering (automatically) the Pretty class with the lang factory by defining it in pretty.py because of https://github.com/kivy/kivy/blob/master/kivy/uix/widget.py#L283. Then, when you define it again, the factory rejects it because the class name already exists, as seen here: https://github.com/kivy/kivy/blob/master/kivy/factory.py#L67. 

You don't see a warning like I thought you would because by default we warn only if you overwrite a class in kv. I think what you're seeing is a feature, not a bug. Re-using class names is just not supported by factory as it sticks with the first version defined. The best solution is for you to call factory.unregister('Pretty')  before defining Prett in __init__.py.
