### ISSUE TITLE
[Feature request] add multiline comment in KV lang

### ISSUE THREAD

**Issue by K0XX** [kivy/kivy#4650]
I think it would be nice to have the possibility to use multiline comments (with """ as the delimiter) in KV lang too: it's useful for debugging and for adding long comments.
Putting a # on every line it's very frustrating..

Thanx.

**Comment by KeyWeeUsr** [comment]
Feel free to test the PR.

**Comment by tshirtman** [comment]
I do believe it's an editor's problem, commenting a few lines at once should be a few keystroke at most, either the editor is bad, or it's badly configured.

But if there is a real need, and a syntax is found, i guess it's ok.

**Comment by K0XX** [comment]
I know many editors can edit differents lines of code at once, but this appears to be a workaround.
Multiline comment is something that exists in every programming language.. so why not in Kivy?
I'd like to have this feature on notepad too!! :-)

Thanx.

**Comment by inclement** [comment]
Per my comments in the other thread, I basically agree with tshirtman, but don't like the proposed syntax even if people want this feature.

I also think it's important that ''' in Python doesn't delimit a comment but a string - this works as a comment in Python code with almost no repercussions, but for the same reason it can't work as a comment in kv without being much more complicated, as ''' should be usable as normal in Python parts. Even if such a syntax is accepted, I think it has to be something other than the proposed '''# which is quite awkward. Perhaps ### would be best, but I don't really like that either.

As a minor note, pep8 suggests that block comments should just use a # at the beginning of each line, a consistent syntax that also works in kv. I appreciate the reasons people want other features though.

All that said, I don't want to bikeshed about it, I don't really support the change but if others support it and agree on a method then I also guess it's okay.

**Comment by KeyWeeUsr** [comment]
Hehe, I'm not really good with new syntax, no surprise. I like udiboy's more than mine (edited it), but the reqest is rather harmless and if there's going to be more extended launcher in the future, this might help with quick editing. That's being said, I'm kind of "neutral" here. I mean, I'll certainly patch my phone, because I use it while traveling, yet on desktop I don't really care as there's that default editor behavior for commenting out a region and it's even in IDLE, which is default Python's IDE.

On the other hand, kv is rather "styling" language using Python, so relying on PEP8 because it says multiline comments shouldn't be used and still a few lines after it uses them for doctrings isn't very good thing to do. Plus I don't think people will start to write code like old C, where were the big comment blocks, in which people put license, filename, ascii-art and/or other less sane stuff. (I'll haunt them if yes :ghost: )

**Comment by dessant** [comment]
If someone feels very strongly about this, please reopen, but i believe this is a non-issue, most decent editors will comment out multiple lines with a keystroke combination.

**Comment by vmisiko** [comment]
i think its an issues and it should be reopened

**Comment by erm3nda** [comment]
I can't figure out how do you configure Windows notepad or nano to add multiline comment binded to keystroke (im joking of course, you can't). I am not always on the same computer, configuration nor editor. I really miss the multiline comment and doing magics on the keyboard is not really an option.
I readed the comments and I don't understand why there's no multiline comment yet. I saw this issue is old, I looked the docs and I can't found any way to comment a big block that I won't remove from the file that is being edited.

Regards.
