### ISSUE TITLE
Kivy problem on mac osx 

### ISSUE THREAD

**Issue by drogu** [kivy/kivy#4669]
Kivy doesn't work on mac osx 10.12 sierra.I can't open it.Update please

**Comment by manthansharma** [comment]
@drogu 
Follow the steps provided 

> https://kivy.org/docs/installation/installation-osx.html

and if problem continues provide the logs.

**Comment by Zen-CODE** [comment]
@drogu. The instruction provided above work when tested on 10.12. If they do not work for you, please post what you did, where it went wrong and what the message was. Otherwise we can't really help and will close the ticket.

**Comment by MFaisalZaki** [comment]
Hello, 
I receive this error "35 warnings and 4 errors generated.
 error: command 'gcc' failed with exit status 1" when trying to compile Kivy for MacOS Sierra.

**Comment by Zen-CODE** [comment]
@MFaisalZaki. What command did you run that produced the errors? Surely you can copy and paste from the console?

**Comment by MFaisalZaki** [comment]
@Zen-CODE I have cloned the repo and then executed sudo python setup.py install

**Comment by Zen-CODE** [comment]
The post the complete output of the command so we can see what the problems is. But please post it as a new report on the Kivy user group.

https://groups.google.com/forum/#!forum/kivy-users

To create a ticket discussion, you need to prove it is a kivy problem, not something you are doing wrong or skipping. The "There is a problem, what is wrong?" proves only that the reporter has not taken the time to try and understand what the problem is. These type of discussions can be had on the forums, but tickets discussions should be reserved for instances where there is clear proof + evidence  of a kivy failing. 

You mention nothing of where you ran this command, what you did before it, what the output is. You need to provide these things as evidence.
