### ISSUE TITLE
Linux install doc - input group

### ISSUE THREAD

**Issue by mixmastamyk** [kivy/kivy#4682]
Under a recent Ubuntu, I found I needed to add my user to the "input" group to get access to things like the track pad.  A short note to the Linux install doc would be helpful:

```
sudo adduser $USER input  # log out then back in to apply
```

Otherwise you'll see lots of errors such as: `permission denied accessing  /dev/input/eventX…`

**Comment by Zen-CODE** [comment]
@KeyWeeUsr. I once submitted a PR to present a message instead of throw an error, but someone felt that might make it incompatible. I don't think that's legitimate: it's bad practice to rely on errors. 

I will prepare anotherPR that logs these messages instead of throwing an error. I think that makes much more sense as errors are things you cannot predict. This is predictable, and not an error so much as a permissions issue.

**Comment by KeyWeeUsr** [comment]
@Zen-CODE I put the documentation+easy tag here, because the adding user to input seemed like a solution for the permission errors too. Or just a note about that in docs. A beginner won't most likely know what's going on except "permission denied" and I think it could lead to opening Kivy apps with `sudo` because of an error just to make things smooth in the log. ^^

**Comment by Zen-CODE** [comment]
Yes, I am also going to add that to the docs. But even with that in the docs, I think it's wrong for an error to be thrown. It's really not an error, it's a permission issue so should appear as such. It is unnecessary to spit such an alarming to the console and has been the cause of many posts and questions. 

Agreed? Or do you think it should throw and error as it currently does?

**Comment by KeyWeeUsr** [comment]
I'm not really sure if it should be thrown. As I read the questions it doesn't seem to cause problems except for that denied access, which is probably only for fetching devices, therefore catching and printing is the good thing to do, right?

**Comment by Zen-CODE** [comment]
If you look at the PR, you'll see two posts by people alarmed by the message. So was I when I first started using kivy (also being new to linux). And those are just two I could google quickly. There have also been many questions on the forums about it, because it does throw an error and people think something is wrong.

I was actually going to ask you to test and merge it :-) I think it causes too much confusion to see errors spat our directly, as if they are not expected and need attention. They are expected, and I think we should handle them as such....

But yes, will get to the docs (hopefully) tonight.

**Comment by mixmastamyk** [comment]
I didn't like the error either, but I gathered that since it had been ignored for years someone supported it.  Therefore I though docs could help.  But, if you'd like to log it instead, by all means.  The log message might include reference to the "input" group if it needed under other popular distros as well.

**Comment by Zen-CODE** [comment]
@mixmastamyk. @KeyWeeUsr. Absolutely. Will link to the doc changes to this ticket so better wording can be suggested.

Thanks. Respect.
