### ISSUE TITLE
BoxLayout/GridLayout (possibly other layouts using spacing): spacing used for invisible widgets, strange effect

### ISSUE THREAD

**Issue by rafalo1333** [kivy/kivy#4711]
`BoxLayout` and `GridLayout` are calculating the space including `spacing` for widgets that should have been invisible due to size_hint + size properties values.

```python
'''Example Kivy app.'''

from kivy.app import App
from kivy.lang import Builder


KV = '''
BoxLayout:
    orientation: 'vertical'
    spacing: '10dp'

    Button:

    Button:
        size_hint: None, None
        size: 0, 0
    Button:
        size_hint: 0, 0
        size: 0, 0
    Button:
        size_hint: None, None
        size: 0, 0

'''


class ExampleApp(App):

    def build(self):
        return Builder.load_string(KV)


if __name__ == '__main__':
    ExampleApp().run()

```

For `BoxLayout` it may be the line that needs a change:
https://github.com/kivy/kivy/blob/master/kivy/uix/boxlayout.py#L160
`minimum_size_none = padding_x + spacing * (len_children - 1)`

I will try to dive deeper into this. Maybe I will be able to fix BL, not sure about GridLayout as its logic with rows/cols is more complicated.

I think its important to fix this behavior. Kivy binding is a very nice feature, and one (including myself) may want to hide some widgets when some property changes without manipulating the widget tree directly:

```python
kv = '''
BoxLayout:
    spacing: '20dp'
    prop: 3

    Button:

    Button:
        size_hint: (0, 0) if root.prop < 4 else (1, 1)

'''
```

@matham maybe you'll know more about the issue, I remember you have updated the layouts ~month ago.

The ss documenting the issue when there is 6 buttons inside a GridLayout, 4 of them hidden and spacing=10dp:

![zrzut ekranu z 2016-11-06 19-38-04](https://cloud.githubusercontent.com/assets/7304986/20040472/aed2ca10-a458-11e6-8818-cb658ba64de7.png)

**Comment by KeyWeeUsr** [comment]
Although it'd be really nice to have a behavior that could hide widgets, there isn't any of that now except playing with sizes. However, the widget is still placed there on the exact position just with size `0`. Therefore it's not a strange behavior, rather highly expected. Even the dashed lines showed you that the widgets are still there.

As more useful type of hiding seems (at least to me) cutting the widget out and referencing the object directly somewhere (so that it's not gc-ed) e.g. `app.hidden_widgets.append(<child>); <parent>.remove_widget(<child>)`. It's not flexible though and you need to handle pasting it back, so it's less user-friendly than playing with sizes.

Try to find the thing that adds spacing and put there some check for size e.g. `if <child>.width or <child>.height or ...: do_spacing`, it could work.

**Comment by rafalo1333** [comment]
I think I have the fix for BoxLayout almost ready. Working on it.

**Comment by dessant** [comment]
I do think the widget should be taken into account for spacing when it is part of the layout, even if the widget size is `(0, 0)`.

@rafalo1333, please reopen if you have a compelling reason to change this behavior, with some use cases attached.
