### ISSUE TITLE
Please flag a new release

### ISSUE THREAD

**Issue by NicoHood** [kivy/kivy#4720]
Hi,
I am using kivy 1.9.1 on ArchLinux, but I have problems running this on the Raspberry pi with ALARM. The current master fixes a lot of problems and runns perfectly with the rpi. The last release is quite some time ago and a lot of fixes were made. It would be nice if you could flag a new release if possible. Thanks.

**Comment by Zen-CODE** [comment]
What do you mean by 'flag a new release'? All new releases are announced on the forums and the website updated.

**Comment by NicoHood** [comment]
I mean its ready to tag a new release, as the last one is quite old.

**Comment by guizhenwei** [comment]
It would be nice to have a release schedule for Kivy. 

Like what Python does: https://www.python.org/dev/peps/pep-0494/

> The last release is quite some time ago and a lot of fixes were made.

I have the same feel. 
It'd be nice to have a new release if the current master is stable enough.

**Comment by KeyWeeUsr** [comment]
++ for the release schedule, yet I don't see it happening (at least not the same as Python has), because of few things:

1. Kivy isn't even slightly as big as Python's organisation :slightly_frowning_face: 
2. Bugs are fixed when there appears someone who knows how to fix it or if some of the devs work with that part of core, otherwise a bug just waits for someone
3. Each release requires creating a changelog, testing and deploying

Although there _is_ Travis CI for testing, that's not enough. There are issues assigned as "milestones", so those need to be fixed most likely because they are important for the next release. For changelog someone has to sit down and check the stuff that has happened since the last release, the same applies for testing (I guess especially for the milestone issues) and then someone has to create releases:

* source, wheels, ppa, VM, and more

and ensure that compiling and packaging with _these_ releases work on supported platforms. That takes a lot of time. Working with Kivy isn't a paid job, most of the people who contribute have a job (or more) too. Making a release for let's say at least 5000 people (looking only at the GitHub stargazers) means taking the responsibility that the stable won't just blow up when you put it e.g. in production. So it's not as easy as "please flag". 😋 

Also it's good to look at the past release dates, those seems to be pretty fixed to a "once a year", so I guess a new one could be here by 2017. Just a note - you can always backport some stuff, or just use _master_ branch. What you can do to make such process quicker is fixing stuff and creating unittests for important issues in Kivy.

**Comment by Zen-CODE** [comment]
@NicoHood. I hear you. but I think the forums are a better place for these kinds of discussions and requests. Tickets should be about requested features and/or actionable issues. 

 https://groups.google.com/forum/#!topic/kivy-dev/DWvbd4XKzhc

As KeeWeeUsr points out, flagging a release is a long and complicated process. Plus there are very few people with enough skill and knowledge to do it. I'm going to close the ticket, not because it's not important and we aren't listening, but because it's does not really seem like a ticket issue? Feel free to re-open if you disagree :-)

**Comment by NicoHood** [comment]
Thanks. I was just kindly asking, I expected that. But sometimes it happens that people just forget new releases ;)

> Feel free to re-open if you disagree :-)

You cannot do that if the owner (you) closes the issue. But nevermind ;)

**Comment by tshirtman** [comment]
It's not an "issue" per see, but i agree, we need to put a new release out asap.

**Comment by Zen-CODE** [comment]
@NicoHood. Thanks for understanding.

ps. Did not know you cannot re-open it. My bad. Okay, feel free to post again if you want it re-opened. :-)
