### ISSUE TITLE
Builder.load_string: text markup parsing error

### ISSUE THREAD

**Issue by hottwaj** [kivy/kivy#4757]
The following kv lang can be parsed in a .kv file, but causes Builder.load_string() to crash.  

```
<TestLabel>:
    text: '\n[size=13sp]meh[/size]'
```

The issue seems to be the preceding "\n" in the string, as removing that makes Builder.load_string happy.

Cheers

**Comment by KeyWeeUsr** [comment]
Kv lang parser handles the `.kv` file as plaintext/string, therefore to get `\n` as a value for `text` property you'll need to escape it with another backslash -> `\\n`, otherwise it'll be handled as this:

    <TestLabel>:
        text: '
    [size=13sp]meh[/size]'

and as the parser goes line-by-line, it'll crash, because it expects some value to assign to `text` property, yet it gets something it doesn't expect. I think it's even somewhere in the documentation.

**Comment by hottwaj** [comment]
Ah I see - silly mistake.  Thanks
