### ISSUE TITLE
Workflow glitches with kivybot

### ISSUE THREAD

**Issue by rnixx** [kivy/kivy#4835]
Since the bot is going to close stale issues automatically it would be good if repository settings get changed that issues can be reopened by creators/contributors. Not sure whether this is possible though.

In the current situation the bot closes something, and the author or a contributor needs to ask organization members to take action. That's no pretty work flow.

**Comment by dessant** [comment]
Unfortunately there is no such setting on github. The bot closes issues when there is no new post made after applying the `awaiting-reply` label.

In your case the label was applied because the linked simpler approach received no response, nor the subsequent questions.
https://github.com/kivy/kivy/pull/3900

**Comment by rnixx** [comment]
@dessant 

I get lots of mails from github and in this case I've simply overlooked that one.

What about defining a core team in kivy organization and a contriburors team with restricted access?

**Comment by rnixx** [comment]
It's also more convenient to track development as organization member with access to the organization dashboard.

If club of visible organization members to the public should stay exclusive, contributor group members can be set private...

**Comment by dessant** [comment]
@rnixx, you've been invited to the Contributor team, this will give you write access to the kivy repository.

**Comment by rnixx** [comment]
Awesome! Thanks!
