### ISSUE TITLE
A way to set the VKeyboard font size could be added

### ISSUE THREAD

**Issue by lulingar** [kivy/kivy#4838]
I'm not sure how to go about this small but probably useful change. Currently, no clean way seems to exist for setting the font size of the keys in a VKeyboard. Indeed, the `draw_keys` method of the `VKeyboard` class has the following code:

    w, h = self.size
    # ...
    font_size = int(w) / 46

But the rendered keyboard is not pleasing to the eye as rendered on half of the screen of a 7'' touchscreen running on a Raspberry Pi. I changed the denominator from 46 to 32 and the keys look much better. So my question is, how could this customization be cleaner?

**Comment by KeyWeeUsr** [comment]
Instead of the raw `46` value make a `NumericProperty` e.g. in `VKeyboard` and put it in that place, which will expose the more useful option to the users. Of course note, that if you are going to make a pull request, each exposed property has to be documented (docstring, version tags, what class it actually is, etc). Examples how it should look you can find all over the repository. 🐰

**Comment by lulingar** [comment]
Right, but would people be happy to tweak an abstract parameter such as that denominator? Maybe, if it has some sort of concept behind it. My question would be, how was that value 46 computed/determined?

**Comment by KeyWeeUsr** [comment]
That's like a super-old line. I put `len()` on a lot of stuff there or just printed stuff but found nothing like `46` value. That guy might even put there `42`, that would be a nice pun for this mystery.

However, I think [the intention](https://github.com/kivy/kivy/commit/576a4ba09b97fd22bbc4ea0bae1073e03ddd9dfa#diff-41a5e58e29320aba7dacc7be3b6cb51dR463) was to have a `font_size` equal on android to something similar as it'd be by default on desktop (`==15`, `kivy.metrics` hadn't been around for about a year judging from the git history). That line needs a fix, most likely with the width cut off completely as it brings up only confusion (and metrics work quite well even without messing up with sizes).

You might as well just remove the line and expose the property to the main class (`VKeyboard`), so that any user can customize that if really necessary.
