### ISSUE TITLE
UserWarning: Normalizing '1.9.2-dev0' to '1.9.2.dev0'

### ISSUE THREAD

**Issue by dessant** [kivy/kivy#4861]
https://www.python.org/dev/peps/pep-0440/#development-release-separators

We could switch to the normalized form at the next version bump.

**Comment by KeyWeeUsr** [comment]
This is kind of hard, because you need to check a lot of things:

* appveyor build → it creates its own name we change before pushing to Drive
* pip install <file> (both normalized and with date & hash)
* kivy version [parse](https://github.com/kivy/kivy/blob/master/kivy/__init__.py#L89)
* consistency between all these three things ↑

Which means that if you edit parsing of the version you probably break every version before `1.10`. If you break file installing, there will be again that renaming thing as it was in the docs + if you break the build everything goes to hell anyway even if there is correct pep styling.

What the pep doesn't say is that you can have only a _single_ separator, therefore this:

    Kivy-X.Y.Z_dev_hash_date-cpAB-cpABm-winARCH.whl

won't work probably already somewhere in the build. You can check the previous appveyor logs where I was changing the names, I think I printed the version somewhere in the beginning of the log.

What could work would be probably this:

    X.Y.Z_devhashdate

but still you need to keep an eye at how the final file will look like, otherwise it won't install, because of pip.

**Comment by matham** [comment]
Right, the real fix, which I mentioned before, is to not have any of that stuff in the wheel filename. Instead we use a version file that is generated on a build and imported in init. Then the name is free to be normal. That's how numpy does it (https://github.com/numpy/numpy/blob/master/setup.py) ans uses it like https://github.com/numpy/numpy/blob/master/numpy/__init__.py#L133. I never got around to that though.

Then, we can add the date-revision to the filename like before but not actually change the version. That's more sane in my opinion :D

**Comment by KeyWeeUsr** [comment]
What about updating? Pip uses `packaging` version parsing:

    from packaging.version import parse
    parse('1.9.2-dev0.24012017.e4d8cb9c') < parse('1.9.2-dev0.25012017.a9d5d756')
    # True
    parse('1.9.2-dev0+e4d8cb9c') < parse('1.9.2-dev0+a9d5d756')
    # False

That first statement is true only because of the date and `.` symbol that separates the version into something like this: `X.Y.Z.d.h` and because XYZ are the same, it compares the next highest thing, which is the date. If I cut it out, updating will break.
