### ISSUE TITLE
Window hangs when "q" is pressed to shut the camera window down.

### ISSUE THREAD

**Issue by yaki29** [kivy/kivy#4904]
When I press the "hello" button it opens the Camera window but when I press "q" to shut it down. The window hangs and I have to "Force Quit".
Here is the code: [https://gist.github.com/yaki29/abe76c7adf9a2cd7971f177b93045921](https://gist.github.com/yaki29/abe76c7adf9a2cd7971f177b93045921)

And also is there a way with which I can use OpenCV functions and methods to do something with kivy.uix.camera ... I have to use VideoCapture() method of OpenCV for that.

**Comment by FeralBytes** [comment]
@yaki29 try pressing "esc" key. I am almost certain this is not a Kivy bug. Can you please tell me how Kivy is to blame for your while loop being stuck looping forever because of True.
```
if cv2.waitKey(1) & 0xFF == ord('q'):
    break
```
In fact to prove me wrong; eliminate all references to OpenCV and keep the same exact Kivy code structure then press "Q" and report back what happens. I believe the application will still be hung.
Note: I am not trying to be harsh; but I took an honest look at your code and it appears to me that you have a logic error, that is unrelated to Kivy. I apologize in advance if this comment seems harsh in any way.

**Comment by yaki29** [comment]
@FeralBytes I knew what I was asking. Opencv "imshow" method opens a different camera window which I have set that it would be closed when "q" would be pressed. It works fine when used and run separately but when I try to make it work with kivy it's window freezes which created a problem as application was not proceeding further. But I have found a [solution](http://stackoverflow.com/questions/6116564/destroywindow-does-not-close-window-on-mac-using-python-and-opencv) to this problem. But still I don't know why it happens. It would be very kind if you tell me reason for this or suggest me some better method.
There is no way it could be considered harsh, we are all contributors here and try to help each other.

**Comment by FeralBytes** [comment]
@yaki29 OK so in essence it is not a programming error on your part. But it is definitely a bug in OpenCV as stated here: http://stackoverflow.com/questions/6116564/destroywindow-does-not-close-window-on-mac-using-python-and-opencv 
I am glad that you found a workaround solution. But I would recommend that you file a bug against OpenCV not Kivy.

@dessant I recommend closing this issue as it is a bug with OpenCV.

**Comment by Julian-O** [comment]
Not a Kivy bug. Closing.
