### ISSUE TITLE
Vispy

### ISSUE THREAD

**Issue by jimanvlad** [kivy/kivy#4910]
Hi,

Is there any way to use [VisPy ](http://vispy.org/index.html)with a Kivy backend?

**Comment by inclement** [comment]
I'm not aware of anyone having written the code for it, but I'm fairly sure it should be possible if anyone wants to try. I had a look at it once but never spent enough time to get very far. I think I was going the route of trying a Kivy window backend for Vispy, but that's not the only possibility.

**Comment by jimanvlad** [comment]
Do you have any code from the time when you were trying to use kivy's backend? Alternatively, would you know of any other way to have interactive/real-time graphs built in? Matplotlib is pretty terrible and kivy doesn't yet support web views for python3 to try and go the Bokeh route (CEFpython doesn't support python3).

**Comment by inclement** [comment]
I don't think I had any useful code, even if I still have the branch
somewhere.

I think the main direction of what I was trying was to add a Vispy
window provider. Vispy's system for choosing this provider is fairly
clear in their source code, so it shouldn't be too hard to slot this in.
As I remember, the window code was supposed to set up the window then
run Vispy's eventloop passing in the window events. I was trying to use
Kivy's Clock for this, so that Kivy could pass Vispy the necessary
events, but then Vispy could run within an existing Kivy window.

I'm afraid I don't know of a better solution for fancy dynamic plots.
