### ISSUE TITLE
Consider changing default theme to material design

### ISSUE THREAD

**Issue by Leviathanone** [kivy/kivy#4958]
I'm sorry in advance if this is the wrong place to post this but i would like to make a suggestion:

It would be a good idea for kivy to change its default theme to material design. It is well documented, clean, easy to use, mobile oriented and looks native on android platforms and a growing number of sites. Its usability has also been tested by the millions of users who use android everyday so the design scheme is solid and trustworthy. I know the kivy developers are planning to make kivy themable but i think that material design would be a great intermediary step until that is achieved, and even as the default theme, after the theming capabilities are implemented. In terms of implementation, the developer of kivymd has successfully created widgets that follow material design and if both groups could collaborate, it would be even better. One of the major obstacles kivy, has is its non native appearance, which looks out of place on all platforms (along with the fact that not many developers know about it). By using a clean functional design that is native on one of the most widely used platforms, I think kivy will become the go to gui toolkit for cross platform python development

**Comment by KeyWeeUsr** [comment]
> native on one of the most widely used platforms

Exactly because of that I doubt material design will be ever adopted by Kivy as _the_ theme. One platform. Not two or more. Argument such as this converges to a "they use it, you have to too!". Material design might be even undesirable on iOS and OSX especially if you find at least a bunch of users who dislikes it.

The same thing was (together with the app's controversial name) recently an issue with the Apple's [app](https://play.google.com/store/apps/details?id=com.apple.movetoios) on Google Play, which hasn't seen Material even from a distance, although Google [apps](https://itunes.apple.com/de/app/youtube-videos-clips-musik/id544007664) at least _try_ to fit into the design patterns of iOS with its apps. The reaction on the Apple application was quite furious :)

Kivy is well themable even now. Place your images to some folder, create atlas from them and just join the pictures. It's not that hard. As an alternative you can replace the images directly with e.g. `background_normal` and similar variables.

Unless there's some intention to even move that direction (none that I know about) from other core devs, I'm closing the issue.

**Comment by Leviathanone** [comment]
> Argument such as this converges to a "they use it, you have to too!"

1. I'm not asking that we switch to material design because its popular, im asking we switch to is because, its functional, well designed, clearly documented and time tested. It just seems smart to use a design that looks decent rather than an archaic theme from a no longer existent os that only looks native (and barely so) on android 4 and younger

> Kivy is well themable even now. Place your images to some folder, create atlas from them and just join the pictures. It's not that hard.

2. Yes kivy is themable, but i was suggesting this to be the _default_ theme so that developers who want to use this wouldnt have to reinvent the wheel.

> The reaction on the Apple application was quite furious

3. Yes there will be controversy but in the end, kivy was designed with mobile computing in mind, and the major mobile os right now is android

> Unless there's some intention to even move that direction (none that I know about) from other core devs, I'm closing the issue.

4. You closed the issue before the other core devs even _had_ a chance to see it, much less discuss moving in that direction. If you just shut down ideas and close them left and right, how will the core devs ever know?

**Comment by dessant** [comment]
> how will the core devs ever know?

Notifications.

**Comment by Leviathanone** [comment]
But they didnt get to discuss this did they?  : )

**Comment by dessant** [comment]
@Leviathanone, they did extensively discuss theming in the past, your proposal is just an aspect of it.

Kivy is gravitating towards offering behaviors, without dictating graphical representations. A theming solution is needed to realize that idea, mainly by extending kv to support declaring animations and some other things, or at least making it easier to separate the theme and its behaviors from the rest of the widget logic, and making the theme swappable.

When these are implemented, third-party developers will be able to offer alternative themes, including one for material design, and that will likely happen outside of the main kivy repo.

**Comment by KeyWeeUsr** [comment]
> its functional, well designed, clearly documented and time tested...

...and adopted only by a single platform and **not even that**, it's adopted by Google. Android isn't just Google and its Material design. There's (or was, still probably not decided) Cyanogen and many other alternatives or branches of Android and not every one of them adopted such design.

> reinvent the wheel

KivyMD is a _package_, you only have to import it, plus it has its own set of widgets. Regarding the images, you can replace some or each of them in atlas. Or just use variables as mentioned before. No one forbids you designing your app.

> the major mobile os right now is android

I wouldn't stab into the hornet's nest if I were you. And I'm an Android guy...

> You closed the issue ... how will the core devs ever know?

Every core-dev and contributor has an option to open/close tickets on GitHub. If it's closed, it doesn't mean it won't be reopened (and the other way around) and as dessant said, we get notified from GitHub, or we see it at `freenode#kivy-dev` as there's a bot reporting such things like PRs, issues, etc in real-time and most of us don't even leave the channel, so there's even history. And [BotBot](https://botbot.me/freenode/kivy-dev/) history.

> In any case its still better to have a theme that _some_ hates rather than a theme that _most_ hate.

Well then, **_I_** don't _hate_ Material design, I like it on Android, because I have `Super AMOLED`, though a well made UI/UX is still a way more eye pleasant than Material especially on 720p+ 5.5" displays. Most of the common → not high-end, not custom builds, the cheap machines that are just consumable goods ← desktops+laptops are happy if they have an LCD that's usable by graphic designers.

**_I_** just find it highly inappropriate for desktop platforms mainly because it happens to do buttons with text only (basically html `<a>` tag), input field is just a **line** and many other lovely things not really usable on desktops if you want to make an application that's readable and not just pretty from a distance of 3m.

**_I_** find [Flat design](https://en.wikipedia.org/wiki/Flat_design) where even Material belongs to useful only for web and really simple applications, but for some reason those happened:

* [Metro](https://en.wikipedia.org/wiki/Metro_(design_language)#After_Windows_8) in Windows - and the lovely finger they got for removing start menu with that change, which they got back just to satisfy people,

* iOS slowly getting to OSX and [flattening](https://developer.apple.com/library/content/documentation/UserExperience/Conceptual/OSXHIGuidelines/index.html) everything - which non-Apple people used to hate just because it was, without any reason even before the flattening. However, porting such things like the app dock was apparently good enough for them. ¯\\_(ツ)_/¯

Related to making a cross-platform usable theme, there's [Java FX](http://www.oracle.com/technetwork/java/javafx/overview/javafx-2-datasheet-496523.pdf) which a lot of people just "love" because it happened to try looking like some extended WinXP or a Winamp theme with designing screw ups.

Therefore if there was a new theme considered, it would be most likely something that's usable on all supported platforms and at the same time readable. If there is something like that, feel free to suggest taking a look at it.

And personally, I'd like you to consider not creating [confusing issues](https://gitlab.com/kivymd/KivyMD/issues/72) in the future as [3 people](https://botbot.me/freenode/kivy/2017-01-27/?msg=80014642&page=1) do not speak for the whole community, especially not at 3-5am European time, which happens to be _the_ time for a lot of us, not only devs. Instead, make a poll or something before such actions and make issues then.

It'll definitely give more objective results even for us to know which direction would be more comfortable to move our asses towards as we aren't intentionally going against our community, although it currently might seem like that to you. :)

**Comment by FeralBytes** [comment]
@Leviathanone 
Just my 2 cents, I am not a dev. But I do pay attention to Kivy and I see all issues thanks to Github. 
I think so long as using kivymd is as simple as pip install kivymd and import kivymd, then there will be no need to make it the default theme. Now why you ask; because again in my opinion; Kivy has so many other issues 478 at this time was over 500 just a month ago; and that is just kivy not counting buildozer, pyler, pythonforandroid, and the various other sub projects of Kivy. 
Given all of those issues I personally feel that we can get to this later. I hope that you will take my criticism of your idea as less critical in that I think Material Design is nice and would be a good fit; but that there are simply so many other pressing issues.

**Comment by Leviathanone** [comment]
Thank you @FeralBytes. I appreciate your opinion.

When i was talking on IRC I suggested that I was willing to work on doing this, and before i could ask the KivyMD developer if he wanted to help me, I had to get an okay from you guys. I know there are more pressing issues but i am willing to work on this and i posted an issue on KivyMD's gitlab to see if he would like to help. So far i havent got a response though

**Comment by dessant** [comment]
@Leviathanone, it would be nice if someone could work on theming, here is a previous discussion on the topic: https://github.com/kivy/kivy/issues/691.

**Comment by inclement** [comment]
I think an improved flat default theme would be a nice way forward for Kivy, and I do think that the current default is not great. I think targeting full material design might cause more problems than it solves though, especially compared to improving Kivy's general themeability - I'm no UI expert, but I'd be concerned that trying to mimic a specific platform too closely actually causes more problems than it solves, as it makes all the ways things don't *quite* work the same very obvious, as well as making things fit progressively less well on other platforms. Of course, proper theme support would resolve this by letting things be switched out easily on different platforms.

KivyMD seems to make nice use of behaviours for things like the ripple effect. I personally wouldn't be terribly against including this kind of thing in Kivy core, in principle, but actually the current status seems quite healthy to me as well - KivyMD is an easy project to install and use, which is seems like a nice sign for the Kivy ecosystem.

It's likely that there would be strong resistance to outright changing Kivy's default theme significantly, especially if involving the material design animation flourishes etc. as well as just the basic look and feel - we've always tended to be very conservative about breaking changes. We've discussed this before as a major thing to do as part of a Kivy 2.0 release, alongside general theme support.

I wonder if t the best ratio of appearance improvement to effort might come from changing the default theme to apply colours only through Color instructions rather than coloured textures. That would immediately make it easy to change colours in a way that is currently annoying, because you have to start messing with images just to get the output shade you want.

**Comment by FeralBytes** [comment]
Can I suggest then that we re-open this with the condition being that the issue be assigned to @Leviathanone ?
He can outline his plans here in the bug, and receive constructive criticism from all and guidance from the Kivy Devs. So long as it is not a core Dev issue then it should not drain resources much more than is already the state of Kivy; since regular PR review is just part of the work flow.
@Leviathanone as an individual that has had several commits accepted into Kivy, I would like to give you the key to my success. All of my commits are very small a matter of lines; but in general they are improvements that work to wards my larger goals.

In this case though it will also be tough because this is a wholesale concept. So for that I would recommend you create a branch of Kivy that follows master and includes your improvements. Then we will attempt to piece meal as many of the commits into main before we have to make the big wholesale decision to change the underlying theme. 
Am I making sense here? Basically make a plan get, feedback, get buy in, figure out what small commits and changes could be done in advance of the bulwark and do them, get them accepted into master, then work on the remainder.

**Comment by Leviathanone** [comment]
Yeah that's exactly what i wanted to do! I just needed permission to do the research and make the commits.

Ill start by making a fork

**Comment by inclement** [comment]
@Leviathanone You're welcome to experiment with this, but please do be aware that we're unlikely to consider merging such a change. This is something that we've discussed a lot in the past with many different points of view, and with the conclusion that it has not seemed like a good option, for reasons including those expressed by others in the previous posts.

**Comment by Leviathanone** [comment]
Okay, never mind, I'm done. You guys are zig zagging on the issue on whether i should go for it or not so Ill just let the kivymd guys do what they do and use that instead for all the apps i plan to make, at least until kivy gets a decent theme, as for the main kivy project itself, well good luck and all the best. See ya

**Comment by dessant** [comment]
@Leviathanone, you may have missed my message which linked to https://github.com/kivy/kivy/issues/691. We want proper theme management, until that feature is not present in kivy, no resources will be spent on creating new widgets or retheming them, because it is wasted time for everyone involved.

We do welcome your work, and I agree with @FeralBytes about making plans, a proposal for theme management, and presenting it on #691.
