### ISSUE TITLE
Installing kivy through pip on Python 3.6

### ISSUE THREAD

**Issue by jimanvlad** [kivy/kivy#4969]
Hi,

There doesn't seem to be any wheel files for kivy.deps.sdl2 for python 3.6, so when trying to install kivy through pip, I get the following error: "No matching distribution found for kivy.deps.sdl2".

Would anyone be able to compile these wheels?

Vlad

**Comment by KeyWeeUsr** [comment]
Until there's Python 3.6 available on Appveyor (that's the thing that produces the deps and wheels for Windows), there will be _no_ distributions for Python 3.6 on Windows. Python 3.5 is quite new now for the community and a lot of stuff (p4a, iOS definitely, maybe even OSX) doesn't really support it. We could install Python 3.6 manually on Appveyor, but that would only complicate things (and I hope they'll include it, so that only adding a new matrix would do that).

You can however go for a (not supported) workaround if there wasn't a change in the main Python compiler (Visual Studio version) and rename both deps(sdl2, glew) and Kivy wheels from basically `*cp35*` to `*cp36*` (same for `cpXYm`). Then pip will accept the wheels, however if there were big changes in Python, then:

* Kivy most likely won't support it
* it may break things

**Comment by jimanvlad** [comment]
Excellent suggestion, I will try it.

**Comment by matham** [comment]
Actually, 3.6 support should be up soon. Dependency wheels are almost done and then for the actualy kivy wheels.

**Comment by matham** [comment]
Should be available now on pip. Kivy nightly wheels are also available on drive, and the direct links on the site will also work when the website is next synced with drive tonight.

**Comment by matham** [comment]
However, I did not actually test the wheels, so...

**Comment by jimanvlad** [comment]
Thanks, I see them all now.
