### ISSUE TITLE
Importing .dll-s

### ISSUE THREAD

**Issue by picibucor** [kivy/kivy#5038]
I have a Kivy-App, which has to connect to a physical device. The code for connection and controlling the device is already written in .dll files. So I would like to import some functions from the .dll file.

I managed to to import it in python. Here's the code for it:

mydll.py :

```
import clr

# import dll-s
try:
    clr.AddReference("CETAx10_x15")
    clr.AddReference("Converter")
    clr.AddReference("NLog")
    clr.AddReference("ValueDefine")
    clr.AddReference("Python.Runtime")
except:
    clr.AddReference("cls\\CETAx10_x15")
    clr.AddReference("cls\\Converter")
    clr.AddReference("cls\\NLog")
    clr.AddReference("cls\\ValueDefine")
    clr.AddReference("cls\\Python.Runtime")

import CETAx10_x15
import Converter
import NLog
import ValueDefine
import Python.Runtime
import System


def get_openports():

    temp = []
    output = []

    ports_reply = CETAx10_x15.CETA.get_ports(temp)

    for elem in ports_reply[1]:
        output.append(elem)

    return output

print(get_openports())

```
Running it will return ['COM3','COM4'] , So it does what it should.

My Kivy App runs flawless without importing this mydll.py file. Importing this mydll.py in my Kivy App will return the following error-message:

> [INFO   ] [Logger      ] Record log in C:\Mirk\CETACal\logs\kivy_17-03-01_150.txt
> [INFO   ] [Factory     ] 193 symbols loaded
> [INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
> [INFO   ] [Text        ] Provider: sdl2
> [INFO   ] [Kivy        ] v1.9.2.dev0, git-c6018cc, 20170222
> [INFO   ] [Python      ] v3.4.4 (v3.4.4:737efcadf5a6, Dec 20 2015, 20:20:57) [MSC v.1600 64 bit (AMD64)]
> [INFO   ] [Logger      ] Record log in C:\Mirk\CETACal\logs\kivy_17-03-01_151.txt
> [INFO   ] [OSC         ] using <thread> for socket
> [INFO   ] [Window      ] Provider: sdl2
> [INFO   ] [GL          ] Using the "OpenGL" graphics system
> [INFO   ] [GL          ] GLEW initialization succeeded
> [INFO   ] [GL          ] Backend used <glew>
> [INFO   ] [GL          ] OpenGL version <b'4.3.0 - Build 10.18.14.4432'>
> [INFO   ] [GL          ] OpenGL vendor <b'Intel'>
> [INFO   ] [GL          ] OpenGL renderer <b'Intel(R) HD Graphics 4600'>
> [INFO   ] [GL          ] OpenGL parsed version: 4, 3
> [INFO   ] [GL          ] Shading version <b'4.30 - Build 10.18.14.4432'>
> [INFO   ] [GL          ] Texture max size <16384>
> [INFO   ] [GL          ] Texture max units <32>
> [INFO   ] [Window      ] auto add sdl2 input provider
> [INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
> [INFO   ] [EZS-2G      ] The system parameters are: ['C:\\Mirk\\CETACal\\main.py']
> ['COM3', 'COM4']
>  Traceback (most recent call last):
>    File "C:\Mirk\CETACal\main.py", line 2708, in <module>
>      EZS.run()
>    File "C:\Python34\lib\site-packages\kivy\app.py", line 802, in run
>      root = self.build()
>    File "C:\Mirk\CETACal\main.py", line 1745, in build
>      self.root = Builder.load_file(os.path.join(cls.config.kvPATH, 'root.kv'))
>    File "C:\Python34\lib\site-packages\kivy\lang\builder.py", line 301, in load_file
>      return self.load_string(data, **kwargs)
>    File "C:\Python34\lib\site-packages\kivy\lang\builder.py", line 380, in load_string
>      self._apply_rule(widget, parser.root, parser.root)
>    File "C:\Python34\lib\site-packages\kivy\lang\builder.py", line 500, in _apply_rule
>      rule.canvas_before, rootrule)
>    File "C:\Python34\lib\site-packages\kivy\lang\builder.py", line 804, in _build_canvas
>      Instruction = Factory.get('Instruction')
>    File "C:\Python34\lib\site-packages\kivy\factory.py", line 139, in __getattr__
>      module = __import__(name=item['module'], fromlist='.')
>  TypeError: __import__() takes at least 1 argument (0 given)

As you see the ['COM3', 'COM4'] is printed out.

Both my app and "mydll.py" works like a charm. 
But after importing it will fail.

I do not understand why does two independently working program fail after the import.

I'm using: Win7 python 3.4 Kivy 1.9.2.devs0 (released: 22.02)

**Comment by matham** [comment]
Seems like that the code you import in mydll is messing with python
internal import machinery.

On Mar 3, 2017 11:07 AM, "picibucor" <notifications@github.com> wrote:

I have a Kivy-App, which has to connect to a physical device. The code for
connection and controlling the device is already written in .dll files. So
I would like to import some functions from the .dll file.

I managed to to import it in python. Here's the code for it:

mydll.py :

import clr

# import dll-s
try:
    clr.AddReference("CETAx10_x15")
    clr.AddReference("Converter")
    clr.AddReference("NLog")
    clr.AddReference("ValueDefine")
    clr.AddReference("Python.Runtime")
except:
    clr.AddReference("cls\\CETAx10_x15")
    clr.AddReference("cls\\Converter")
    clr.AddReference("cls\\NLog")
    clr.AddReference("cls\\ValueDefine")
    clr.AddReference("cls\\Python.Runtime")

import CETAx10_x15
import Converter
import NLog
import ValueDefine
import Python.Runtime
import System


def get_openports():

    temp = []
    output = []

    ports_reply = CETAx10_x15.CETA.get_ports(temp)

    for elem in ports_reply[1]:
        output.append(elem)

    return output

print(get_openports())


Running it will return ['COM3','COM4'] , So it does what it should.

My Kivy App runs flawless without importing this mydll.py file. Importing
this mydll.py in my Kivy App will return the following error-message:

[INFO ] [Logger ] Record log in C:\Mirk\CETACal\logs\kivy_17-03-01_150.txt
[INFO ] [Factory ] 193 symbols loaded
[INFO ] [Image ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif
(img_ffpyplayer ignored)
[INFO ] [Text ] Provider: sdl2
[INFO ] [Kivy ] v1.9.2.dev0, git-c6018cc, 20170222
[INFO ] [Python ] v3.4.4 (v3.4.4:737efcadf5a6, Dec 20 2015, 20:20:57) [MSC
v.1600 64 bit (AMD64)]
[INFO ] [Logger ] Record log in C:\Mirk\CETACal\logs\kivy_17-03-01_151.txt
[INFO ] [OSC ] using for socket
[INFO ] [Window ] Provider: sdl2
[INFO ] [GL ] Using the "OpenGL" graphics system
[INFO ] [GL ] GLEW initialization succeeded
[INFO ] [GL ] Backend used
[INFO ] [GL ] OpenGL version <b'4.3.0 - Build 10.18.14.4432'>
[INFO ] [GL ] OpenGL vendor <b'Intel'>
[INFO ] [GL ] OpenGL renderer <b'Intel(R) HD Graphics 4600'>
[INFO ] [GL ] OpenGL parsed version: 4, 3
[INFO ] [GL ] Shading version <b'4.30 - Build 10.18.14.4432'>
[INFO ] [GL ] Texture max size <16384>
[INFO ] [GL ] Texture max units <32>
[INFO ] [Window ] auto add sdl2 input provider
[INFO ] [Window ] virtual keyboard not allowed, single mode, not docked
[INFO ] [EZS-2G ] The system parameters are: ['C:\Mirk\CETACal\main.py']
['COM3', 'COM4']
Traceback (most recent call last):
File "C:\Mirk\CETACal\main.py", line 2708, in
EZS.run()
File "C:\Python34\lib\site-packages\kivy\app.py", line 802, in run
root = self.build()
File "C:\Mirk\CETACal\main.py", line 1745, in build
self.root = Builder.load_file(os.path.join(cls.config.kvPATH, 'root.kv'))
File "C:\Python34\lib\site-packages\kivy\lang\builder.py", line 301, in
load_file
return self.load_string(data, **kwargs)
File "C:\Python34\lib\site-packages\kivy\lang\builder.py", line 380, in
load_string
self._apply_rule(widget, parser.root, parser.root)
File "C:\Python34\lib\site-packages\kivy\lang\builder.py", line 500, in
_apply_rule
rule.canvas_before, rootrule)
File "C:\Python34\lib\site-packages\kivy\lang\builder.py", line 804, in
_build_canvas
Instruction = Factory.get('Instruction')
File "C:\Python34\lib\site-packages\kivy\factory.py", line 139, in *getattr*
module = *import*(name=item['module'], fromlist='.')
TypeError: *import*() takes at least 1 argument (0 given)

As you see the ['COM3', 'COM4'] is printed out.

Both my app and "mydll.py" works like a charm.
But after importing it will fail.

I do not understand why does two independently working program fail after
the import.

I'm using: Win7 python 3.4 Kivy 1.9.2.devs0 (released: 22.02)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/kivy/kivy/issues/5038>, or mute the thread

**Comment by picibucor** [comment]
Could you give me some tipps on how to avoid it?

**Comment by matham** [comment]
You can try changing the line in which errors out in kivy.factory instead of passing in `name` as a keyword arg to a positional arg. But I don't think that fill fix it. It seems like the other library you import overwrites the `__import__` function with something that cannot handle keyword args. So it's basically a problem with the other library and not with kivy.

**Comment by picibucor** [comment]
@matham :
I just added the following line to factory.py :

> from importlib import __import__

And it works as it should
