### ISSUE TITLE
AsyncBorderImage

### ISSUE THREAD

**Issue by eteamin** [kivy/kivy#5060]
Will you consider Implementing AsyncBorderImage for kivy.graphics?

**Comment by dessant** [comment]
What is the use case for AsyncBorderImage?

**Comment by KeyWeeUsr** [comment]
I'm not quite sure what would be the reason for doing so. If it's just a matter of drawing/rendering, look at [Clock.tick](https://github.com/kivy/kivy/blob/master/kivy/clock.py#L545) as it should pretty much do the same, but in a global scale if called at the right place. Otherwise everybody can create an issue for AsyncThis and AsyncThat until we redo the whole core. 😋
