### ISSUE TITLE
Trouble installing Kivy

### ISSUE THREAD

**Issue by Billmike** [kivy/kivy#5106]
![error](https://cloud.githubusercontent.com/assets/24798364/24812413/dcb36a94-1bc1-11e7-8706-e32cab65a340.JPG)

**Comment by inclement** [comment]
When posting errors, please paste the text rather than an image, it's much easier to scan through.

In this case, it looks like you are trying to compile Kivy. Unless you specifically want to do this (e.g. for developing Kivy itself), install instead the [nightly wheel](https://kivy.org/docs/installation/installation-windows.html#nightly-wheel-installation) for your python version.
