### ISSUE TITLE
Screenmanager.children - list not populating?!

### ISSUE THREAD

**Issue by beweonline** [kivy/kivy#5144]
### Versions

* Python: 3.4
* OS: Win10
* Kivy: 1.9.1

### Description

No matter how many Screens added to Screenmanager - children list still only enlists the first screen!

### Code and Logs
Console >>> [\<Screen name='1'>]  1
but should be: [\<Screen name='1'>, \<Screen name='2'>]   2

```python
from kivy.app import App
from kivy.lang import Builder
from kivy.uix.screenmanager import ScreenManager, Screen

sm = ScreenManager()
sm.add_widget(Screen(name='1'))
sm.add_widget(Screen(name='2'))

class TestApp(App):

    def build(self):
        print(sm.children, len(sm.children))
        return sm

if __name__ == '__main__':
    TestApp().run()

```

**Comment by KeyWeeUsr** [comment]
I'm not sure if this is by design, but it does show the real amount of children + instances after the App is run(e.g. Clock + print). Anyway, it appears in master too.

**Comment by Bakterija** [comment]
This is a performance optimization, the children list is meant for active widgets.

**Comment by dessant** [comment]
Yes, this is by design. `add_widget` and `remove_widget` are overridden by `ScreenManager`, and `children` mostly holds the current screen only, or two screens during transitions. The property you're looking for may be [screens](https://kivy.org/docs/api-kivy.uix.screenmanager.html#kivy.uix.screenmanager.ScreenManager.screens).

**Comment by beweonline** [comment]
OK, makes sense now. Thank you all!
