### ISSUE TITLE
MTDEV reconnecting

### ISSUE THREAD

**Issue by audryste** [kivy/kivy#5150]
I have made improvements for mtdev input device: (implemented reconnecting). What is normal way to apply changes to master branch?

**Comment by KeyWeeUsr** [comment]
[We accept pull requests](https://github.com/kivy/kivy#contributing). Make sure you have only the related changes in your branch/pull request before applying via GitHub to prevent #5149 mistakes.

**Comment by iCmdr** [comment]
Hi! Was the pull request sent? I am currently facing a problem where the changes could help. The backlight of my usb touchscreen can't be controlled via software, so the only way I found is to cut power with a relay and power it back on if needed. The HDMI signal comes back up and works fine. Problem is that the touch controller does not register any touch events after the disconnect until the app is restarted. Since my app takes a while to start, simply restarting the app everytime isn't an option. If the mtdev provider could stay idle until the usb touch controller is back online, it should fix the problem. Thanks in advance!

**Comment by KeyWeeUsr** [comment]
@iCmdr I think there has not been any pull request regarding this issue yet.

**Comment by iCmdr** [comment]
@KeyWeeUsr Thanks for answering on such short notice. I came across issue #4406, which seems to be part of the same problem, despite dealing with a different provider. The actual logic flow seems to be roughly the same. Most screens for embedded purposes don't seem to have any backlight control nor the possibility to be switched off via software. Thus I can imagine that it is a common problem when using Kivy with these devices or any USB input device for that matter. The official Raspberry Pi display for example doesn't seem to be hotpluggable, because the i2c registers aren't being reinitialized on reconnect.
I tested some disconnection scenarios of the screen / touch controller outside of Kivy, e.g. on the desktop and the reconnect works flawlessly. Thus I can be sure that its not the device that has frozen when it disconnects.

After the touch controller has disconnected, the CPU usage of the kivy process rockets up to 100%. That would explain the observations in issue #4406 where the app becomes extremely laggy until it has been  restarted.

I have taken a look at mtdev and would love to address the issue myself, however, sadly I am not familiar with libmtdev or the inner workings of kivy :(

@audryste Could you hand in the changes / improvements you made to mtdev via pull request?


Thanks in advance for your help!

**Comment by audryste** [comment]
I will make pull request this evening or tomorrow. It will include several one more fix.
On Sunday, May 28, 2017, 10:22:58 PM GMT+3, iCmdr <notifications@github.com> wrote:
@KeyWeeUsr Thanks for answering on such short notice. I came across issue #4406, which seems to be part of the same problem, despite dealing with a different provider. The actual logic flow seems to be roughly the same. Most screens for embedded purposes don't seem to have any backlight control nor the possibility to be switched off via software. Thus I can imagine that it is a common problem when using Kivy with these devices or any USB input device for that matter. The official Raspberry Pi display for example doesn't seem to be hotpluggable, because the i2c registers aren't being reinitialized on reconnect.
I tested some disconnection scenarios of the screen / touch controller outside of Kivy, e.g. on the desktop and the reconnect works flawlessly. Thus I can be sure that its not the device that has frozen when it disconnects.

After the touch controller has disconnected, the CPU usage of the kivy process rockets up to 100%. That would explain the observations in issue #4406 where the app becomes extremely laggy until it has been restarted.

I have taken a look at mtdev and would love to address the issue myself, however, sadly I am not familiar with libmtdev or the inner workings of kivy :(

@audryste Could you hand in the changes / improvements you made to mtdev via pull request?

Thanks in advance for your help!

**Comment by iCmdr** [comment]
@audryste Thank you very much :-) I looked into the issue in the meantime and came up with a rather dirty hack, which seems to work so far, but I am sure that your solution will be way more elegant than mine 👍 

As far as my debugging showed, the high CPU load is / was caused by the device failing to idle properly after a sudden disconnect and thus bouncing back and forth in the 2 main while-loops that run very fast and indefinately. In order to prevent this, I added a check to see if the device is still connected. If not, it will idle and try to reconnect at a certain interval. If the device is back online, the previous instance of _device is replaced by a new one. Not sure if this is the best way to do it, but my short tests showed that it seems to work. I also tried to use the close() function of libmtdev, but got a pointer error that wasn't clear to me.

Again, thanks for your support, help and improvements! :)

**Comment by audryste** [comment]
My first pull request on github:
https://github.com/kivy/kivy/pull/5206

I hope this one will fix your problemsOn Wednesday, May 31, 2017, 10:05:21 PM GMT+3, iCmdr <notifications@github.com> wrote:


@audryste Thank you very much :-) I looked into the issue in the meantime and came up with a rather dirty hack, which seems to work so far, but I am sure that your solution will be way more elegant than mine 👍
 
As far as my debugging showed, the high CPU load is / was caused by the device failing to idle properly after a sudden disconnect and thus bouncing back and forth in the 2 main while-loops that run very fast and indefinately. In order to prevent this, I added a check to see if the device is still connected. If not, it will idle and try to reconnect at a certain interval. If the device is back online, the previous instance of _device is replaced by a new one. Not sure if this is the best way to do it, but my short tests showed that it seems to work. I also tried to use the close() function of libmtdev, but got a pointer error that wasn't clear to me.

Again, thanks for your support, help and improvements! :)
