### ISSUE TITLE
_clock.so: undefined symbol: _Py_ZeroStruct

### ISSUE THREAD

**Issue by federico28x** [kivy/kivy#5151]
### Versions

* Python: 3.4.2
* OS: Raspberry Jessie PIXEL (last version)
* Kivy: 1.9.2
* Kivy installation method: git clone https://github.com/kivy/kivy
cd kivy

make
echo "export PYTHONPATH=$(pwd):\$PYTHONPATH" >> ~/.profile
source ~/.profile

### Description
Trying to run any app (in this case_ minimum example "main.py" from Desktop) gives error in _clock.so.
I've done clean install from cython (0.23), kivi (1.9.2), & dependencies.
Same results.

### Code and Logs

[INFO   ] [Logger      ] Record log in /home/pi/.kivy/logs/kivy_17-05-01_38.txt
[INFO   ] [Kivy        ] v1.9.2.dev0, git-ead4655, 20170501
[INFO   ] [Python      ] v3.4.2 (default, Oct 19 2014, 13:31:11) 
[GCC 4.9.1]
 Traceback (most recent call last):
   File "/home/pi/Desktop/main.py", line 4, in <module>
     from kivy.app import App
   File "/home/pi/kivy/kivy/app.py", line 319, in <module>
     from kivy.base import runTouchApp, stopTouchApp
   File "/home/pi/kivy/kivy/base.py", line 29, in <module>
     from kivy.clock import Clock
   File "/home/pi/kivy/kivy/clock.py", line 362, in <module>
     from kivy._clock import CyClockBase, ClockEvent, FreeClockEvent, \
 ImportError: /home/pi/kivy/kivy/_clock.so: undefined symbol: _Py_ZeroStruct

**Comment by KeyWeeUsr** [comment]
Cython 0.23 should be already high enough, but try to update it to the latest one if available. Kivy on RPi works fine for me so I think it's just a faulty compilation most likely because of missing `Python.h` or other Python headers.

If you already have the headers, you've updated cython and still it doesn't start, I'd even go that far to check if python version and the headers package(s) match i.e. if you have installed python-dev for `3.4` and not for `3.3`. At least on Ubuntu they have it separated i.e. `python3.3-dev`, `python3.4-dev`, etc.

**Comment by federico28x** [comment]
Thank You!
Already updated to Cython 0.25 and still the same...
How do I check the headers?
Sorry...I'm still learning.

**Comment by federico28x** [comment]
I've found that "clone install" produces the problem. Reinstalled "globally" @master and works.

**Comment by KeyWeeUsr** [comment]
@federico28x Try to install it from the clone [this way](http://www.developerfiles.com/pip-install-from-local-git-repository/):

    pip install git+file:///path/to/your/git/repo@branch

For me it fails from clone with `svg.pyx` I think, but with this way it's fine.

**Comment by federico28x** [comment]
Thanks!!!
