### ISSUE TITLE
Feature Request: Boolean property to make widget non-existent in the UI

### ISSUE THREAD

**Issue by mark-orion** [kivy/kivy#5166]
We need an elegant way to be able to make a widget disappear from the UI:
- widget is non-existent for the user. It does not take up any space in or outside the UI etc.
- hiding should be independent from the layout. All types of layout should support this feature.
- parent widgets resize their children as if the hidden widget does not exist.
- all properties of the widget can be accessed while it is hidden.

**Comment by matham** [comment]
This can already be done by removing the widget from its parent or by putting its position outside the visible screen.

Otherwise, it doesn't quite make sense to make a widget invisible when it's still the child of something. E.g. what does a boxlayout do when a child is invisible? Skip it? Or lay it out like normal? In the former, why not just remove it from the children list. In the latter, it'd look weird and is not a common thing to do.
