### ISSUE TITLE
Error in get_deps_minimal

### ISSUE THREAD

**Issue by taisreis** [kivy/kivy#5180]
* Python: 3.5
* OS: Windows 8
* Kivy: 0.10.0
* Kivy installation method: python -m pip install kivy
* Pyinstaller: 3.2.1

I'm trying use "get_deps_minimal" in my .spec file but I get the following error: [CRITICAL] App: Unable to get a Text provider, abort.

Logs and my .spec file:
 https://gist.github.com/taisreis/69a94c437e5afad627277a6e444ac933

**Comment by matham** [comment]
The default text provider should have been used in this case. What is it (i.e. what does the log say when you run kivy normally)?

What happens if you specify that provider like you specify gstreamer?

**Comment by taisreis** [comment]
Hi @matham I set the text provider to SDL2 and now I get another error.

When I execute with the text provider set to SDL2 I get the follow error:
https://gist.github.com/taisreis/b0d08f8fcfa860266954b24d87a9fbd3

When I execute without "get_deps_minimal" it works fine although occurs some import errors:
https://gist.github.com/taisreis/b0d08f8fcfa860266954b24d87a9fbd3

**Comment by matham** [comment]
I meant can you share a log of you running the kivy app without pyinstaller. Because I want to see what providers are used.

Also, you have problem in your code. If you look [here](https://kivy.org/docs/api-kivy.tools.packaging.pyinstaller_hooks.html#kivy.tools.packaging.pyinstaller_hooks.get_deps_minimal) you'll see that it `"a dict with two keys, hiddenimports and excludes."`. So you need to remove them from the function call, otherwise it's passed twice.

If you need to pass hiddenimports  to the function, you should append it to the key in `hiddenimports` in the result of `get_deps_minimal`.

**Comment by taisreis** [comment]
Hi @matham 

The log when I'm running the kivy without pyinstaller:
[kivy_17-05-19_31.txt](https://github.com/kivy/kivy/files/1015282/kivy_17-05-19_31.txt)

I remove the `hiddenimports` and the `excludes` and it's works fine, but how I place the `requests` import in the `get_deps_minimal`, is only to put 'request'?

**Comment by matham** [comment]
The returned dict from get_deps_minimal has two keys hiddenimports and excludes whose values are lists. You can update those lists in the dict with e.g. requests and pass it on to the function.
