### ISSUE TITLE
Accessing root_window.left throws Exception under Ubuntu

### ISSUE THREAD

**Issue by DaytonaJohn** [kivy/kivy#5224]
### Versions

* Python: 3.6.1
* OS: Ubuntu 16.04
* Kivy: 1.10.0
* Kivy installation method: honestly do not remember

### Description

Trying to get an app to remember its location and size on the device screen, then use that same location and size when restarted. Saving size and location info to a user-specific ini file when the app is closed (in the on_stop() method).
The code below works fine under Windows 10 with the same Python and Kivy versions. Under Ubuntu, I get an Exception. I suspect this is a bug in Kivy under Ubuntu.

### Code and Logs
    import os.path
    from kivy.config import Config
    Config.read(str(os.path.join(os.path.expanduser('~'), 'sizeandloc.ini')))
    from kivy.app import App
    from kivy.uix.relativelayout import RelativeLayout
    from kivy.uix.label import Label
    from kivy.uix.button import Button
    from kivy.core.window import Window
    import traceback
    import os.path

    class SizeAndLoc(RelativeLayout):
        def __init__(self):
            super(SizeAndLoc, self).__init__()

    class SizeAndLocApp(App):
        def build(self):
            root = SizeAndLoc()
            label = Label(text='This is a Test', pos_hint={'center_x': 0.5, 'y': 0.75}, size_hint=[0.5, 0.2])
            root.add_widget(label)
            button = Button(text='Quit', pos_hint={'center_x': 0.5, 'y': 0.25}, size_hint=[0.5, 0.2], on_press=self.do_quit)
            root.add_widget(button)
            return root

        def get_application_config(self, **kwargs):
            return os.path.join(os.path.expanduser('~'), 'sizeandloc.ini')

        def do_quit(self, *args):
            self.stop()

        def on_start(self):
            pass

        def on_pause(self):
            # Here you can save data if needed
            return True

        def on_resume(self):
            # Here you can check if any data needs replacing (usually nothing)
            pass

        def on_stop(self, *args):
            window = self.root_window
            Config.set('graphics', 'position', 'custom')
            Config.set('graphics', 'left', str(window.left))
            Config.set('graphics', 'top', str(window.top))
            Config.set('graphics', 'width', str(window.width))
            Config.set('graphics', 'height', str(window.height))
            if Config.write():
                print('config written to ' + str(Config.filename) + '\n')
            else:
                print('failed to write config\n')

    if __name__ == '__main__':
        app = SizeAndLocApp()
        try:
            app.run()
        except Exception:
            traceback.print_exc()

The lines of interest from the stacktrace:
   File "main.py", line 49, in on_stop
     Config.set('graphics', 'left', str(window.left))
   File "kivy/properties.pyx", line 483, in kivy.properties.Property.__get__ (/tmp/pip-build-vf10dxpy/kivy/kivy/properties.c:5670)
   File "kivy/properties.pyx", line 1467, in kivy.properties.AliasProperty.get (/tmp/pip-build-vf10dxpy/kivy/kivy/properties.c:23970)
   File "/usr/local/lib/python3.6/site-packages/kivy/core/window/__init__.py", line 743, in _get_left
     return self._get_window_pos()[0]
 TypeError: 'NoneType' object is not subscriptable

**Comment by Bakterija** [comment]
Just tested with kivy 1.9.2 and kivy 1.10, i don't see this issue.

**Comment by Bakterija** [comment]
The pr is not for this error

**Comment by DaytonaJohn** [comment]
Here is the entire log:
[kivy_17-06-17_25.txt](https://github.com/kivy/kivy/files/1082568/kivy_17-06-17_25.txt)

**Comment by KeyWeeUsr** [comment]
From log:

>[INFO   ] Window: Provider: pygame(['window_egl_rpi'] ignored)

@DaytonaJohn [`Window.left`](https://kivy.org/docs/api-kivy.core.window.html#kivy.core.window.WindowBase.left) together with `Window.top` are properties fetched from SDL2 and aren't available in `pygame` provider unless they're [set via `Config`](https://github.com/kivy/kivy/blob/master/kivy/core/window/window_pygame.py#L74), but even then they aren't updated after the window is created. Since a default return is `None` for a Python function, the error is about `NoneType`. Basically this:

```python
def blob(): pass
blob()[0]
```

The only situation when `left` and `top` are updated is when [`_window_sdl2.get_window.pos()`](https://github.com/kivy/kivy/blob/master/kivy/core/window/_window_sdl2.pyx#L236) is called, which is when you have an SDL2 provider and do e.g. `print(Window.left)` as the `left` and `top` are just [AliasProperties](https://kivy.org/docs/api-kivy.properties.html#kivy.properties.AliasProperty).

Switch to SDL2 provider on your OS and it'll work.

**Comment by DaytonaJohn** [comment]
Thanks for the information, but in my world, this is a bug.
Unfortunately, I will have to access the information I need by working around Kivy, through the underlying OS.

**Comment by KeyWeeUsr** [comment]
@DaytonaJohn It's not a bug because the feature of a retrievable value of Window position was introduced quite recently and only for the SDL2 provider. Otherwise anything you'd actually get from the `Window.left` or `Window.top` would be a position set by you in `Config` at best. You could compare it to a missing Cortana in WinXP. 😋 

On the other hand, it might be nice to backport it even though the main provider _is_ SDL2, so feel free to make a pull request.

Also, I don't see why you'd need to do any workaround as you clearly **have** the latest kivy version, so just [install the new provider and recompile/reinstall](https://kivy.org/docs/installation/installation-linux.html#ubuntu-example).
