### ISSUE TITLE
Erratic button behavior

### ISSUE THREAD

**Issue by zedr** [kivy/kivy#5234]
### Versions

* Python: 3.6/2.7
* OS: Linux/Android
* Kivy: 1.9.1/1.10.0
* Kivy installation method: buildozer

### Description

Button appear to be triggered by simple mouse movement. This behavior occurs both on my Linux development machine and when I deploy to my Android device.

### Code and Logs

https://github.com/zedr/cerebellum

```
class CerebellumApp(App):
    kv_directory = KIVY_TEMPLATES_PATH

    def build(self):
        return Button()
```

**Comment by dessant** [comment]
Could you check with the latest kivy version? Please also embed a simple example here and confirm that the bug is reproducible with it.

**Comment by zedr** [comment]
Thanks for taking a look at it. I've updated the ticket. If you checkout and build my project you should be able to reproduce it.

**Comment by dessant** [comment]
Based on the information you provided, the issue cannot be reproduced. We usually do not debug an entire repository on the issue tracker, this is why a self-contained example which reproduces the issue is required.

The example you have embedded does not bind to any event which could show that the button is triggered by moving the mouse over it.

Please open a new issue by following the guidelines at the top of the issue template: https://raw.githubusercontent.com/kivy/kivy/master/.github/ISSUE_TEMPLATE.md
