### ISSUE TITLE
Feature Request: Custom app title bars with window drag support

### ISSUE THREAD

**Issue by EndilWayfare** [kivy/kivy#5279]
### Description

I was trying to make a custom window title bar with `Window.borderless = True` and replacing default OS functionality (close, maximize, etc.) with Button widgets. I could not, however, figure out how to move the position of the window by dragging with `on_touch_move`, or similar. The screen coordinate system doesn't seem to match up with the OS system, and movement becomes unstable the further the drag goes from original position.

I gather from research that getting/setting the position of windows is very reliant on the underlying windowing system, and can vary greatly depending on the host platform. It would be cool if Kivy supported custom app title bars. The necessary permutations for supported windowing systems is very beyond my personal experience.

**Comment by KeyWeeUsr** [comment]
Yep, that touch thing kicked me too, unfortunately, when I was trying to do exactly the same. I still think that there wasn't just the right touch position calculated, although maybe it's as you say and it's platform dependent (I really hope nah).

Anyway, about custom title bars, I'm not sure if it's available for all platforms because e.g. Firefox which allows you to change the style on Windows to something like this([article](https://www.codeproject.com/articles/140267/create-custom-windows-in-wpf-with-ease), there's an official one I forgot link for):

![image](https://user-images.githubusercontent.com/8825439/28238394-d2db44ae-6952-11e7-8598-dfedc19c6a17.png)

behaves completely different on Linux Mint for me i.e. it's just inserted into an ordinary window frame (it's ugly as hell), but that might be just because of some missing plugin/library, so feel free to prove me wrong 😋 

Changing the app title bar might not be implemented because of the missing platforms and you can make one just with drawing on [`Canvas`](https://kivy.org/docs/api-kivy.graphics.html#kivy.graphics.Canvas) or showing images. However, the touch/window-dragging seems a really good thing to me.

For now I have no clue how to implement it except setting with [`Window.left`](https://kivy.org/docs/api-kivy.core.window.html#kivy.core.window.WindowBase.left) + [`Window.top`](https://kivy.org/docs/api-kivy.core.window.html#kivy.core.window.WindowBase.top) as I was trying in the first place, but the result for me was that when dragged only ~5px or so, the Window "locked" itself and started moving e.g. in one direction until I released the button.

If I find the source, I'll post it here, but I think I removed it as it "didn't work for me". 😢

**Comment by EndilWayfare** [comment]
I didn't actually want to customize the existing Windows title bar (which, yeah, I'm sure is very platform dependent, and uses the abyss that is Win32 API). I wanted to get rid of it and replace its functionality with pure Kivy widgets, as you describe.

I could probably hack together a simple example of what I tried to put together. Basically, I think the main problem is that kivy's internal "screen space" coordinate system is scaled differently than Windows'. I got `Window.left` and `Window.right` to respond to `touch.dpos` in a `on_touch_move` event, but the window didn't move as far as I dragged. It works (kind of) when dragging down or to the right, but fails in the opposite direction because you drag outside of the window, which is not keeping up.

I'm on Windows 10, so I would not be shocked at all if this has something to do with native scaling for high-DPI displays, or whatever.

**Comment by urbanonymous** [comment]
> I didn't actually want to customize the existing Windows title bar (which, yeah, I'm sure is very platform dependent, and uses the abyss that is Win32 API). I wanted to get rid of it and replace its functionality with pure Kivy widgets, as you describe.

I'm planning to do a custom title bar using `Config.set('graphics', 'borderless', '1')` and adding a title bar inside the kivy app.

Do you have that  ```I got Window.left and Window.right to respond to touch.dpos in a on_touch_move event, but the window didn't move as far as I dragged. It works (kind of) when dragging down or to the right, but fails in the opposite direction because you drag outside of the window, which is not keeping up.``` code around?


Thanks

**Comment by webpolis** [comment]
This is a must. I have a custom class inherited from `ActionBar` widget and added the following event handlers:

```

     def on_touch_down(self, touch):
         print("\CustomActionBar.on_touch_down:")

         if self.collide_point(*touch.pos):
             print("\ttouch.pos =", touch.pos)
             self.touch_x, self.touch_y = touch.spos[0], touch.spos[1]

             return True

         return super(CustomActionBar, self).on_touch_down(touch)

     def on_touch_move(self, touch):
         print("\CustomActionBar.on_touch_move:")

         if self.collide_point(*touch.pos):
             print("\ttouch.pos =", touch.pos)
             Window.top = self.touch_y + touch.spos[1]
             Window.left = self.touch_x + touch.spos[0]

             return True

         return super(CustomActionBar, self).on_touch_move(touch)
```

But it doesn't move as expected, and it's totally wrong.

**Comment by jcradzwill** [comment]
I have been able to accomplish this in Windows 10 using workarounds. You have to utilize a mouse listener outside of Kivy to prevent the Window from 'skipping' when being dragged and resized. I used pynput in my example. 

Please see my github post here for the full example:

https://github.com/jcradzwill/Create-custom-title-bar-in-Kivy

This workaround is not perfect, but it is a good start.
