### ISSUE TITLE
SDL2 Window.on_textinput event is not being called

### ISSUE THREAD

**Issue by Bakterija** [kivy/kivy#5296]
### Version

* Python: Any
* OS: Any
* Kivy: Stable 1.10 and master
* Kivy installation method: Any

### Description

Hello.
As talked about it #5244 already, the problem is that self._win.hide_keyboard() calls SDL_StopTextInput() in the [sdl2 cythonized module](https://github.com/kivy/kivy/blob/master/kivy/core/window/_window_sdl2.pyx#L301-L303). [That function](https://wiki.libsdl.org/SDL_StopTextInput) **disables textinput events completely**. TextInput widgets work because SDL_StartTextInput is called on focus gain.

My example app shows it very well [here](https://gist.github.com/Bakterija/bbe89c1b95857255e71abc215591783b)

Is there a good reason for disabling it ?
This is supposed to be a [feature of kivy](https://kivy.org/docs/api-kivy.core.window.html#kivy.core.window.WindowBase.on_textinput) and you might want to change the docs, if it isn't meant to be used this way

**Comment by tshirtman** [comment]
I'm actually more surprised that it works before the TextInput gets the focus, i agree it doesn't seem to cause any issue since the typed text is not actually added to the TextInput, but it's rather weird that it gets events without any intent to use them. The way i understand the feature documentation, is that it's only called when text is entered in the textinput (as opposed to when other keys are pressed), i don't see any specification that it is/should be called when the TextInput has no focus (no text is entered since it doesn't have focus).

**Comment by Bakterija** [comment]
@tshirtman the event is triggered from any keyboard text input, unless you disable it, which kivy is doing right now. having it work outside of textinput widgets is useful when you want to make an input widget that pops in when you start typing, in some cases you also might want to use text based hotkeys.
The corent code prevents that.

**Comment by Bakterija** [comment]
I don't think that it is intended to be used like that by core devs, so i don't see any reason to talk about it .
