### ISSUE TITLE
actionbar: entries get swapped between the dropdowns of consecutively clicked actiongroups

### ISSUE THREAD

**Issue by tiktok7** [kivy/kivy#5337]
### Versions
* Python: 3.4.3
* OS: Linux-3.13.0-24-generic-x86_64
* Kivy: 1.10.1.dev0
* Kivy installation method: manual (git repo)

### Description
Steps to recreate the problem
1. Run `python3 ./kivy/uix/actionbar.py`
2. Quickly click Group1 and Group2 alternately until the options from one menu show up in the other

### Code and Logs
Having debugged the events, it appears that the problem is multiple calls of the ActionGroup._toggle_dropdown(). Both the on_release and dismiss events trigger the same _toggle_dropdown. The result is that the event is called three times so the is_open property is set incorrectly.

**Comment by tiktok7** [comment]
proposed solution #5338

**Comment by KeyWeeUsr** [comment]
I've noticed the bug too, however I believe that those lines aren't entirely bad. Instead, it appears to me that there was a [design flaw](https://github.com/kivy/kivy/blob/83ec08750babec892d1fd46c2f14b292b5144ed6/kivy/uix/dropdown.py#L298) since the introduction of the `DropDown` widget and that's `self.dismiss()` in both `on_touch_down` and in `on_touch_up`.

It's not like that's bad per se, however `on_dismiss` event is triggered in both of them, which quickly falls down with the current implementation of `Spinner`/`DropDown`-ish like behavior that binds to that particular event the `_toggle_dropdown()` function.

In most of the `DropDown`s I've seen the elements are removed when the touch/click is released, so I tried that. When I removed the `self.dismiss()` part for `DropDown.on_touch_down()`, it made stuff better, but I still think the widget itself needs a rewrite as it doesn't use anything but `DropDown` from the `Spinner` it currently uses.

This is fixed in the linked PR #5339.
