### ISSUE TITLE
Kivy does not have a project description at https://pypi.org/project/Kivy/

### ISSUE THREAD

**Issue by inclement** [kivy/kivy#5353]
https://pypi.org/project/Kivy/

For the project description to appear in the listing, it seems it has to be added as the `long_description` kwarg to setup in the setup.py.

In python-for-android I just read in the README.rst and pass this as the long_description. Kivy could do something similar, although currently it has a README.md which would not display properly as pypi only supports rst.

**Comment by KeyWeeUsr** [comment]
Afaik, the description is updated per release (or manually via pypi account). We can convert the markdown file, but if I remember correctly, I tried to do so in the past without any success because the image on the right and some other elements that won't let go if used with RST syntax.

It's not that RST isn't capable of displaying it properly, but rather GitHub cripples the formatting (even when used with `.. raw:: html`). It might be a good idea to fetch either only some specific parts from the `README.md` file or just copy the parts directly to the `setup.py` file. We don't change the description so often :D

**Comment by inclement** [comment]
I opened this issue because it no longer seems to be possible to update the package information manually via the web interface. Trying to do so returns the following text:

> Gone (This API has been deprecated and removed from legacy PyPI in favor of using the APIs available in the new PyPI.org implementation of PyPI (located at https://pypi.org/). For more information about migrating your use of this API to PyPI.org, please see https://packaging.python.org/guides/migrating-to-pypi-org/#uploading. For more information about the sunsetting of this API, please see https://mail.python.org/pipermail/distutils-sig/2017-June/030766.html)

The new https://pypi.org/ doesn't seem to have a replacement web interface for this. I'm not sure if one is intended.

**Comment by misl6** [comment]
Fixed via https://github.com/kivy/kivy/pull/5762
