### ISSUE TITLE
Remove Kivy-Garden dependency

### ISSUE THREAD

**Issue by vanschelven** [kivy/kivy#5384]
On https://github.com/kivy/kivy/issues/5367 I said the following:

> The package `kivy-garden` is pulled in by the `kivy` package, even though there is no actual _dependency_ of the former on the latter (AFAIU). Kivy-garden then goes and worsens the situation by pulling in `requests`, which pulls in further packages (`urllib3`, `certifi`, `idna` & `chardet`). I would suggest to remove the dependency, and let those that want to install `kivy-garden` just install it themselves. TBH I don't understand the need for kivy-garden in the first place, it would seem to be a half-baked "not invented here" implementation of `pip`/`PyPI` but perhaps I'm missing something.

I still stand by those remarks; to make place for a single location for discussion and possible implementation I've now split this out into an issue of itself.

**Comment by dessant** [comment]
We could also install directly from GitHub with pip, but all garden flowers would have to be converted to proper packages.

**Comment by KeyWeeUsr** [comment]
@dessant nothing to do here regarding the conversion until https://github.com/pypa/pip/issues/4230 is resolved. :-/

@vanschelven feel free to rewrite it, so that it doesn't depend on so many packages (I also dislike too many deps :) ), otherwise `garden` is a tool/repo for [sharing](http://kivy-garden.github.io/gallery.html) widgets/behaviors/code-pieces related to Kivy that can make things easier for many users (i.e. DRY). Simply said it's a place for non-core stuff that people felt it'd be nice to give to the community. `RecycleView` was in there quite recently.

Personally I feel like removing garden would be a kick to the back of the users who contributed to the garden, therefore the only way I see it now is improving the garden (even if it means cutting off the deps and rewriting stuff manually) or converting. Since converting has a hard block, I'm closing this issue. Reopen if the conversion can be brought up.
