### ISSUE TITLE
kivy's hello world issues in atom editor

### ISSUE THREAD

**Issue by xmen1412** [kivy/kivy#5398]
Versions

* Python: Python 3.6
* OS: Windows 10 64bit
* Kivy: version 1.10.0
* Kivy installation method: pip install kivy

### Description

i write a code on atom editor when i want re write the example of code from kivy documentation 
there is module error in my atom

### Code and Logs

here's is the code from https://kivy.org/docs/guide/basic.html

```python
import kivy


from kivy.app import App
from kivy.uix.button import Button

class Myapp(App):
    def build(self):
        return Button(text = 'Hello kivy')


if __name__ == '__main__':
    Myapp().run()
```
then the error pop up 

`Traceback (most recent call last):
  File "C:\Users\akbar\Documents\kivy.py", line 1, in <module>
    from kivy.app import App
  File "C:\Users\akbar\Documents\kivy.py", line 1, in <module>
    from kivy.app import App
ModuleNotFoundError: No module named 'kivy.app'; 'kivy' is not a package
[Finished in 0.144s]`

**when i recheck my pip my kivy has been already install with version 1.10.0**
![kivy](https://user-images.githubusercontent.com/29954788/30779947-67d2ab16-a129-11e7-97e5-9b81559f1f3c.PNG)

**Comment by bionoid** [comment]
Unless you get the same error outside of Atom, this seems like a configuration issue. Most likely your Atom is using the wrong Python executable/installation, ie not the one where you installed Kivy

**Comment by KeyWeeUsr** [comment]
Try these lines:

```python
import sys
print(sys.executable)
```

I think the same as bionoid i.e. the interpreter doesn't match the one where you installed the packages (perhaps a virtualenv). You need to activate the virtualenv (if using one) first when working with editor otherwise it'll just grab the default one from the path i.e. the one without Kivy installed in it.

Anyway, this isn't a Kivy issue, rather an issue of your editor (e.g. it did stuff in the background and this is the result) and/or the lack of understanding of editor's manual. Try to ask on the Atom's support channels or reinstall Kivy from within Atom (so that it installs it in virtualenv if that's the case).
