### ISSUE TITLE
Kivy Minimum required OpenGL version (2.0) NOT found

### ISSUE THREAD

**Issue by desmond75** [kivy/kivy#5640]
Versions

* Python:  2.7.14
* OS: Windows7
* Kivy:  v1.10.0
* Kivy installation method: using pip

Description
i am trying to to run the kivy example app and when i run i get this error  [CRITICAL] [GL          ] Minimum required OpenGL version (2.0) NOT found!

OpenGL version detected: 1.1

Version: 1.1.0
Vendor: Microsoft Corporation
Renderer: GDI Generic

Try upgrading your graphics drivers and/or your graphics hardware in case of pro
blems.

The application will leave now.
i have research on the and found some solutions but none is working for eg adding 
```
from kivy import Config
Config.set('graphics', 'multisamples', '0')
```
at the top of my code and it still does not work 

from kivy import Config
Config.set('graphics', 'multisamples', '0')
Code and Logs
```
import kivy 
kivy.require('1.9.1') # replace with your current kivy version !

from kivy.app import App
from kivy.uix.label import Label

class MyApp(App):

    def build(self):
        return Label(text='Hello world')

if __name__ == '__main__':
    MyApp().run()
```

this are some of the picture of my computer system 
![driver](https://user-images.githubusercontent.com/27916806/36889338-69c5cf46-1dae-11e8-9615-0738d413a841.PNG)
![drivers 3](https://user-images.githubusercontent.com/27916806/36889340-6a02743c-1dae-11e8-8811-3b19f8c47db2.PNG)
![drivers2](https://user-images.githubusercontent.com/27916806/36889343-6a3c1e62-1dae-11e8-84b4-cff6160d84db.PNG)
![windows](https://user-images.githubusercontent.com/27916806/36889344-6a8b1b34-1dae-11e8-8b99-7bb5a67f3a5f.PNG)
pip list
![pip list](https://user-images.githubusercontent.com/27916806/36889815-78f03900-1db0-11e8-9960-681ac5e77272.PNG)

please i need help as i have been on this for more than a week today and feeling very frustrated with coding

**Comment by bionoid** [comment]
"Standard VGA graphics adapter" -- you do not appear to have a driver with OpenGL ES 2.0 support installed.

**Comment by desmond75** [comment]
ok so what do i do now?

**Comment by bionoid** [comment]
First make sure your graphics adapter actually supports OpenGL ES 2.0, then download and install a driver for it.

**Comment by tito** [comment]
Same as bionoid said. Same as the minimal requirements. If you don't meet them, then Kivy can't be used on your computer.

1. Find a OpenGL driver that works on your chip
2. If you have DirectX 9 working, then try the ANGLE version

We cannot help if you don't meet the minimal requirements!

**Comment by desmond75** [comment]
how doi find the this  OpenGL driver please guide me through this

**Comment by bionoid** [comment]
@desmond75 first identify your graphics adapter (manufacturer and model number). From the window shown in your first screenshot, click "details" tab on top, then for "property" select "Hardware Ids". Right-click the top value, select copy and then search for information about it:

![hwid](https://user-images.githubusercontent.com/1098382/37423315-d1d650ec-27bd-11e8-8caa-4f21081a0769.jpg)

Alternatively you can open the computer and look at it, or search for the make and model number if it's a laptop. Or you can try [UnknownDevices](http://www.halfdone.com/ukd/) (but it only lists vista support, I haven't used this since XP days). 

Once you know what graphics card you have, you can try to find drivers that support either OpenGL ES2.0 or DirectX 9. This may not be possible, if the card is too old you need a new one to use Kivy
