### ISSUE TITLE
copy paste in password view

### ISSUE THREAD

**Issue by niceboypy** [kivy/kivy#5704]
Look at this weird behaviour of text input widget's password attribute, When I click the show toggle button then it simply sets the password attribute of text widget to True nothing more, then copying the password ACTUALLY COPIES ASTERISKS , I don't think this is an expected behaviour, THE VIDEO IS IN THIS LINK: https://youtu.be/6bmsxaNHedk

**Comment by KeyWeeUsr** [comment]
This is actually a desired feature in many applications(e.g. some database GUI clients) and browsers because of how [clipboard works](https://security.stackexchange.com/a/33429/106776). See even [this](https://security.stackexchange.com/q/149326/106776) question.

Basically - if it's a password, it should be protected against the copying and if it's not, then it's just a plain text which you already can copy without issues.
