### ISSUE TITLE
help:: your website always cannot open but ping is ok . location:China [SOLVED]

### ISSUE THREAD

**Issue by linpan** [kivy/kivy#5712]
''''➜  ~ ping www.kivy.org
PING kivy.org (159.203.106.198): 56 data bytes
64 bytes from 159.203.106.198: icmp_seq=0 ttl=50 time=312.178 ms
64 bytes from 159.203.106.198: icmp_seq=1 ttl=50 time=249.017 ms
64 bytes from 159.203.106.198: icmp_seq=2 ttl=50 time=291.739 ms
'''
ping is ok but web is ERR_TIMED_OUT.

>  i use vpn (called ssr )
### wo can offline website(https://kivy.org/docs/gettingstarted/intro.html) for offline read? thank you

**Comment by kuzeyron** [comment]
Have you tried using VPN?
If not, check [comparitech.com](https://www.comparitech.com/blog/vpn-privacy/whats-the-best-vpn-for-china-5-that-still-work-in-2016/). It could help you.

**Comment by linpan** [comment]
@kuzeyron  comparitech.com but https://kivy.org/docs/gettingstarted/intro.html is not working

**Comment by bionoid** [comment]
Seems like an issue in your end, since the service is working normally for others. You may be able to view [kivy docs at readthedocs.io](http://kivy.readthedocs.io/en/master/), there is also a [PDF download on RTD for offline viewing](https://media.readthedocs.org/pdf/kivy/master/kivy.pdf). 

As a last resort, the [doc sources are on GitHub](https://github.com/kivy/kivy/tree/master/doc/sources) but that's not very practical to read..

**Comment by linpan** [comment]
> in home or workplace . mac ,iphone  or windows, .  indeed can not access your website.

**Comment by linpan** [comment]
[SOLVED OUT]
@kuzeyron  ssr  set pac to Global mode is okay .thanks  everyone
