### ISSUE TITLE
TextInput field not displaying inputs in macOS

### ISSUE THREAD

**Issue by ahuangJM** [kivy/kivy#5744]
### Versions

* Python: 3.5.2
* OS: macOS Sierra
* Kivy: 1.10.0
* Kivy installation method: python -m pip install kivy (from website)

### Description

input to textinput field, expect text to appear in the textinput field, but nothing appears in the textinput field.

worked on windows though, so might be a OS thing?

### Code and Logs

```python
class FirstLaw(Screen):
    def __init__(self, **kwargs):
        super(FirstLaw, self).__init__(**kwargs)
        variable1=Label(text='let Log(M)= ',pos=(-325,220))
        variable1.font_size = '20dp'
        self.add_widget(variable1)
        self.v1 = TextInput(text='',pos_hint={'x': .2, 'center_y': .9}, size_hint=(.1, .1))
        self.add_widget(self.v1)
        variable2=Label(text='let Log(N)= ',pos=(-100,220))
        variable2.font_size = '20dp'
        self.add_widget(variable2)
```

**Comment by bionoid** [comment]
Please check the log in console when you start a kivy app -- in particular the active window provider:

    [INFO   ] [Window      ] Provider: sdl2

Does it by any chance say "pygame" instead of "sdl2" for you? If so, that is your problem, pygame backend has been deprecated for years (no longer maintained). Pygame is straight up broken on MacOS with retina display, it will result in weird issues like what you describe.
