### ISSUE TITLE
Kivy disables KDE Plasma Compositor upon Window creation

### ISSUE THREAD

**Issue by Vencorr** [kivy/kivy#5810]
### Versions

* Python: 3.6.5
* OS: Kubuntu 18.04 x86_64
* DE: KDE Plasma 5.12.5 with Framework 5.46.0
* Kivy: 1.10.1.dev0
* Kivy installation method: Compiled from source

### Description

I am experiencing an issue with the creation of the window. When I run a simple python script that creates a kivy window, my compositor gets completely disabled. I can workaround this issue by disabling "Allow applications to block compositing" but it must have been enabled by default for a reason, right?

### Code and Logs

Doesn't matter what I use to create a kivy window, as it always disables it. The only thing the kwin logs show is a restart to disable the compositor. No errors, nothing. I'm assuming this is normal due to it disabling it and not crashing it. Kivy itself doesn't even give any errors. Just a few warnings I assume is normal:
```
[WARNING] [Modules     ] Module <kivy> not found
[WARNING] [Base        ] Unknown <pygame> provider
```

I installed all the necessary dependencies found on the 'Getting Started' kivy page and compiled from there using instructions also found on those pages. If I am missing any packages or modules, let me know. If you need a complete log or output from something, just ask.

**Comment by mamoit** [comment]
Let me guess... nvidia graphics.

**Comment by Vencorr** [comment]
Yes, I happen to be running Nvidia graphics.

**Comment by tshirtman** [comment]
i wonder if this https://community.kde.org/KWin/Environment_Variables#KWIN_COMPOSE could help, it might be because kivy is built against OpenglES and you use OpenGL for kwin (or some other incompatible combination), or it could be that *all* our window provider somehow ask for composition to be disabled (apparently kwin supports that by default), though i don't see any code on our side doing that, it could be that SDL2, PyGame, X11 all do that, though i doubt it.

**Comment by mamoit** [comment]
I have had this problem with Steam.
[Welcome to hell](https://bugs.kde.org/show_bug.cgi?id=353983).

**Comment by Dinsmoor** [comment]
I had this until I did a apt-update and upgrade, the problem went away (at least for kivy 1.9.1 on bionic.)
I'm not sure which package it was, but it was likely upstream, not Kivy's fault.

Also, Kivy switch to Gitlab?

**Comment by Vencorr** [comment]
I have been meaning to respond but I kept forgetting.

tshirtman, changing the environmental variables of KWIN failed to make a difference. Even changing the Compositor settings in the System to use not OpenGL 3.1 or 2.0, but XRender did nothing. It still happens.

Dinsmoor, I am using kivy compiled from source, not bionic packages. If the problem has been fixed between the bionic packages and master, then it isn't working.

Again, disabling the option for applications to block compositing works fine for kivy. No issues persist with that.

The problem also persists with AMD graphics aswell. I have integrated AMD graphics from an A8 processor on my system. Booting from those graphics works fine, compositing is enabled, but the issue remains. I'm gonna test it on Plasma 5.13 and see if that is the issue, since I have recently installed KDE Neon instead of sticking with Kubuntu. Will reply back with some more results and information.

**Comment by Vencorr** [comment]
> I'm gonna test it on Plasma 5.13 and see if that is the issue, since I have recently installed KDE Neon instead of sticking with Kubuntu. Will reply back with some more results and information.

Oops, completely forgotten about this.
Just tested it and it still has issues with the compositor. Whatever kivy is doing, Kwin is not a fan of.

**Comment by dolang** [comment]
From what I can tell, Kivy isn't doing anything special (although my knowledge here is limited), and it targets OpenGL ES 2.0, which is rather old.

I do know that KWin has problems in a Virtualbox Linux guest with hardware accelerated graphics. I use VMs for a few things and generally turn that off when using KDE. Random-things-that-probably-won't-help™ you could try:
- [switch the OpenGL backend](https://kivy.org/docs/guide/environment.html#graphics), e.g. with: `export KIVY_GL_BACKEND=sdl2` (on Linux, the default backend is `gl`)
- disable compositing at startup; this helps somewhat in the VM case, but probably not so much when running Kivy later (Hardware > Display and Monitor > Compositor)
- set your log to level `debug` in `.kivy/config.ini`, maybe there's some relevant log message that won't show with the default verbosity

In the meantime, I'll see if I can find something in the SDL2 wiki/codebase.

**Comment by dolang** [comment]
Found some things in the [SDL2 codebase](http://hg.libsdl.org/SDL/file/523e803a0192/src/video/x11/SDL_x11window.c#l561):
```C
...
} else {
    wintype_name = "_NET_WM_WINDOW_TYPE_NORMAL";
    compositor = 1;  /* disable compositing for "normal" windows */
}
...
```
If that's the problem, I'm not yet sure if there's a way to tell it that it's not a normal window. (Is that really a KWin only problem?)

Also, the code here seems to be for video playback, not sure how that ties back to creating an X11 window.

A bit further below it checks the hint `SDL_HINT_VIDEO_X11_NET_WM_BYPASS_COMPOSITOR`. Not entirely sure what that does, either, but you could try:
```bash
export SDL_VIDEO_X11_NET_WM_BYPASS_COMPOSITOR=1
```
and for good measure:
```bash
export SDL_VIDEO_X11_NET_WM_BYPASS_COMPOSITOR=0
```

Another WM manipulation by SDL2 is that it disables the screensaver by default, so that might be something else to try. However, Kivy seems to enable that by default and exposes that [setting on the Window](https://github.com/kivy/kivy/blob/master/kivy/core/window/__init__.py#L425):
```py
Window.allow_screensaver = True  # should probably try both
```
... although I haven't found where it sets that default.

As an SDL hit it would be:
```bash
export SDL_VIDEO_ALLOW_SCREENSAVER=...
```

-----

See also:
- [This wiki page about SDL2 hints](https://wiki.libsdl.org/CategoryHints) lists some but not all SDL settings that can be changed. Note especially: "*The convention for naming hints is SDL_HINT_X, **where "SDL_X" is the environment variable** that can be used to override the default.*"
- It should be possible to stop it from disabling the compositor on a per-application basis: [r/kde: How to add a KWin rule to stop disabling the compositor?](https://old.reddit.com/r/kde/comments/7sfb4p/how_to_add_a_kwin_rule_to_stop_disabling_the/)

**Comment by dolang** [comment]
If you're not afraid of grabbing the source and patching it, here's another thing you could try:
```diff
diff --git a/kivy/core/window/_window_sdl2.pyx b/kivy/core/window/_window_sdl2.pyx
index 31e0663c..f832838e 100644
--- a/kivy/core/window/_window_sdl2.pyx
+++ b/kivy/core/window/_window_sdl2.pyx
@@ -67,7 +67,7 @@ cdef class _WindowSDL2Storage:
 
     def setup_window(self, x, y, width, height, borderless, fullscreen,
                      resizable, state):
-        self.win_flags = SDL_WINDOW_OPENGL | SDL_WINDOW_SHOWN | SDL_WINDOW_ALLOW_HIGHDPI
+        self.win_flags = SDL_WINDOW_OPENGL | SDL_WINDOW_SHOWN | SDL_WINDOW_ALLOW_HIGHDPI | SDL_WINDOW_UTILITY
 
         IF USE_IOS:
             self.win_flags |= SDL_WINDOW_BORDERLESS | SDL_WINDOW_RESIZABLE | SDL_WINDOW_FULLSCREEN_DESKTOP
```
You'll need to recompile Kivy for that to work.

**Comment by dolang** [comment]
@Vencorr after reading a bit more, and if you're only going to try one thing, it should be this:
```bash
export SDL_VIDEO_X11_NET_WM_BYPASS_COMPOSITOR=0
```

**Comment by tito** [comment]
Here we are, use the env :)

**Comment by Kazun3500** [comment]
Is it possible to add information about a workaround with env variable SDL_VIDEO_X11_NET_WM_BYPASS_COMPOSITOR=0 to the problem in the documentation? Or is it already mentioned in the documentation and I just couldn't find it?

**Comment by tshirtman** [comment]
I don't think it's in the documentation, or anywhere in the codebase, and i'm not sure where it should be, can you think of where you would expect to find it? maybe in the Window class, but that's pretty specific to a platform.

**Comment by Kazun3500** [comment]
> I don't think it's in the documentation, or anywhere in the codebase, and i'm not sure where it should be, can you think of where you would expect to find it? maybe in the Window class, but that's pretty specific to a platform.

For me it is only one place where i expect to see this - https://kivy.org/doc/stable/guide/environment.html , in new section like "Not kivy environment variables". I know, that it is not ideal place for it, but github issues is worse.

code for optional enabling this env variable 
```
out = subprocess.run('qdbus org.kde.KWin /Compositor org.kde.kwin.Compositing.active'.split(' '),
                       stdout=subprocess.PIPE, stderr=subprocess.DEVNULL).stdout.decode().strip()
    if out == 'true':
        os.environ['SDL_VIDEO_X11_NET_WM_BYPASS_COMPOSITOR'] = '0'
```
