### ISSUE TITLE
sudo add-apt-repository ppa:kivy-team/kivy no longer useable

### ISSUE THREAD

**Issue by yingshaoxo** [kivy/kivy#5824]
I can't use `sudo add-apt-repository ppa:kivy-team/kivy`:

```
Err:8 http://ppa.launchpad.net/kivy-team/kivy/ubuntu bionic Release                                     
  404  Not Found [IP: 91.189.95.83 80]
```

And when directly install `sudo apt install python3-kivy`

I get ` python3-kivy amd64 1.9.1-1build3`

Which will raise an error of `https://github.com/kivy/kivy/issues/5410`

**Comment by dolang** [comment]
Yes, the stable PPA doesn't have a release for bionic currently, because v1.10.0 doesn't work on bionic.

This has been reported before, see here: https://github.com/kivy/kivy/issues/5795#issuecomment-396037899

v1.10.1 is in the process of being released and will have a package once ready. In the meantime, try using **ppa:kivy-team/kivy-daily** instead.

**Comment by maksat20021999** [comment]
HI!!!!! I did so 
sudo add-apt-repository ppa:http://ppa.launchpad.net/kivy-team/kivy/ubuntu
