### ISSUE TITLE
videoplayer gstreamer 

### ISSUE THREAD

**Issue by linpan** [kivy/kivy#5871]
whe i installation steps based on document https://kivy.org/docs/installation/installation-rpi.html, but run a video mp4, show a error :
[ERROR  ] [Image       ] Error loading texture cityCC0.mpg
 have you got a solution ?

**Comment by dannylew12** [comment]
What command are you using to run the video?

**Comment by tito** [comment]
When you use the videoplayer, it tries to load a thumbnail for the video, but this error is informative and doesn't block the player.
If your video doesn't work, it's mostly because the codec used is not working in GStreamer itself. Ensure you have the all the package for GStreamer installed, and if it work within GStreamer, it will work in Kivy
