### ISSUE TITLE
Wrong description on EventDispatcher.funbind()

### ISSUE THREAD

**Issue by gottadiveintopython** [kivy/kivy#5889]
Hi I think the description is wrong.

https://github.com/kivy/kivy/blob/master/kivy/_event.pyx#L576-L577

Actually, `EventDispatcher.unbind()` will only unbind the first. 

Edit:

```python
from kivy.factory import Factory


def callback(__):
    print('callback')


button = Factory.Button()
button.fbind('on_press', callback)
button.fbind('on_press', callback)
button.dispatch('on_press')
print('-------------------')
button.unbind(on_press=callback)
button.dispatch('on_press')
```

```
callback
callback
-------------------
callback
```

**Comment by matham** [comment]
You are right, but here is what's going on IIRC. Originally, `unbind` searched for all matches if it bound a property, while `bind` only added a bound callback if one that was equal to it didn't already exist, depending if it was an event or property. When I added `fbind` and co. I simply replicated that functionality in `EventObservers` for simple `bind`.

However, I also fixed some inconsistencies at the time, then after doing that I realized that if no duplicates are added, then unbinding all is done after finding the first :D. So the comment is technically true, but also meaningless and is just there because history.

So feel free to make a PR to remove it. Also, just a note in case you're planning you use it, the `ref` keyword will probably go away at some point if the KV proposal is merged, and instead an explicit `fbind_proxy` will be added instead.

**Comment by gottadiveintopython** [comment]
Aha! Thanks for the detailed explanation :smile: . I should have read docs of other classes(Observable, BoundCallback, EventObservers). I've only read EventDispatcher's doc. 

> So feel free to make a PR to remove it

Probabely I'm not going to make a PR for that because I don't fully understand the code.
