### ISSUE TITLE
Use build stages in Travis

### ISSUE THREAD

**Issue by dessant** [kivy/kivy#5904]
Currently wheels, docs etc. are pushed to the server despite failing parallel jobs, such as tests.

With build stages we can run the initial jobs in the first stage, and jobs which produce artifacts can be run in the second stage.

https://blog.travis-ci.com/2018-07-18-build-stages-officially-released
https://docs.travis-ci.com/user/build-stages

Switching to build stages is also a prerequisite for automated releases.

\cc @matham @KeyWeeUsr

**Comment by matham** [comment]
That's a great idea, although making sure all the tests pass consistently is a per-requisite to use this. Because right now, whether the tests pass or not, we still need to create the artifacts because tests failures are not that meaningful.

Thinking about this, though. For automated releases, we would need a way to somehow tie together the appveyor and travis tests.

**Comment by dessant** [comment]
Flaky tests are an issue, but they don't seem to be a blocker for the change. Tests could be listed in the second stage until the issue is solved. We would still benefit by stopping the build if the pep8 job fails. :rofl: 

One possible way of tying travis and appveyor together for automated releases is to wait on the server for an artifact upload or webhook call from both places.
