### ISSUE TITLE
Development builds are backed up to S3

### ISSUE THREAD

**Issue by dessant** [kivy/kivy#5915]
We need to update the list of folders that can be safely ignored during backups, after some recent changes we've started to back up folders to S3 with dev builds.

This is the current list of ignored folders:
https://github.com/kivy/kivy-server/blob/master/downloads/cont/config/exclude-backup.conf

Please take a look at https://kivy.org/downloads/ and post the directory paths that we can skip. If there are folders that are no longer used, also mention those so they can be removed.

The new `ci` folder seems to contain both dev and release builds.

/cc @KeyWeeUsr @matham @akshayaurora

**Comment by matham** [comment]
`Kivy_examples.egg-info/` can be deleted.

`downloads/ci/win/kivy/` is a symbolic link of `downloads/appveyor/kivy/`.

`packages/` was used before we could host gstreamer on pypi so that can be removed as well (we can check if anyone is still using it, but they can just use pypi anyway).

`ci` and `appveyor` contains ci builds. For every release, we move stuff from `ci` into the release folder, except for win deps (`downloads/ci/win/deps/`), those just remain in that folder. Once that is moved to its own folder (e.g. `downloads/win_deps` and similarly for other OS), we can ignore the `ci` folder on S3.
