### ISSUE TITLE
Window on_resize event fires twice with different widths

### ISSUE THREAD

**Issue by abethcrane** [kivy/kivy#6082]
### Versions

* Python: 3.7
* OS: Mac OS Mojave
* Kivy: 1.10.1
* Kivy installation method: pip

### Description

I'm subscribed to the window.on_resize event. I expect to get 1 callback per resize. Instead I get 2, one for width, one for width * 2.

width 1680
width 3360
width 785
width 1570
width 366
width 732

### Code and Logs

```python
class Example(Widget):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        Window.maximize()
        Window.bind(on_resize=self.on_window_resize)

    def on_window_resize(self, window, width, height):
        print("width", width)

class MainApp(App):
    def build(self):
        return Example()

if __name__ == '__main__':
    MainApp().run()
```

**Comment by toejough** [comment]
Same versions/os/installation-method, but on a dual monitor setup (one external, one on my laptop), and I get the double event as well, but the width stays the same.

I get the double event on maximize, as in the above example.  I also get it on manual resizing.  I get double events on both monitors.

I do *not* get a double event (I get a single event) when I drag my window from one monitor to another (resizes because of the DPI change).

**Comment by zhuchangzhan** [comment]
Same problem, could not find a solution anywhere. Once the screen is dragged to the external monitor, all my widgets get smooch together.
