### ISSUE TITLE
png  ring of death revisited

### ISSUE THREAD

**Issue by ssolari** [kivy/kivy#6100]
### Versions

* Python: 3.7.1
* OS: MacOS Mojave 10.14
* MacBook Pro (Retina, 13-inch, Early 2015)
* Intel Iris Graphics 6100 1536 MB
* Kivy: 1.10.1
* Kivy installation method: pip install into conda environment

### Description

When placing a png on a canvas a ring appears around the outside unexpectedly.   The expectation is that no ring will appear.

This issue has been discussed in the past:
https://groups.google.com/forum/#!topic/kivy-users/W2lloACEKCw

And there is a similar issue:  #4463

The above do not address the use case below where an image simply needs to be placed on a canvas that does not have a uniform background.   Maybe I did not understand the discussed solutions, but I tried exporting this white_circle.png format from Adobe illustrator in about every configuration I could think of:  PNG, PNG8, anti-aliasing options, interlace options.   The transparency option has to be enabled because the image crosses boundaries. 

### Code and Logs

```
from kivy.app import App
from kivy.lang import Builder
from kivy.uix.boxlayout import BoxLayout


Builder.load_string("""
<MainWidget>

    canvas.before:
        Color:
            rgba: 1,1,1,1
        Rectangle:
            pos: self.pos
            size: self.size
    
    Widget:
    
    Widget:
        canvas.before:
            Color:
                rgba: 0.5,0.5,0.5,1
            Rectangle:
                pos: self.pos
                size: self.size
            
            Color:
                rgba: 1,1,1,1
            Rectangle:
                source: './white_circle.png'
                pos: self.pos[0] - dp(100), self.pos[1] + dp(100)
                size: self.width + dp(200), self.width + dp(200)
            
    Widget:
            
""")


class MainWidget(BoxLayout):
    def __init__(self, **kwargs):
        super(MainWidget, self).__init__(**kwargs)


class MyApp(App):
    def build(self):
        return MainWidget()


if __name__ == '__main__' or __name__ == 'android':
    MyApp().run()

```

### Screen shot
<img width="999" alt="screen shot 2019-01-15 at 11 43 27 am" src="https://user-images.githubusercontent.com/1182784/51205465-d6e7a600-18ba-11e9-8ab5-ab4c1881c230.png">

### white_circle.png
![white_circle](https://user-images.githubusercontent.com/1182784/51205373-a0119000-18ba-11e9-9bc4-a3155b476a56.png)

**Comment by tshirtman** [comment]
I remember having issues with images exported from illustrator, when a certain option was set, it was something like anti-aliasing or oversampling optimisation (for text). If you have the vector, can you check exporting again *without* this option activated?

**Comment by tshirtman** [comment]
If i test your example and put the rectangle size at 601, 601, the circle disappears, so it is an issue with scaling the texture.

**Comment by ssolari** [comment]
@tshirtman first, cool gist with the sliding image dependent on time ... second, I can confirm that I do see that the grey circle disappears in the second layout in your gist.   Q: Why does the int() around the pos[0] argument fix the issue?   Both images are sized at 601,601, but the int on the position seems to be what makes the circle disappear.  

I can confirm that the 'anti-aliasing' option needs to be set to "None" for your gist to work.   If the anti-aliasing option is not None for either PNG or PNG8 a circle is seen around both images in the gist. 

@akshayaurora yes, on a mac retina.   I did see that comment.   I guess I could not figure out what ```On the RGB layer, extend the "white" outside the circle``` actually means.   Maybe a better description might help me and others. 

I definitely feel the right solution is to fix the image at the source in this case.   I just can not figure out what that means.    In order for the image to be the right size on different screens we have to scale the image, preferably by setting the size with a metric like ```size: dp(200), dp(200)```.  I don't see a way around that or are there other ways?

**Comment by ssolari** [comment]
Using .svg files removes issues with scaling, however the Svg module has deprecation warnings.   Is there any thought to find a way to support svgs more robustly?

**Comment by tshirtman** [comment]
i'd need to be sure about why the circle get there in the first place to answer why it disappears, but my understanding is that channel computation is broken when an image's pixel is not exactly mapped to a screen pixel, (either because the image is scaled, so a pixel of it covers or less than the area of a screen's pixel), or because the coordinates are not integers, so the pixel is simply offset to the screen's pixel. making sure size is the exact size of the image and coordinates are integer avoids both of these issues, assuming that the window itself is not scaled (for example to adjust to a highdpi screen, i didn't test that).

Hm, just opened the image in gimp and it's in indexed colors, but if i do
1/ image -> mode -> rgba
2/ colors -> composants > separate
3/ now do ctrl-a, then ctrl-drag around the "k" to select it out
4/ for each color layer in the layer, select it then press "delete" on the keyboard, you should see the black part around the circle disappear in the preview of the layer. only do this for colors, not for the alpha channel.
5/ colors -> composants > compose
6/ save the new file and make the example code edit it (here is a copy of the file for me) 
![white_circle3](https://user-images.githubusercontent.com/22759/51233834-4321e280-196b-11e9-9918-e8a00193464c.png)

What we did is overdraw the color channels under the alpha one, so computation errors don't matter, if the alpha channel says there should be color, then we always have a color at that position, no chance of getting an "empty" pixel mixed in, of course, this is not as easy to do for more complex images, so it's better to fix it before, or to find a way to avoid that in kivy (if possible).

The svg module is not deprecated afaik, it's more experimental, meaning it doesn't support all the svg features (i fixed some things, but some others are *hard* ^^'), and it's slower than we wish it was (and certainly slower than what a modern browser does), but it works nicely for a lot of cases, can you share the warnings you got?

**Comment by ssolari** [comment]
thanks for all the effort

Trying to add the following widget:
```
class SvgWidget(Scatter):

    def __init__(self, filename):
        super(SvgWidget, self).__init__()
        with self.canvas:
            svg = Svg(filename)

        self.size = svg.width, svg.height
```

I get:
```DeprecationWarning: This method will be removed in future versions.  Use 'list(elem)' or iteration over elem instead.
   svg = Svg(filename)
```

seems like there may be another new svg issue #6101 (not sure if it is related), but probably better to handle svg discussion in that issue to keep this one focused.

**Comment by tshirtman** [comment]
Ah, the deprecation certainly comes from some usage of some method from the elementree package of python to parse the xml, no worries, it can be fixed before it goes away.

this example shipped with kivy's examples seems to be exactly what you are asking.
https://github.com/kivy/kivy/blob/master/examples/svg/main.py

**Comment by ssolari** [comment]
thanks!   

If I am not mistaken, it seems as though the png isssue: 
  * preventing an outline in parts of the png when scaling the image

is not going to be solved by kivy ?  if that's the case I'm ok closing the issue.

**Comment by tshirtman** [comment]
It's unlikely to be solved us any time soon, i'm fine with leaving it open for reference, but if you (or anyone) wants to investigate and find a proper fix, that would be awesome :).

**Comment by tito** [comment]
@ssolari "Preventing an outline in parts of the PNG when scaling the image" - we cannot do magic everywhere for everything! :)

As explained before, the RGB part when the A is black (aka transparent) have a wrong color. You must put white color if you want to have good antialiasing. I don't know how others toolkit are "fixing" theses kind of issues. When you make transparent images: make sure the RGB part always cover the whole image with a consistent color (aka if you do a circle, you shouldn't see a black/white circle in RGB). Only Alpha should have black/white that create the circle shape.

IMO, it is not revisited, it's the same as explained on previous posts :)
