### ISSUE TITLE
Kivy input not working after 5 days usage; Permission denied: '/dev/input/event0'

### ISSUE THREAD

**Issue by albertz** [kivy/kivy#6141]
### Versions

* Python: 3.5.3
* OS: Raspbian, Debian 9.4
* Kivy: 1.10.1
* Kivy installation method: pip install

### Description

After about 5 days of runtime, suddenly Kivy did not accept any input anymore, and I was getting `/dev/input/event0` permission errors on stdout.

### Code and Logs

Maybe relevant is that it runs on a Raspberry Pi, and the input is a touchscreen.
Maybe also relevant: Via #3640, I followed the advice to use this in my `~/.kivy/config.ini`:
```
[input]
mouse = mouse
%(name)s = probesysfs,provider=hidinput
mtdev_%(name)s = probesysfs,provider=mtdev
hid_%(name)s = probesysfs,provider=hidinput
```

Then [my app](https://github.com/rwth-i6/drink-kiosk) works fine.
It ran fine for 5 days now, until I suddenly got this on stdout:
```
 Exception in thread Thread-107:
 Traceback (most recent call last):
   File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
     self.run()
   File "/usr/lib/python3.5/threading.py", line 862, in run
     self._target(*self._args, **self._kwargs)
   File "/home/zeyer/.local/lib/python3.5/site-packages/kivy/input/providers/hidinput.py", line 685, in _thread_run
     data = fd.read(struct_input_event_sz)
  OSError: [Errno 19] No such device

 Exception in thread Thread-108:
 Traceback (most recent call last):
   File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
     self.run()
   File "/usr/lib/python3.5/threading.py", line 862, in run
     self._target(*self._args, **self._kwargs)
   File "/home/zeyer/.local/lib/python3.5/site-packages/kivy/input/providers/mtdev.py", line 290, in _thread_run
     _device = Device(_fn)
   File "/home/zeyer/.local/lib/python3.5/site-packages/kivy/lib/mtdev.py", line 143, in __init__
     self._fd = os.open(filename, os.O_NONBLOCK | os.O_RDONLY)
  PermissionError: [Errno 13] Permission denied: '/dev/input/event0'
```

After I quit the app, and just restarted it, it is all fine again. But I guess probably the problem will again appear after some days of usage. I guess this is maybe some leak, maybe of file-descriptors, or so. E.g. what makes me also curious in that output is the high thread number (`Thread-108`).

**Comment by tito** [comment]
If your doing some POS, it might always be best to do a reboot to prevent any long term memory issues. Can be us, can be the underlaying libs too.

**Comment by albertz** [comment]
What is POS? You are suggesting a full reboot, or just a restart of the app?
You are right, this could also be some buggy lib. But it would be good to debug this somehow, to understand what's happening here.

**Comment by tito** [comment]
Just restarting the app is enough. And you're right, maybe we're leaking FD and that's why you hit the permission issue.

I double checked our code, there is only one thread started per hidinput, they are never recreated if they are crashing, and there is no entrypoint in the code to recreate them except if you call EventLoop.start() again.

But your log output indicate `Thread-108` which is a very high number. I'll bet it's not our code. I checked your project, and you're doing many weird things ^^ The only one that triggered me was that `init_ipython_kernel`. If you ipython reload anything, maybe then you get your behavior.

If you can give us a reproducible pure kivy example, then i'll accept the issue, otherwise it's a wontfix.
