### ISSUE TITLE
TypeError: descriptor 'property' requires a 'kivy._event.EventDispatcher' object but received a 'method_descriptor'

### ISSUE THREAD

**Issue by PtmDex** [kivy/kivy#6158]
I am building an android app using kivy and buildozer. App crashes on start and I found this TypeError. So iget the logs using logcat and so this error after some lines from traceback. I'm using Kivy 1.9.0 and Python 2.7.9 Is there a way to fix this ? Please tell me how to fix this one. Thank you. T_T

`TypeError: descriptor 'property' requires a 'kivy._event.EventDispatcher' object but received a 'method_descriptor'`

main.py, main.kv, log(from logcat), buildozer.spec
[mycodes.zip](https://github.com/kivy/kivy/files/2856367/mycodes.zip)

Thank you so much for your time T_T

**Comment by tito** [comment]
There is multiple issue with your code, like starting a Thread that change the text of widget. This is forbidden to change the state of Widget that may have an impact of OpenGL then crash.
This is not the crash you have, but unless you have a reproducible code, this issue came from your app.

Aka somewhere you set a method instead of a value (int/str/etc)
