### ISSUE TITLE
No way to specify parameters to KIVY_VIDEO provider

### ISSUE THREAD

**Issue by brentpicasso** [kivy/kivy#6171]
We have a case where we're using ffpyplayer, and we want to ensure it uses a specific hardware decoder vs choosing the default h264 software decoder. 

What's the best way to parameterize this information?  Should this be an issue on ffpyplayer instead?

**Comment by brentpicasso** [comment]
Related ffpyplayer issue: https://github.com/matham/ffpyplayer/issues/60

**Comment by tito** [comment]
I think it's too specific. I'm not against a patch that pass some information from the env to the providers, but even if we would have a way, we need to know what exactly we want to pass.
You showed what you wanted in the related issue, therefore if you provide a patch for that, i'll be happy to merge.

So easier is to have env variable working on ffpyplayer project itself IMO.
Or provide a way to parse argument in KIVY_VIDEO, and then use it to map some argument to the ffpyplayer implementation.

**Comment by matham** [comment]
An environmental variable is not appropriate for ffpyplayer because the `vcodec` is passed into init. It would be like adding an environmental variable to control the number of rows in a grid layout.

A more appropriate solution would be to have a config options duct on the video class which each backend provider can use as needed. Then ffpyplayer can use it for the `vcodec` parameter. What do you think @tito? It should be easy to add!?

**Comment by brentpicasso** [comment]
I think that's reasonable - the config options dict would be specific to the provider, and that would be OK considering the provider is likely to be specified as well.
