### ISSUE TITLE
settings `mouse,disable_multitouch` in settings is causing bug on touch on Android

### ISSUE THREAD

**Issue by goffi-contrib** [kivy/kivy#6229]
### Versions

* Python: 2.7.15
* OS: Arch Linux on desktop, Android 6.0 on mobile
* Kivy: master (rev. 44a8a6f)
* Kivy installation method: git + pip on desktop, p4a on Android

### Description

After disabling multi-touch emulation in my app with the following line:
```python
Config.set('input', 'mouse', 'mouse,disable_multitouch')
```
the touch event on buttons (using `on_release`method) is called twice on Android, while it's working fine on desktop

### Code and Logs

Following code should reproduce the issue, it is manual testing. Just click once on the button. On desktop it should call `on_release` only once, while on Andorid it's calling it twice.

```python
from kivy.config import Config
Config.set('kivy', 'log_level', 'debug')
Config.set('input', 'mouse', 'mouse,disable_multitouch')

from kivy.app import App
from kivy.lang import Builder
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.button import Button
import sys

kv = """
<Test>:
    BoxLayout:
        id: box
        orientation: 'vertical'
        TestButton:
            text: 'Touch/Click me'
"""



class Test(BoxLayout):
    pass


class TestButton(Button):
    release_count = 0

    def on_release(self, *args):
        self.release_count += 1
        print("on_release clicked (count: {})".format(self.release_count))
        if self.release_count > 1:
            print("release_count has been called more than once")
            sys.exit(1)


class TestApp(App):
    def build(self):
        return Test()


if __name__ == '__main__':
    Builder.load_string(kv)
    TestApp().run()
```

**Comment by tshirtman** [comment]
I'm not sure whether to consider this a bug or not.
Kivy supports multiple input provider, mouse makes sense on desktop, but much less on android, unless you consider people using a real mouse on it (which is possible), if you allow that, by setting setting the mouse input like in this example, then you'll get double touches when the user touches the screen, because you get the same event by two different means, one from the mouse simulation from android, and once from the normal touch event. Kivy has no foolproof way to know they are the same thing, as they are really given separately by the system. The solution usually is not to enable mouse on android, but it could be an issue for users that actually have this use case (although this is not a common case, it exists). Alternatively, trying to deduplicate touches at app level is possible, but not perfect (i did that with touch tables on windows), you have to keep track of all the touches, and check any new touch for proximity (in time and distance) with another touch, and ignore it if it's a match, there is a small risk of ignoring a legitimate touch, and a difficulty with fast moving touches, that are harder to match against their duplicate, but it can be better than nothing.

**Comment by akshayaurora** [comment]
`disable_multitouch` Is for disabling the emulation of multi touch hardware, not the actual hardware...

doesn't the default app settings work with mouse and touch? Why would you need to add mouse explicitly on android?

In my experience Kivy and other apps work as expected with a external mouse, without the need to change these settings on android.

**Comment by goffi-contrib** [comment]
Hello,

I don't need to do that on Android, I've just done that for Desktop and the same app is running on Android/Desktop so I run through this behavior. I now only set `disable_multitouch` on Desktop and it's working fine.

I've talked about that on the chat channel, and somebody (@tshirtman IIRC) told me to open a ticket here, because he was not sure if it was a ticket or not, so feel free to close if it's fine for you :).
