### ISSUE TITLE
Nesting a widget an even number of times makes its text dimmed

### ISSUE THREAD

**Issue by IfElifElse** [kivy/kivy#6332]
### Versions

* Python: 3.6
* OS: Windows 10
* Kivy: 10.0.1
* Kivy installation method: pip3

### Description

I am running into an unexpected behavior adding labels to layouts. When I add a label to a layout nested into `n` other layouts, if `n` is even, the label's text is dimmed. Here's what I mean by dimmed:

when `n` is 5:
![image](https://user-images.githubusercontent.com/13923183/58354531-c1bded80-7e3f-11e9-8824-65485dd49571.png)

when `n` is 6:
![image](https://user-images.githubusercontent.com/13923183/58354557-d9957180-7e3f-11e9-92fb-f25f0698d4bd.png)

### Code and Logs

Here is the code I am using to generate the above images and exhibit my issue.

```python
import kivy
kivy.require("1.10.1")

from kivy.app import App
from kivy.uix.label import Label
from kivy.uix.stacklayout import StackLayout
from kivy.uix.floatlayout import FloatLayout


class MyApp(App):

    def build(self):
        layouts = []
        nest = 6 # with nest equal to 6, the Label's text is dimmed.
        # if nest were equal to 5, the Label's text would not be dimmed.
        for _ in range(nest):
            innerLayout = StackLayout()
            if len(layouts) != 0:
                layouts[-1].add_widget(innerLayout)
            layouts.append(innerLayout)

        layouts[-1].add_widget(Label(text="Hello, world"))
        return layouts[0]


if __name__ == '__main__':
    MyApp().run()
```

**Comment by matham** [comment]
Can you check that it's not because of
https://github.com/kivy/kivy/issues/6318?

**Comment by matham** [comment]
I made a new kivy candidate release that hopefully resolves the issues and uploaded it to pypi. I also made new wheels for kivy dependencies. Given the existing issues with the binary dependencies I also took the opportunity to migrate our dependencies from `kivy.deps.xxx` to `kivy_deps.xxx`. So, I'd ask that you try the new wheels in a new clean virtual environment so there's no clash with previous kivy dependencies and see if you still face any issues.

Here's complete instructions.

```sh
python -m pip install --upgrade pip setuptools wheel virtualenv
python -m virtualenv kivy_venv
```
If you're in windows cmd shell do:
```sh
kivy_venv\Scripts\activate
```
otherwise do:
```sh
source kivy_venv/Scripts/activate
```
Next do (note that to install the new kivy rc2 you need to add `--pre` to pip):
```sh
pip install kivy_deps.glew kivy_deps.sdl2 kivy_deps.gstreamer kivy kivy_examples --pre
python kivy_venv/share/kivy-examples/demo/kivycatalog/main.py
```

Or any other tests and let me know if you run into any issues.

**Comment by IfElifElse** [comment]
Hey, thank you for helping me out. From a [stackoverflow post](https://stackoverflow.com/questions/56174045/kivy-widgets-have-almost-unreadable-text) I was told to roll back the sdl2 version slightly, and that ended up working fine for me.
