### ISSUE TITLE
Python stop working 0xC0000005 in PyCharm

### ISSUE THREAD

**Issue by Bodzio122333** [kivy/kivy#6337]
* Python:3.6.8 64-bit
* OS:Windows 10 64-bit
* Kivy:v 1.10.1
* Kivy installation method: 
https://kivy.org/doc/stable/installation/installation-windows.html
![image](https://user-images.githubusercontent.com/21276867/58478410-541f0380-8156-11e9-98a2-876e34f9310b.png)

### Description
I try use kivy but after instalation I see this error. 
I try on PyCharm and default IDE. In PyCharm i see :Process finished with exit code -1073741819 (0xC0000005) but in IDE python.exe stop working.
![image](https://user-images.githubusercontent.com/21276867/58478383-3d78ac80-8156-11e9-8c16-f35ad0ab2a3f.png)

### Code and Logs
from kivy.app import App
from kivy.uix.button import Button

class TestApp(App):
    def build(self):
        return Button(text='Hello World')

TestApp().run()

**Comment by matham** [comment]
I made a new kivy candidate release that hopefully resolves the issues and uploaded it to pypi. I also made new wheels for kivy dependencies. Given the existing issues with the binary dependencies I also took the opportunity to migrate our dependencies from `kivy.deps.xxx` to `kivy_deps.xxx`. So, I'd ask that you try the new wheels in a new clean virtual environment so there's no clash with previous kivy dependencies and see if you still face any issues.

Here's complete instructions.

```sh
python -m pip install --upgrade pip setuptools wheel virtualenv
python -m virtualenv kivy_venv
```
If you're in windows cmd shell do:
```sh
kivy_venv\Scripts\activate
```
otherwise do:
```sh
source kivy_venv/Scripts/activate
```
Next do (note that to install the new kivy rc2 you need to add `--pre` to pip):
```sh
pip install kivy_deps.glew kivy_deps.sdl2 kivy_deps.gstreamer kivy kivy_examples --pre
python kivy_venv/share/kivy-examples/demo/kivycatalog/main.py
```

Or any other tests and let me know if you run into any issues.

**Comment by Bodzio122333** [comment]
Hi Matham, Thanks for you help but i still have the same issues:

[console.txt](https://github.com/kivy/kivy/files/3235798/console.txt)
[kivy_19-05-30_0.txt](https://github.com/kivy/kivy/files/3235806/kivy_19-05-30_0.txt)

**Comment by matham** [comment]
Ok, the log you attached doesn't show any problem and it doesn't seem like you ran `python kivy_venv/share/kivy-examples/demo/kivycatalog/main.py`. Can you run it from the virtual environment? To activate it again do `kivy_venv\Scripts\activate`.

**Comment by Bodzio122333** [comment]
![image](https://user-images.githubusercontent.com/21276867/58779154-4560a280-85d5-11e9-9a3f-2dbafc490213.png)

**Comment by matham** [comment]
I don't understand. What is the issue? I don't see a crash or error in the screenshot.

**Comment by Bodzio122333** [comment]
I don't see any window after run this script.  The kivy-examples not start.

**Comment by matham** [comment]
Sorry, but this seems to be something specific to your system, rather than with kivy. You can try to compile kivy yourself, or ask on discord for further help.
