### ISSUE TITLE
Documentation needed: "id" will be removed in next release

### ISSUE THREAD

**Issue by 20Tauri** [kivy/kivy#6363]
"id" on FloatLayout is now deprecated.
```
Deprecated property "<StringProperty name=id>" of object "<FloatLayout>"
has been set, it will be removed in a future version
```

When a layout is created from kv language, what's the official way to get a reference to it ?

I haven't found an explanation why this will been removed (and I'm interested in). Is there  somewhere a discussion about this ?

**Comment by gottadiveintopython** [comment]
`id` in kv and `id`(the deprecated one) are completely different. So you don't have to worry about that.

**Comment by gottadiveintopython** [comment]
`id` in kv and `id`(the deprecated one) are different thing.

So you don't have to worry about:
> When a layout is created from kv language, what's the official way to get a reference to it ?

**Comment by 20Tauri** [comment]
Thanks, it was unclear...
The warning only occured when `id` if set from code (and it's easy to keep a reference in this case)

Until know I thought that
```
        self.ids["name"].id == "name"
```

**Comment by chavarinbonbyn** [comment]
If that widget property is getting deprecated, which is the correct way of identifying a widget when creating it from python code directly ? For example, when creating an unknown number of buttons with a for loop, but you need to keep track of them somehow. That was very easy with the widget id (in python code)

**Comment by 20Tauri** [comment]
I don't know a build in solution in kivy (will be a great enhancement to add this info directly on warning).
To found the affected code, I have overload FloatLayout.__setattr__ / FloatLayout.__getattr__. When called with the attribute name "id"  I log both "value" (the widget id) and stack trace.

**Comment by matham** [comment]
>which is the correct way of identifying a widget when creating it from python code directly ?

There's no kivy special solution because this is not a kivy specific problem. You can keep track of the widgets like you would track a list of any python objects.

**Comment by clickworkorange** [comment]
I get this warning because I'm feeding a RecycleView with a list of dicts where each dict has an "id" attribute in order to keep track of which dict belongs to which RFID tag (by means of an attached label). Each one has a "name" as well, but this can change, and the RFID tag EPCs are much too long to efficiently compare with a print-out; "23" is a lot easier to find in a pile of loose tags than "300ED89F335000400182129B" - and it also uses less of the expensive marking tape ;) So _sometimes_ an "id" attribute still makes sense, though I guess I could just call it something else...
