### ISSUE TITLE
Unable to get a text provider for simple Kivy app.

### ISSUE THREAD

**Issue by AMDphreak** [kivy/kivy#6465]
### Versions

* Python: 3.7.4
* OS: Windows 10 Version 10.0.18362 Build 18362
* Kivy: 1.11.1
* Kivy installation method: pip

### Description

Installed Kivy with `pip install kivy`.
Followed the quickstart [tutorial](https://kivy.org/doc/stable/guide/basic.html#quickstart) to create an app. The example app generates errors.

### Code and Logs
`>python PongGame.py`

Output
```[INFO   ] [Logger      ] Record log in C:\Users\rjamd\.kivy\logs\kivy_19-08-11_1.txt
[INFO   ] [Kivy        ] v1.11.1
[INFO   ] [Kivy        ] Installed at "C:\Users\rjamd\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 19:29:22) [MSC v.1916 32 bit (Intel)]
[INFO   ] [Python      ] Interpreter at "C:\Users\rjamd\AppData\Local\Programs\Python\Python37-32\python.exe"
[INFO   ] [Factory     ] 184 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif (img_sdl2, img_pil, img_ffpyplayer ignored)
[CRITICAL] [Text        ] Unable to find any valuable Text provider. Please enable debug logging (e.g. add -d if running from the command line, or change the log level in the config) and re-run your app to identify potential causes
sdl2 - ImportError: DLL load failed: The specified module could not be found.
  File "C:\Users\rjamd\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kivy\core\__init__.py", line 63, in core_select_lib
    fromlist=[modulename], level=0)
  File "C:\Users\rjamd\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kivy\core\text\text_sdl2.py", line 13, in <module>
    from kivy.core.text._text_sdl2 import (_SurfaceContainer, _get_extents,

pil - ModuleNotFoundError: No module named 'PIL'
  File "C:\Users\rjamd\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kivy\core\__init__.py", line 63, in core_select_lib
    fromlist=[modulename], level=0)
  File "C:\Users\rjamd\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kivy\core\text\text_pil.py", line 7, in <module>
    from PIL import Image, ImageFont, ImageDraw

[CRITICAL] [App         ] Unable to get a Text provider, abort.
```

### Copy of my example app

```
#Pong Game Tutorial
import kivy
kivy.require('1.11.1')
from kivy.app import App
from kivy.uix.label import Label

class MyApp(App):
    def build(self):
        return Label(text='Hello world')
if __name__ == '__main__':
    MyApp().run()
```

**Comment by AMDphreak** [comment]
And before anyone says it, this is not a support issue. This is a bug. If I can install Kivy with `pip`, it should immediately work.

1. The Kivy error message is *not* helpful in the slightest in telling the user what they need to do. It also does not even direct the user to the Installation tutorial. (How quaint. If it requires lengthy installation instructions, there's already something wrong with it).
2. If a user has to `pip install --upgrade pip wheel setuptools virtualenv` to make Kivy work, then there is something wrong with Kivy's dependency management. `pip` has dependency management, so it should be used.

**Comment by matham** [comment]
You didn't follow the installation instructions, hence the error.

Ideal
-----
You are right that we could a simpler install process, ideally it'd just be `pip install kivy`, but that is not the current state of python packaging and there is not a lot we could really do about given the complexity of our dependencies and the different OS we support.

Python packaging
-------------------
Specifically, we cannot list `kivy_deps.xxx` in our pip dependencies because it's only a dependency on windows. In addition, because we allow users to select between different backend providers, even on windows they are not hard dependencies. E.g. for text, we can use either `PIL` or `sdl2` and for video `gstreamer` or `ffpyplayer`.

Ideally, we'd be able to list all our deps and tell pip, one of these must be installed, with some kind of preference order. E.g. either PIL or `kivy_deps.sdl2` must be installed, but `kivy_deps.sdl2` is preferred. But pip doesn't support such things. Furthermore, some are completely optional, like `kivy_deps.gstreamer`, and again would only be needed on windows.

We could just list everything in our dependencies, but `kivy_deps.gstreamer` > 100MB and users may have reasons for installing only specific backend providers, and as I said, these dpendecies only exist for windows and as far as I know pip doesn't have a way to state that.

Potential changes
------------------
What we could do, is add optional pip install configs so you'd do e.g. `pip install kivy[basic/full-win]` or whatever. But no one has had the time to investigate if this will work/be useful.

>Users should not have to pip install --upgrade pip wheel setuptools virtualenv to make Kivy work.

They don't need to. This is to help our users install `virtualenv` so they can run kivy in a virtualenv. In addition, we recommend updating to the latest `pip` and `wheel` because if users have very old versions, sometimes pip is unable to install wheels or has other bugs. So we tell everyone to update to prevent issues. Often we have users that are completely new to python so we try to help them get things working or avoid potential issues they may not know how to navigate around.

>The error message is not helpful. Nor does it link to the Installation tutorial.

There are many reasons why a user may get that error and it's different on different OSs. Yes we can explicitly link to the install page (PR welcome), but it's probably better at that point to search google and ask on discord because the assumption is that people followed the install instructions already so if they have the error something more is going on.

>how quaint

This is not appreciated, and was not necessary.
