### ISSUE TITLE
Remove widget remains on parent

### ISSUE THREAD

**Issue by nosuchip** [kivy/kivy#6483]
### Versions

* Python: 3.7.2
* OS: Arch Linux x64
* Kivy: 1.11.1
* Kivy installation method: `pip install kivy` into virtualenv

### Description

Create a parent, on right mouse click adding child, on middle mouse click on child - remove it from parent.

Expected: child disappeared from parent and from `children` collection.
Actual: child disappeared from `children` collection but remains visible and fronzen on parent.

### Code and Logs

```python
from kivy.app import App
from kivy.uix.widget import Widget
from kivy.config import Config
from kivy.lang import Builder
from kivy.uix.behaviors import DragBehavior
from kivy.uix.relativelayout import RelativeLayout


Config.set('input', 'mouse', 'mouse,disable_multitouch')


Builder.load_string(f'''
<Node@RelativeLayout>:
    drag_rectangle: self.x, self.y, self.width, self.height
    drag_timeout: 10000000
    drag_distance: 10

    canvas.before:
        Color:
            rgba: self.bcolor
        RoundedRectangle:
            pos: 0, 0
            size: self.size
            radius: [10,]
''')


class Node(DragBehavior, RelativeLayout):
    def __init__(self, **kwargs):
        self.bcolor = (0, 0, 1, 1)
        super(Node, self).__init__(size=(100, 100), **kwargs)

    def placement_pos(self, x, y):
        return (x - self.node_width() / 2, y - self.node_height() / 2)


Builder.load_string(f'''
<GrapherUI@Widget>:
    canvas.before:
        Color:
            rgba: {.5, 1, .5, 1}
        Rectangle:
            pos: self.pos
            size: self.size
''')


class GrapherUI(Widget):
    def __init__(self, graph=None, **kwargs):
        super(GrapherUI, self).__init__(**kwargs)

    def on_touch_down(self, touch):
        touched_children = [x for x in self.walk(restrict=True) if x is not self and x.collide_point(*touch.pos)]

        has_touched_children = any(touched_children)

        if touch.button == 'right':
            if not has_touched_children:
                self.add_node(touch)
        elif touch.button == 'middle':
            self.remove_node(touched_children, touch)

        super(GrapherUI, self).on_touch_down(touch)

    def add_node(self, touch):
        print('add node')
        with self.canvas:
            node = Node(pos=(touch.x, touch.y))
            self.add_widget(node)

    def remove_node(self, touched_children, touch):
        for node in touched_children:
            print('remove node')
            self.remove_widget(node)


class Main(App):
    def build(self):
        return GrapherUI()


if __name__ == '__main__':
    Main().run()
```

**Comment by nosuchip** [comment]
@matham could you explain why did you marked it as support request? According to documentation this case should work but it doesn't that clearly shows a bug. If you need additional logs - let me know. I believe it is bug in current version of Kivy.

**Comment by matham** [comment]
The main reason is that your example code is complex enough so that it is not a minimum runnable example showing that it is a bug in *kivy*, but rather likely it is an issue in the way you use it.

And I'm fairly confident that the add/remove widget in kivy is working appropriately as that is probably the single most used function in kivy. So this suggests that it's likely a bug in your code, and hence you're much more likely to get help on the channels listed where there are people likely willing to look at your code and help debug it.

If after people looking at it you/they can pinpoint the *exact* bug in kivy, then you can open a issue here with the smallest code showing the bug.

If I were to leave it open here, it would probably be a long while before anyone looks at this issue and that won't be very helpful to you.
