### ISSUE TITLE
Adding Line(circle) to InstructionGroup causes segfault

### ISSUE THREAD

**Issue by abstractdonut** [kivy/kivy#6499]
### Versions

* Python: 2.7.15+, 3.6.8
* OS: Ubuntu
* Kivy: 1.11.1
* Kivy installation method: pip install kivy, pip3 install kivy

### Description

I am writing a program that draws some lines and circles to the screen by creating individual InstructionGroup objects, adding Line instructions to each group object, then adding those group objects to self.canvas. Calling self.groups[0].add( Line(circle=(self.p1[0], self.p1[1], 10)) ) in my class Lines(FloatLayout) (line 97) causes a segfault. I'm assuming the crash is caused by me using the API incorrectly, but am posting this error here since the kivy documentation (v 1.11.0.dev0, section 5.4, pg. 28) requests users to submit a bug report when encountering a segfault.

### Code and Logs

https://gist.github.com/abstractdonut/5598da22f54f574af1f61036bb728004

There is only main.py, and the addition of a trivial lines.kv file does not alter the outcome or prevent the crash. main.py imports print from future in order to run on python2 and 3. The code crashes python in both cases.

```

**Comment by matham** [comment]
It's because you're missing `super().__init__(**kwargs)` in `__init__`. 

You need to have a window before you do any canvas operations, and calling super for any widget ensures there's a window present. If you want to do canvas stuff before that, you'd need to call `EventLoop.ensure_window()` from `kivy.base`.

(also you have a division by zero issue in the extend function)

**Comment by abstractdonut** [comment]
Oh wow, how did I forget to call super?

Thank you.
