### ISSUE TITLE
Windows: Program gets flooded by on_touch_move events even when there's no movement

### ISSUE THREAD

**Issue by dogtopus** [kivy/kivy#6664]
### Versions

* Python: 3.8.0
* OS: Windows 10 1903
* Kivy: 2.0.0-g39f3baf
* Kivy installation method: pip self build

### Description

Not sure if this is intended (as per my intuition probably not) but I noticed that kivy floods the widget with on_touch_move events more than 800 times/second (!) when the finger stay still on screen and there is absolutely no movement.

Currently I workaround this by swallowing the event as soon as the program found out that the event is redundant (i.e. no movement at all).

### Code and Logs

```python
from kivy.uix.widget import Widget
from kivy.app import runTouchApp

class TestWidget(Widget):
    def on_touch_down(self, touch):
        if self.collide_point(*touch.pos):
            touch.grab(self)
        super().on_touch_down(touch)

    def on_touch_up(self, touch):
        if touch.grab_current is self:
            touch.ungrab(self)
        super().on_touch_up(touch)

    def on_touch_move(self, touch):
        was_us = touch.grab_current is self
        is_us = self.collide_point(*touch.pos)
        if was_us and not is_us:
            touch.ungrab(self)
        elif not was_us and is_us:
            touch.grab(self)
        super().on_touch_move(touch)

if __name__ == '__main__':
    runTouchApp(TestWidget())
```
Press and hold anywhere inside the window using a touch screen and the CPU usage shoots up instantly. Profiling the app reveals that `TestWidget.on_touch_move()` gets called very frequently even though there's little to no movement at all.

**Comment by pythonic64** [comment]
You're grabbing touch in `on_touch_move` method which will make `on_touch_move` to be called twice for the same grabbed touch, once because of grab in `on_touch_down` and again because of `on_touch_move`. As your condition for ungrab in `on_touch_move` is never `True`, `on_touch_move` will keep grabbing the same touch event every time movement, `touch.grab_list` will grow linearly by 1 for every `on_touch_move` call and overtime your CPU usage will increase. 

Usually you don't grab events in `on_touch_move`, but in `on_touch_down` and ungrab in `on_touch_up`. In `on_touch_move` you have to test if the touch is the same one you grabbed in `on_touch_down`, with `if touch.grab_current is self`, and then do your logic. All `on_touch_xxx` methods should return `True` to indicate that touch is handled and no further dispatching of event is needed, but if touch is not handled due to some conditions then `False` is returned so that other widgets can try to handle it.

Grabbing of touch events: https://kivy.org/doc/stable/guide/inputs.html#grabbing-touch-events

**Comment by dogtopus** [comment]
> You're grabbing touch in `on_touch_move` method which will make `on_touch_move` to be called twice for the same grabbed touch, once because of grab in `on_touch_down` and again because of `on_touch_move`. As your condition for ungrab in `on_touch_move` is never `True`, `on_touch_move` will keep grabbing the same touch event every time movement, `touch.grab_list` will grow linearly by 1 for every `on_touch_move` call and overtime your CPU usage will increase.
> 
> Usually you don't grab events in `on_touch_move`, but in `on_touch_down` and ungrab in `on_touch_up`. In `on_touch_move` you have to test if the touch is the same one you grabbed in `on_touch_down`, with `if touch.grab_current is self`, and then do your logic. All `on_touch_xxx` methods should return `True` to indicate that touch is handled and no further dispatching of event is needed, but if touch is not handled due to some conditions then `False` is returned so that other widgets can try to handle it.
> 
> Grabbing of touch events: https://kivy.org/doc/stable/guide/inputs.html#grabbing-touch-events

I am aware that the `on_touch_*` needs to return `True` for the event to stop propagating. However I was using a set of widgets as bounding boxes for touch events and I would like my touch points to follow the finger instead of locking on a specific widget. Therefore it's mostly impossible for me to handle the touch events before it gets propagated through the whole widget set. Any specific suggesstions for situations like this?

**Comment by pythonic64** [comment]
Cannot help you without more details and runnable example which shows the problem. You should try using the support channels on Kivy Discord https://discord.com/invite/eT3cuQp as your problem doesn't seem like a bug in Kivy.
