### ISSUE TITLE
on_touch_up calls a callback twice

### ISSUE THREAD

**Issue by Xeizzeth** [kivy/kivy#6698]
Basically if you have a button in kv file that contains this:
```
    Button:
        id: f_but
        on_touch_down: root.check_status(f_but)
```
And if you have the callback like this:
```
    def check_status(self, btn):
        word = "word"
        btn = Button(text=str(word), width=40 + len(word) * 5, size_hint=(None, 0.15))
        self.ids.text_layout.add_widget(btn)
```
Then you can observe that it is being called twice on a single click.
Is it intentional?

**Comment by matham** [comment]
Briefly, the answer is yes, it is expected. That's why you need to use `collide_point` to check to make sure the touch was meant for this widget and then it returns True so it's not propagated further.

It's generally not a good idea to handle a touch from kv, unless you understand how the touch is propagated among widgets and are ok with the implications of using it from kv.
