### ISSUE TITLE
[Feature Request] New Layout

### ISSUE THREAD

**Issue by Svaught598** [kivy/kivy#6722]
When using the KV lang to style apps, I commonly put a blank widget at the bottom of the of the widget tree to push the rest of the widgets up to the top. I'm newer to Kivy, so maybe there is a reason for this I don't understand yet. It seems that having the layouts rise to the top to fill space would be more intuitive. 

It's not a huge deal to put the blank widget, but it would be great if either
* There was a built in widget/widget-mixin that automatically did something to this effect
* The placement of widgets started from the top of the screen

Please let me know if I've misunderstood some functionality of this API. As of now, I have not found any other simple workaround to this minor issue.

**Comment by tshirtman** [comment]
the StackLayout has a direction property which does fit this use case, but i agree it would be nice for BoxLayout and GridLayout to allow for different directions, there is some work going on for this in GridLayout, and i had a patch for BoxLayout sometime ago, but i think i didn't merge it because i wanted RecycleBoxLayout to work the same, and didn't do it, and as with a lot of things i started, i forgot about it :grimacing: anyway, i don't think this warrants a new layout, but merely adaptation of existing ones to allow for more flexbility.

**Comment by pythonic64** [comment]
@Svaught598 You use [AnchorLayout](https://kivy.org/doc/stable/api-kivy.uix.anchorlayout.html) to anchor child widget (Grid/Box layout) to one of the anchors.

**Comment by Svaught598** [comment]
Ok! sorry for just getting around to replying, I've actually been using AnchorLayout since submitting this, so I just forgot about the issue altogether. Thanks for the assistance!
