### ISSUE TITLE
Dear developers, I hope you can add support for arm64 architecture Linux application display in chroot environment.

### ISSUE THREAD

**Issue by maozhifeng** [kivy/kivy#6800]
Dear developer, I am currently using your kivy to make apk, it works well on the computer, thank you for your project creation!

However, an idea has recently emerged because it is always inconvenient to always develop on a computer. I want to develop on mobile at any time. I used the linux_deploy application to deploy Ubuntu18 arm64 on my phone, and connected to the screen using X11 software, and then successfully installed kivy based on your source code. When running the example, you will be prompted "No matching FB configuration"

I don't want to use
Kivy Launcher application or pydroid3 application is used for software development because its scope of use is limited.

By referring to the documentation for installing kivy on a Raspberry Pi, it may not work properly due to differences in display drivers. I hope you can add support for Qualcomm mobile chip displays, not just the Raspberry Pi, so that you can easily develop applications.

**Comment by maozhifeng** [comment]
![Screenshot_2020-03-26-15-40-47-152_x org server](https://user-images.githubusercontent.com/37328485/77710890-51a56880-700a-11ea-86be-052151b0ebe4.jpg)

**Comment by matham** [comment]
I'm sorry, but I'm unable to parse this issue. It mentions a bunch of unrelated things: chroot, linux_deploy, pydroid3, and the pi and I don't understand the connection between them.

I'm guessing you're asking for us to support linux_deploy, but I don't think we are likely to add support for this. If you have a specific bug or very clear feature request, please open a new issue. Otherwise, for support, please ask on discord.
