### ISSUE TITLE
Clicking a button of an item in RecycleView leads to a button of another item flashing

### ISSUE THREAD

**Issue by mkc2019** [kivy/kivy#6902]
**Software Versions**
* Python: 3.6.9
* OS: Ubuntu 18.04
* Kivy: 1.11.1
* Kivy installation method: pip install kivy

**Describe the bug**
In RecycleView, if I press a button in one of the viewclass object with a button, which triggers the update on data used by RecycleView, a random button in the list will flash. See code and video below.

**Expected behavior**
Other buttons should not flash a particular button.

**Code and Logs and screenshots**
```python
import kivy
from kivy.app import App
from kivy.lang import Builder
from kivy.uix.label import Label
from kivy.uix.button import Button
from kivy.properties import StringProperty, ListProperty
from kivy.uix.recycleview.views import RecycleDataViewBehavior
from kivy.uix.boxlayout import BoxLayout


class MyButton(RecycleDataViewBehavior,BoxLayout):
    value = StringProperty()
    def __init__(self,**kwargs):
        super().__init__(**kwargs)

    def add_data(self):
        app = App.get_running_app()
        new_value = len(app.rv_data)
        app.rv_data.append({"value":str(new_value)})


class MyApp(App):
    rv_data = ListProperty()

    def __init__(self, **kwargs):
        mylist = list()
        for i in range(10):
            mylist.append(dict(value=str(i)))
        self.rv_data = mylist
        super().__init__(**kwargs)

    def build(self):
        return Builder.load_string("""
<MyButton>
    orientation: "horizontal"
    Label:
        text: root.value
        color: 0,0,0,1
    Button:
        text: "Press Me"
        pos_hint: {"center_x": .5, "center_y": .5}
        size_hint_x: .5
        on_press: root.add_data()

Screen:
    canvas.before:
        Color:
            rgba: 1,1,1,1
        Rectangle:
            pos: self.pos
            size: self.size
    RecycleView:
        id: rv
        viewclass: "MyButton"
        data: app.rv_data
        RecycleGridLayout:
            cols: 2
            default_size: [0, dp(40)]
            default_size_hint: 1, None
            size_hint_x: 1
            size_hint_y: None
            height: self.minimum_height
            spacing: dp(5)
"""
)

if __name__ == '__main__':
    MyApp().run()

```
![Button Flashing 2](https://user-images.githubusercontent.com/55228926/83222613-4ce86680-a1ab-11ea-9e80-f9aa3e336025.gif)

**Additional context**
This issue seems related to #5496. Any idea why this is happening?

**Comment by matham** [comment]
This is not a bug. The issue is that you do `on_press: root.add_data()`. So as soon as you press, the data is updated and the graphics are updated. So before you even released, the widgets used to display the data are changed up and another data item is re-using the widget.

The solution is to not do anything until the button is released (i.e. use `on_release` instead of `on_press`. Or a more correct solution would be to schedule the data update on the next frame with the clock.

**Comment by mkc2019** [comment]
@matham 
Thank you for your reply. I tried to do as you suggest, but the issue is still there. Could you replicate the issue on your side?

Here is the modified code:
```
import kivy
from kivy.app import App
from kivy.lang import Builder
from kivy.uix.label import Label
from kivy.uix.button import Button
from kivy.properties import StringProperty, ListProperty
from kivy.uix.recycleview.views import RecycleDataViewBehavior
from kivy.uix.boxlayout import BoxLayout
from kivy.clock import Clock


class MyButton(RecycleDataViewBehavior,BoxLayout):
    value = StringProperty()
    def __init__(self,**kwargs):
        super().__init__(**kwargs)

    def add_data(self):
        Clock.schedule_once(self._add_data,0)

    def _add_data(self,*args,**kwargs):
        app = App.get_running_app()
        new_value = len(app.rv_data)
        app.rv_data.append({"value":str(new_value)})

class MyApp(App):
    rv_data = ListProperty()

    def __init__(self, **kwargs):
        mylist = list()
        for i in range(10):
            mylist.append(dict(value=str(i)))
        self.rv_data = mylist
        super().__init__(**kwargs)

    def build(self):
        return Builder.load_string("""
<MyButton>
    orientation: "horizontal"
    Label:
        text: root.value
        color: 0,0,0,1
    Button:
        text: "Press Me"
        pos_hint: {"center_x": .5, "center_y": .5}
        size_hint_x: .5
        on_release: root.add_data()

Screen:
    canvas.before:
        Color:
            rgba: 1,1,1,1
        Rectangle:
            pos: self.pos
            size: self.size
    RecycleView:
        id: rv
        viewclass: "MyButton"
        data: app.rv_data
        RecycleGridLayout:
            cols: 2
            default_size: [0, dp(40)]
            default_size_hint: 1, None
            size_hint_x: 1
            size_hint_y: None
            height: self.minimum_height
            spacing: dp(5)
"""
)

if __name__ == '__main__':
    MyApp().run()

```

**Comment by matham** [comment]
Hmm, this is because button has a [minimum release timeout](https://github.com/kivy/kivy/blob/master/kivy/uix/behaviors/button.py#L175). If you click the button for less than a certain amount of time, it'll wait the minimum time before resetting the state to `normal`.

So basically the issue is that the button is re-used when the data is updated **before** the button is actually released visually. I.e. even though the `on_release` event has fired, the button doesn't visually get reset to `normal` until after the timeout.

I suppose this is a bug in Button because it should release and set the state at the same time. But for now, the workaround should be to change `on_release: root.add_data()` to `on_state: if self.state == 'normal': root.add_data()`. This fixes it because the state is reset after the timeout so it should always work. Unfortunately, most widgets were not designed with a eye for recycle view, so they probably have data/state issues when present in a rv.

**Comment by mkc2019** [comment]
Thank you very much @matham ! This workaround did the trick :)
