### ISSUE TITLE
Regular http requests via UrlRequest fail on Android

### ISSUE THREAD

**Issue by idevo89** [kivy/kivy#6946]
**Software Versions**
* Python: v3.8.1
* OS: Android 9 API29
* Kivy: v2.0.0rc2
* Kivy installation method: python-for-android develop

**Describe the bug**
Since #6703, regular http requests via urlrequest no longer work on android. The on_error function of urlrequest is called, while on desktop it is successful. Going back to kivy v2.0.0rc1 fixes it, but this version has broken https.

**Expected behavior**
Successful regular http requests.

**To Reproduce**
```python
from kivy.app import runTouchApp
from kivy.uix.widget import Widget
from kivy.network.urlrequest import UrlRequest


class Test(Widget):
    def __init__(self, **kwargs):
        super(Test, self).__init__(**kwargs)
        UrlRequest(
            url='http://lipsum.com/',
            on_error=lambda *args: print('error:', args),
            on_failure=lambda *args: print('fail:', args),
            on_redirect=lambda *args: print('redir:', args),
            on_success=lambda *args: print('success:', args)
        )
        UrlRequest(
            url='https://lipsum.com/',
            on_error=lambda *args: print('error:', args),
            on_failure=lambda *args: print('fail:', args),
            on_redirect=lambda *args: print('redir:', args),
            on_success=lambda *args: print('success:', args)
        )


runTouchApp(Test())

```

**Code and Logs and screenshots**
```python
TypeError("__init__() got an unexpected keyword argument 'context'")
```

**Comment by AndreMiras** [comment]
Thanks for the report. Please share the full stacktrace as it often helps developers to spot the exact issue more quickly.
Also could you try on the  2.0.0rc3 that was released recently?

**Comment by idevo89** [comment]
It is the same for v2.0.0rc3. I omitted the try-exception around
```python
result, resp = self._fetch_url(url, req_body, req_headers, q)
```
and added 'win' to line 219 in urlrequest to simulate the error on desktop and get a traceback.
https://github.com/kivy/kivy/blob/ab58fbecea6ae1ee4f8f465d9eaad2b41bdd6f65/kivy/network/urlrequest.py#L219


```python
Exception in thread Thread-1:
 Traceback (most recent call last):
   File "C:\Program Files (x86)\Python38-32\lib\threading.py", line 932, in _bootstrap_inner
     self.run()
   File "C:\Program Files (x86)\Python38-32\lib\site-packages\kivy\network\urlrequest.py", line 253, in run
     result, resp = self._fetch_url(url, req_body, req_headers, q)
   File "C:\Program Files (x86)\Python38-32\lib\site-packages\kivy\network\urlrequest.py", line 360, in _fetch_url
     req = cls(host, port, **args)
 TypeError: __init__() got an unexpected keyword argument 'context'
```

**Comment by AndreMiras** [comment]
Thanks for the trace, from quick checking I think the problem occurs with `[HTTPConnection](https://docs.python.org/3/library/http.client.html#http.client.HTTPConnection)` class only which indeed doesn't seem to accept a context while the `[HTTPSConnection](https://docs.python.org/3/library/http.client.html#http.client.HTTPSConnection)` does.

From reading the code, I think this is happening because now because since recently, the CA file is always provided https://github.com/kivy/kivy/pull/6703 then we enter in this case https://github.com/kivy/kivy/blob/2.0.0rc3/kivy/network/urlrequest.py#L337 which generate the context. So probably an easy fix would be to also check for `parse.scheme == 'https'` in this if as well. I may make a PR + test later this week
