### ISSUE TITLE
Image on Android not loading... showing a black screen

### ISSUE THREAD

**Issue by jok3erc0ncy30** [kivy/kivy#6961]
**Software Versions**
* Python: 3.8
* OS:Kali Linux 2020.1, Android 8.1
* Kivy: Latest
* Kivy installation method: pip

**Describe the bug**
I complied my program to an app and when i import and image using the plyer filemanager.. the image is not loaded and showed a black rectangle. The image is present and the code is working fine on PC(Linux). But I don't know why it does not works on android.

**Expected behavior**
I cannot see the image. The image should be loaded but I only get a black screen.

**Code and Logs and screenshots**
![image](https://user-images.githubusercontent.com/65017033/85460077-805abd00-b5c0-11ea-8d50-1056fdf95d03.png)

**Comment by kengoon** [comment]
i had the same issue with my app "Binomial". What i think is the problem is that your phone cannot render very high quality image when you use kivy rendering properties. In my app what i had to do was to reduce the quality of the image(actually the size reduced and i had little or no loss in the quality). Moreover ".jpg" files are ok for image with multiple colors and ".png" files or ok for image with one or two colors only. So to me I think you should try to compress the image you can checkout this site [https://www.img2go.com/compress-image](url)
