### ISSUE TITLE
PEP 484 .pyi Typing Support

### ISSUE THREAD

**Issue by sweethuman** [kivy/kivy#6970]
**Is your feature request related to a problem? Please describe.**
I'm very frustrated when I want to know more about the things that are available to me when working with kivy, and every time I have to search in the docs. It really takes a lot of time and makes it harder and more unpleasant to work with kivy.

Adding .pyi stub files to type the objects would be really nice and make working with kivy a breeze.

**Comment by matham** [comment]
How is `pyi` files better than looking at the source code? If your editor supports looking at the pyi files in Kivy's source code, why not just look at kivy's source code directly?

I agree that the docs should be improved so that it's easier to see at a glance what our API is, but pyi files is not meant to be a fix for this particular issue, even if it may coincidentally make simply docs lookups. And for some things, like the events supported by widgets, pyi files doesn't really support kivy's mechanisms.
