### ISSUE TITLE
Canvas Memory Leak

### ISSUE THREAD

**Issue by edwit1971** [kivy/kivy#6981]
I am drawing using the Kivy Canvas.  It works.  But...
repeated drawing on the screen seems to increase the CPU usage which means the app starts running slower and slower very quickly.

`class Draw_Stuff():

    #################################################
    def __init__(self, **kwargs):
        self.IG_Line = InstructionGroup()

    #################################################
    # Clear all the Instructions from the IG_Line
    # and make the Labels invisible
    def Clear_Lines(self):
        self.IG_Line.clear()

    #################################################
    # Draw a Line inside the Drawing Window Area
    # given Pixel coordinates
    # Not Axis Coordinates
    def Draw_Line(self, pScreen=None, pX1=0, pY1=0, pX2=0, pY2=0, pR=1, pG=1, pB=1, pW=1, pOp=1):
        self.IG_Line.add(Color(rgba = (pR, pG, pB, pOp)))
        self.IG_Line.add(Line(points = [pX1, pY1, pX2, pY2], width = pW))
        if(pScreen is not None):
            pScreen.canvas.before
            pScreen.canvas.add(self.IG_Line)
        return`

**Comment by edwit1971** [comment]
my code is in the following repository:
[https://github.com/edwit1971/Rectangle/](url)

If you hit Clear Screen,
and then hit the Rectangles Button and then the STOP button to see the time it took to draw and finish. Hit the CLEAR DRAWING button.
then repeat. Hit Rectangles Button. and when the STOP button appears immediately hit it. and then hit the Clear Drawing Button.
Each time you do this, the time keeps increasing...

**Comment by pythonic64** [comment]
Is the problem similar to https://github.com/kivy/kivy/blob/master/examples/canvas/canvas_stress.py ?

**Comment by edwit1971** [comment]
No the problem I'm seeing is not the same as you mentioned.  How to explain this?  The effects are almost IMMEDIATE.  The instant I start drawing on the screen with Instructions to the Canvas, the App starts to slow down instantly.  Even using an animated SPINNER from KivyMD shows the effect.  The App slows down so bad the Spinner is useless because the animation is so choppy.  The more I add instructions to draw on the screen, NO MATTER THAT I DELETE ALL THE INSTRUCTIONS to CLEAR THE SCREEN the CPU starts being cumulatively more and more busy (meaning the App gets slower and slower).  The ONLY SOLUTION is to NEVER DRAW to the screen using Kivy Canvas which means never drawing on the screen at all.

**Comment by tshirtman** [comment]
Your problem seems to come from the fact that you add the instruction group over and other to the canvas of pscreen, while you should only do it once, adding a flag in your code to prevent it from happening more than once fixes the performance issue.

I'm not exactly sure why it's a problem (and why it even works, i would have assumed adding the same instruction instance multiple times to a canvas would cause a crash), but there is a better solution that "NeVeR DrAwInG To ThE ScReEn".

- please don't write all caps, that's not nice to the people that try to help you, as it feels like being screamed at.
- please read PEP-8 and stop littering your code with meaningless "#####" lines, just and 90s style comment blocks telling useless things like the filename and the creation date, that's what git is for, it'll make pythonists reading your code much more happy.

**Comment by edwit1971** [comment]
TShirtMan fixed my Memory buildup problem.  He's awesome!!!!

For others, I want to make the fix clear...

You can only call Canvas.add( InstructionGroup ) once per Screen Drawing.
Do all your drawing to the InstructionGroup Object. Then when you draw the screen add the InstructionGroup ONCE to Canvas.add.

When you want to redraw the screen and make a new screen and new drawing,
clear the canvas and clear your InstructionGroup, and draw new instructions to the InstructionGroup and then add it once to the Canvas.

If you call Canvas.add( ) more than once before clearing the canvas it will build up memory and slow the CPU down and there is no way to undo it without quitting the App to release all the resources.
