### ISSUE TITLE
pythonw.exe needs  KIVY_NO_CONSOLELOG to be set on windows

### ISSUE THREAD

**Issue by jgirardet** [kivy/kivy#7004]
I think it could be handled by kivy.
an easy fix could be to auto set KIVY_NO_CONSOLELOG if sys.executable is "pythonw.exe" on windows.

**Comment by matham** [comment]
Changing the default value of `KIVY_NO_CONSOLELOG` based on how python is started will lead to API inconsistencies, so we should not do that.

**Comment by J3ronimo** [comment]
Running a kivy app with pythonw.exe will currently just do nothing - it crashes because pythonw.exe does not provide sys.stdout / sys.stdin, which kivy needs for logging and can't handle if it's not there. I can't imagine that this is the desired behavior.

So currently, to support running on pythonw.exe, your apps needs to do something like below before importing kivy:

```python
import os
if sys.executable.endswith("pythonw.exe"):
    os.environ["KIVY_NO_CONSOLELOG"] = "true"
```

And that's basically what OP proposed kivy could do itself.

Another way to do it is to have a look at `sys.stdout` when initializing kivy's logging. If that's set to `None`, just internally behave the same way as if `KIVY_NO_CONSOLELOG` was set in env, without actually setting it so. This way, redirections like done in IPython qtconsole would work nicely with it, where stdout exists while still running on pythonw.exe.
