### ISSUE TITLE
touch.x and touch.y misaligned from cursor

### ISSUE THREAD

**Issue by DrakeProvost** [kivy/kivy#7023]
**Software Versions**
* Python: 3.7.3
* OS: Raspbian 10 (buster)
* Kivy: 1.11.1
* Kivy installation method: (taken from #6413):

> sudo apt update
> sudo apt -y upgrade
> sudo apt install -y libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev pkg-config libgl1-mesa-dev libgles2-mesa-dev python3-setuptools libgstreamer1.0-dev git-core gstreamer1.0-plugins-{bad,base,good,ugly} gstreamer1.0-{omx,alsa} python3-dev libmtdev-dev xclip xsel libjpeg-dev
> python3 -m pip install --upgrade --user pip setuptools
> python3 -m pip install --upgrade --user Cython==0.29.10 pillow
> sudo pip3 install kivy

**Describe the bug**
touch.x and touch.y do not accurately line up with the mouse (tested with on_touch_move). With on_touch_move, the amount it's displaced is inconsistent as well, and depends on the speed of your mouse as you "draw". With the Pong Game example I describe below, the paddle also flickers quickly between misaligned and aligned. 

I confirmed this issue with 2 separate RPi 4B's (all same software versions), each with their own monitor (one 5", the other 24" if I remember correctly). Both systems were affected in a similar way.

**Expected behavior**
I expect the touch.x and touch.y values to be reflective of where the touch event is actually occurring.

**To Reproduce**
Problem is noticeable with [Touch Tracer Line Drawing Demonstration](https://kivy.org/doc/stable/examples/gen__demo__touchtracer__main__py.html#file-demo-touchtracer-main-py). It was originally observed with the [Pong Game Tutorial](https://kivy.org/doc/stable/tutorials/pong.html#) since one or both of the paddles wouldn't be centered on touch events, instead moving in the same direction as the touch event but at an incorrect and scaled rate.

**Code and Logs and screenshots**
Code can be copy-pasted from the two tutorials linked above. 

The logs are [here](https://gist.github.com/DrakeProvost/90792e6069a46c4a9571a6a308cf0908).

I took some screenshots of example output from Touchtracer to hopefully demonstrate what I mean. Take notice that not only are things misaligned, but that the level of misalignment was dependent on the speed at which my mouse moved and therefore the misaligned writing isn't just a scaled version of the original. Here are the screenshots:

* Blue followed my cursor, magenta is the misaligned stuff:
![2020-07-31-012308_1920x1080_scrot](https://user-images.githubusercontent.com/19244666/89008834-fe516880-d2d0-11ea-9611-bb1e4d998bb9.png)
* Red followed my cursor, cyan is the misaligned stuff:
![2020-07-31-012538_1920x1080_scrot](https://user-images.githubusercontent.com/19244666/89008850-06a9a380-d2d1-11ea-93e1-9a711581ad54.png)
* Blue followed my cursor, yellow is the misaligned stuff:
![2020-07-31-012702_1920x1080_scrot](https://user-images.githubusercontent.com/19244666/89008853-08736700-d2d1-11ea-939f-8b19d78dd84d.png)

**Comment by wolfmanjm** [comment]
I think this issue is to do with the fact that the events are being read directly from the touch device rather than allowing X windows to pass the events. In order to get events from XWindows (where the coordinates will be corrected for your window) you would need only 
```
[input] 
mouse=mouse
```
in the ~/.kivy/config.ini.

However this has a problem that it won't work well with a multi touch device.

You could use 
```
[input]
mtdev_%(name)s = probesysfs,provider=mtdev
```

Which works fine for me, however only if the kivy app is running full screen with no window adornments (ie no title bar etc).

In the event that the offsets are still incorrect then a more complex configuration is needed that tells it how to map the touch events to the screen. This is done in the raspi /boot/config.txt file and is documented in the raspi wiki.

If I am correct then the only way to get correct mouse events in a non full screen XWindow is to use the mouse=mouse, mainly becuase only XWindows knows where your window is on the screen and how to map the Xscreen coordinates to your application coordinates.
When you read the mouse events directly they are usually in screen coordinates hence the mismatch.
