### ISSUE TITLE
Pycharm not recognizing Kivy 

### ISSUE THREAD

**Issue by JAA2000** [kivy/kivy#7033]
![kivy potential issue 3_LI111](https://user-images.githubusercontent.com/69207629/89550041-1fd1b900-d7d7-11ea-8f36-a37e99f56efd.jpg)

I am trying to import Kivy on Pycharm but it says it doesn't recognize the module despite the fact that it is installed, not sure if this is a problem with the interpreter or not.

**Comment by Broezion3** [comment]
I've the same problem, I think this is a pip or python's problem

**Comment by Broezion3** [comment]
I'm not an expert, but I think that you can't install kivy in windows. Also if you are using python3, you must digit this code in the PyCharm terminal: `pip install kivy==2.0rc3.`

I give you an advice: buy a Mac or use a virtual machine, linux and Mac are better to develop. Linux more but Mac OS ids designed better.

Have a nice day!!👋🏻👋🏻

**Comment by SESummers3** [comment]
Sorry, that's incorrect. Kivy works fine on Windows 10, and on Pycharm 2020.2, and on Python 3.7.  It also doesn't help to recommend changing operating systems. Most of us can't simply announce to our employers that they must spend a bunch of money to buy us a Mac because somebody on the internet said it was better than the OS the corporation already has already spent $millions installing on tens of thousands of desktops (because the other 90%+ of businesses made the same decision and it seemed safe).  They'll typically tell you to do what you're told with what you're provided or go find another place to work. 

JAA2000, I'm not sure what the problem is on your machine - the log you provided looks like everything was already installed.  What happens if you try to run a Kivy example in PyCharm?

**Comment by JAA2000** [comment]
Don't worry, I resolved the issue, Had to do with the interpreter.
