### ISSUE TITLE
Invalid instance in App.root

### ISSUE THREAD

**Issue by JAA2000** [kivy/kivy#7036]
I'm currently watching a youtube tutorial on kivy, but I keep getting this app.root error, what does it mean and how do I fix it? Thank you.
![kivy sdfghjk](https://user-images.githubusercontent.com/69207629/89668874-7fe65f00-d8ac-11ea-9b73-8fdd5894cd77.PNG)
![Kivy asdfgh](https://user-images.githubusercontent.com/69207629/89668875-807ef580-d8ac-11ea-8f9e-957f1084df18.PNG)
![kivy issue whatever](https://user-images.githubusercontent.com/69207629/89668876-807ef580-d8ac-11ea-83ab-bb376e0d10de.PNG)

**Comment by tshirtman** [comment]
your `MyGrid` class is not a subclass of a widget, i assume you intended to subclass `GridLayout`.

**Comment by SESummers3** [comment]
The app's widget tree, including the root node, have to be widgets.  Also,
your kv code at the bottom that starts with <My Grid> won't work because
the name of the class you're trying to modify is "MyGrid" not "My Grid".
My guess though is that you're not getting an error from that, unless your
KV code is in a file with the same name as your app (but without the word
"app" if you had it. Very confusing, I know.)

The biggest problem with ALL the Kivy tutorials I found (I just started
learning it in mid-May, and was VERY confused at first), is that they think
showing one widget that occupies the entire main window is a "demo". The
thing to remember is that widgets are TREES.  If you have a dialog box that
has say two edit boxes with labels, and an OK and Cancel button at the
bottom, your widget tree might look something like this (in KV language):

<MyDialogBox@BoxLayout>:   #Declare a new class - = "class
MyDialogBox(BoxLayout)" in Python.
    orientation: 'vertical'    #Make it stack in layers
    Label:                     #Put a label with "Name" on it
        text: "Name"
    TextInput:                 #Give it an edit box

    Label:                     #Repeat for the "Name" label and box
        text: "Name"
    TextInput:

    BoxLayout:                 #Now add OK and Cancel buttons across the bottom
        orientation: 'horizontal'
        Button:
            text: "OK"
        Button:
            text: "Cancel"
MyDialogBox:                   #Finally, tell the app that MyDialogBox
is the root

If you do this, it will look like:
[image: image.png]

Now if you want it to look better, you'll have to experiment with
size/size_hint and pos/pos_hint properties.  BE SURE TO STUDY AND
UNDERSTAND THE LAYOUT widgets, and how they work with those size and pos
properties. The "magic behind the curtain" is what really confused me the
most at first.
