### ISSUE TITLE
Weird behviour in RecycleView

### ISSUE THREAD

**Issue by AssemRad** [kivy/kivy#7075]
**Software Versions**
* Python: 3.6
* OS: Windows 10
* Kivy: 1.11.0
* Kivy installation method:

**Describe the bug**
Updating the RecycleView's data in one row renders the updated data on another also.
RecycleView is having two rows (data elements), each one is having a text box populated by a property of the view class.

When changing the value in the second row's quantity text box to **2** for example and updating the underlying data item (index 1 in data) with this value. then refreshing the recycle view from the data. It _**renders 2 also in quantity text input of the First row**_ as well as the _expected 2 in text input of the Second row_!

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/3982577/92926240-6785d900-f444-11ea-9849-a4a9110ef39d.gif)

**Expected behavior**
When changing the quantity TextInput of the Second Item row and pressing Enter, the new quantity should be rendered on that TextInput upon refreshing from data. But quantity rendered in the first row's text input should remain intact!

**To Reproduce**
Run the shortened sample code below then change the value in text input of the second row to 2 or whatever number. observe that this also changes the value of the First row's text input.

**Code and Logs and screenshots**
```python
from kivy.app import App
from kivy.lang import Builder
from kivy.properties import ListProperty, StringProperty, NumericProperty
from kivy.uix.boxlayout import BoxLayout

Builder.load_string("""
<RVRow>:
    Label:
        text: root.name

    Label:
        text: str(root.price)
        halign: 'center'

    TextInput:
        text: str(root.quantity)
        multiline: False
        halign: 'center'
        size_hint_x: .15
        on_text_validate:
            # Hardcoded for demo purpose and not inheriting from RecycleDataViewBehavior
            app.main_window.data[1]['quantity'] = int(self.text)
            app.main_window.rv.refresh_from_data()
            
    Label:
        text: str(root.quantity * root.price)



<MainWindow>:
    orientation: 'vertical'

    rv: rv

    RecycleView:
        id: rv
        key_viewclass: 'viewclass'
        pos_hint: {'top': 1, 'left': 0}
        data: root.data

        RecycleBoxLayout:
            default_size: None, dp(48)
            default_size_hint: 1, None
            size_hint_y: None
            height: self.minimum_height
            orientation: 'vertical'
""")

class RVRow(BoxLayout):
    name = StringProperty('')
    price = NumericProperty(0)
    quantity=NumericProperty(0)

class MainWindow(BoxLayout):
    data = ListProperty([])
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.data = [
            {'viewclass': 'RVRow' , 'name': 'First', 'price': 10 , 'quantity': 1},
            {'viewclass': 'RVRow', 'name': 'Second', 'price': 30, 'quantity': 1},
        ]


class RecycleViewUpdateApp(App):
    main_window = None
    def build(self):
        self.main_window = MainWindow()
        return self.main_window

if __name__=='__main__':
    RecycleViewUpdateApp().run()
```

**Comment by pythonic64** [comment]
When views get refreshed due to `refresh_from_data` call layout manager will reuse views but not usually in the same order as they were displayed before `refresh_from_data` call. In your case after `refresh_from_data` call, second row will become the first one and for it `quantity` attribute didn't change (value is 1) and therefore no update is done to `TextInput.text` property. 

You can see what is happening to `RVRow` class when you replace it with this one:
```
from kivy.uix.recycleview.views import RecycleDataViewBehavior

class RVRow(RecycleDataViewBehavior, BoxLayout):
    name = StringProperty('')
    price = NumericProperty(0)
    quantity = NumericProperty(0)

    def refresh_view_attrs(self, rv, index, data):
        super().refresh_view_attrs(rv, index, data)
        print(index, id(self), self.quantity, self.children[1].text)
```

It will print something like this:
```
# Before entering new value for quantity in second row
0 1883702598680 1 1
1 1883703466360 1 1

# After refresh_from_data call
0 1883703466360 1 2
1 1883702598680 2 2
```

The easiest solution is to dispatch `quantity` in `refresh_view_attrs` method like this:
```
    def refresh_view_attrs(self, rv, index, data):
        super().refresh_view_attrs(rv, index, data)
        self.property('quantity').dispatch(self)
```

or you can check if `quantity` didn't change (comparing `self.quantity` and `data['quantity']`) and then dispatch or assign text directly if `quantity` didn't change. 

This is not a bug in RecycleView but maybe an undocumented case or missing examples which would show how to sync view when inputs (`TextInput`, `ToggleButton`, `CheckBox` etc) are used.

**Comment by AssemRad** [comment]
@pythonic64 thank you for the clarification.
Testing the case does solve the problem (Changing the quantity box of the second row). 
However, if I went **further step** and changed the quantity box of the **First row**, values get disrupted again !

**Comment by pythonic64** [comment]
You hardcoded index to `1` in kv rule for `RVRow`.

**Comment by matham** [comment]
I believe https://kivy.org/doc/master/api-kivy.uix.recycleview.html#viewclass-state contains the updated docs for how to manage state!?

**Comment by pythonic64** [comment]
I was thinking of an example with more inputs, like one row with `TextInput`, `ToggleButton`, `CheckBox`, `Spinner` etc. Maybe an example with multiline `TextInput`, so it doesn't use `on_text_validate` to store text back in data.

Example at https://kivy.org/doc/master/api-kivy.uix.recycleview.html#viewclass-state looks good to me, except for `class RV(RecycleView, App)` part which teaches users to combine `App` with `Widget` classes and I would suggest to use `App.build` method instead.

**Comment by tshirtman** [comment]
hm, indeed there is no example showing editable content in https://github.com/kivy/kivy/tree/master/examples/widgets/recycleview either i have this one showing a related thing with checkboxes https://gist.github.com/tshirtman/aae7cc0a18c1cfe92b4a0399d2a0e29e but (though storing the selection state outside of data, which might not be the most flexible way, but was interesting for performance reasons here). 

so i gave a shot at making a nicer example for such a situation and it got a bit out of hand (https://gist.github.com/9cce16df53f643118cf72cb080e50398) due to my inhability to keep things simple, but its' *almost* as good as i want, it just doesn't handle refocusing well (after scrolling an edited element out and into the screen), and it might be too complex an example to follow.
