### ISSUE TITLE
x

### ISSUE THREAD

**Issue by Jena2** [kivy/kivy#7127]
x

**Comment by tshirtman** [comment]
Please provide the full log, not just the error, this doesn't show enough about what happened.

**Comment by Jena2** [comment]
> Please provide the full log, not just the error, this doesn't show enough about what happened.

@tshirtman  Here is my full log. I had to divide into two parts https://pastebin.com/TfuEpEXV https://pastebin.com/jUXYHak0

**Comment by tshirtman** [comment]
can you go to
/mnt/c/Users/acer/Downloads/kivy/Test/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/ffpyplayer-openssl/armeabi-v7a__ndk_target_21/ffpyplayer

and run `/mnt/c/Users/acer/Downloads/kivy/Test/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/native-build/python3 setup.py build_ext -v`

seems to be the first thing that fails, yes, it's expected to fail, but i think it doesn't fail in the expected way, and that's why there is no ffpyplayer/pic.c file after that, you might be missing something for the build to happen.

same thing in the directory `/mnt/c/Users/acer/Downloads/kivy/Test/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/pyjnius-sdl2/armeabi-v7a__ndk_target_21/pyjnius` and the command `/mnt/c/Users/acer/Downloads/kivy/Test/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/native-build/python3 setup.py build_ext -v`

i suspect you are missing some dependency, did you follow https://buildozer.readthedocs.io/en/latest/installation.html#targeting-android ?
