### ISSUE TITLE
Ability to keep Kivy windows active / or always monitor keyboard events

### ISSUE THREAD

**Issue by taichi-suzuki-pckg** [kivy/kivy#7146]
I'm using Kivy keyboard events to create applications that work with external applications.

However, there is one problem with using this feature of Kivy.
Once I tap a Kivy window with the mouse and then type on the keyboard, a keyboard event occurs.
Then, if I tap other non-Kivy applications etc. with the mouse and then type on the keyboard, the keyboard event will not occur.
This happens because Kivy is deactivated when a non-Kivy window becomes active.

I sometimes want to have a keyboard event even when a non-Kivy window is active.

I asked Stack Overflow about this issue, but didn't get an answer.
[https://stackoverflow.com/questions/63875135/how-to-listen-for-keyboard-events-when-the-kivy-window-is-inactive
](https://stackoverflow.com/questions/63875135/how-to-listen-for-keyboard-events-when-the-kivy-window-is-inactive
)
Is there already a way around these issues?
If there is no way around this, I would like to request it as a new feature.

**Comment by Zen-CODE** [comment]
This is not really under the control of kivy. It's due to the way operating systems direct input - to the application with the focus. It would not really be desirable for kivy apps to listen to global keyboard events.

If you want to monitor keyboard events, the best cross platform library I've found for that so far is pynput. But there are various others, depending on your need.

https://pypi.org/project/pynput/
