### ISSUE TITLE
Conda kivy package doesn't print its own version

### ISSUE THREAD

**Issue by tito** [kivy/kivy#7202]
**Software Versions**
* Python: 3.7
* OS: Arch Linux
* Kivy: ?
* Kivy installation method: conda install -c conda-forge kivy

**Describe the bug**
The current conda forge kivy package doesn't print its own version like the pip package.

**Expected behavior**
It is supposed to print something like:
```
[INFO   ] [Kivy        ] v1.11.1
```

**To Reproduce**
- install the package: `conda install -c conda-forge kivy`
- `python -c "import kivy; print(kivy._KIVY_RELEASE)"`

**Code and Logs and screenshots**
```
$ python -c "import kivy; print(kivy._KIVY_RELEASE)"
[INFO   ] [Logger      ] Record log in /home/tito/.kivy/logs/kivy_20-11-06_3.txt
[INFO   ] [Kivy        ] Installed at "/home/tito/.conda/envs/glitter2/lib/python3.7/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.7.8 | packaged by conda-forge | (default, Jul 31 2020, 02:25:08) 
[GCC 7.5.0]
[INFO   ] [Python      ] Interpreter at "/home/tito/.conda/envs/glitter2/bin/python"
False
```

The `kivy/base.py` code check either if it's a RELEASE version, on a development version that have a git hash. But conda package don't have.
So i guess we are missing the RELEASE tag?

**Comment by matham** [comment]
Can you check for sure which version you're using? Because I'm looking at https://anaconda.org/conda-forge/kivy/1.11.1/download/linux-64/kivy-1.11.1-py36hb227714_3.tar.bz2 and the code looks correct.

I suspect you installed 2.0.0rc4, which does seem to have this issue since we don't add a git hash or date for conda. However, I'm concerned that conda would install a rc version automatically. I had believed that stable is always considered larger than rc!?
