### ISSUE TITLE
Generate minimum reproducible code automatically

### ISSUE THREAD

**Issue by allhavebrainimplantsandmore** [kivy/kivy#7234]
**Is your feature request related to a problem? Please describe.**
It is very time consuming and annoying and robotic process to water down the code to produce a minimum reproducible code for bug submission. All the involved steps are highly automation prone. 

**Describe the solution you'd like**
A Kivy API to spit out a minimum reproducible code snippet for bug submission that would remove all of the formatting and styling code, also offer options to omit nonessential/unneeded classes/methods, and perhaps produce several minimum reproducible code variants with several degrees of slimming down - so that the developers could quickly narrow down which minimal code snippet reproduces the problem. This is just brainstorming, but it would simplify lives of everyone to make Kivy great.

**Comment by matham** [comment]
I don't think such a thing is currently possible. Consider that if had the capability to figure out how to strip the code down to show just the bare issue, that we would also have the capability to automatically fix the issue.

Additionally, generally, the process of a user reducing the code to a reproducible example typically helps them figure out if the issue is on their side or with Kivy and could also help them figure out workarounds. Because after all this is a community project and the goal is for the community to help supply fixes to their issues if they can.
