### ISSUE TITLE
Kivy Screen Manager changes device sreen size or reselution

### ISSUE THREAD

**Issue by Saad-py** [kivy/kivy#7306]
**Win 7**
* Python 3.85 Conda:

I went on the kivy docs website and then went to screenmanger to know about it there was a sample code so I tried it but it just changed my device screen to a smaller resolution and didn't open the app itself.

One more note that I was using juyter notebook
So again it changed the size of my device's screen

Why this bug and how to solve it.
@matham Sorry if this is not a bug

**Comment by Saad-py** [comment]
i tried a hello world so I found out its a problem with jupyter notebook

**Comment by matham** [comment]
I'm sorry, but github is really not the place to troubleshoot issues because there are very few people here responding, and don't even have enough time for proper bug reports.

Please ask on the discord channels or mailing list linked in the closing message below. If you can demonstrate that this is a kivy bug, then feel free to re-open, but with a complete but minimum example showing the issue.
