### ISSUE TITLE
Speeding up application startup on Android

### ISSUE THREAD

**Issue by TSalty21** [kivy/kivy#7333]
**Basic info**
- Kivy: master
- Python: 3.7
- Backend: SDL2
- Buildozer: 1.2.0

**Device info**
- Android: 5.0.2
- Model: P01Z

**Description**
Love Kivy, I've been using it for a couple years now. My contractor wants an app to work on android, now everything works great after the widgets have been created, but creating them takes too long. The app takes about a minute to load on older hardware. I'm lazy loading everything already, only creating widgets right before they're needed and caching them. The most basic test app takes about 15 seconds to start, just for comparison. That would be acceptable on devices with weaker hardware.

**Suggestion**
I had this not very promising idea. Would it be possible somehow to serialize the widgets in their initial state and save them to a file, so they could be loaded without too much computation? I'm afraid that saving all the context would be impossible. I'd like to skip creating most of my widgets, their initial state is always the same anyway, so why bother making them every time I open the app?

Is this idea worthwhile to investigate?
Are there any other ways to go about this problem?

**Comment by tshirtman** [comment]
Kivy widgets are using opengl instructions, which are dependent on a gl context, that part wouldn't be serializable and usable later, the idea does seem unpractical to me, if you managed to save the state but without the instructions, you would still need to go through the list of them to create them in the proper context.

I would rather time the creation of widgets and see which should be optimized, and look if there are things that should be optimized on the kivy side during that, or if you could just reduce the amount of instructions created, dispatching happening, etc. One minute indeed seems seriously long, even if we are talking about old hardware. Otherwise, you could make the widgets display "placeholders" until they are fully loaded, and schedule events to finish the loading after the app has started.

**Comment by TSalty21** [comment]
Alright, guess I'm going down that road instead. Thanks for the quick reply!
