### ISSUE TITLE
Kivy Refuses to Clear Existing Widgets On Start

### ISSUE THREAD

**Issue by BluelyTASer** [kivy/kivy#7336]
**Software Versions**
* Python: 3.7
* OS: Windows 10
* Kivy: Unknown
* Kivy installation method: Pip

**Describe the bug**
It Doesn't clear all existing widgets with self.clear_widgets()

**Annoying Part**
You need to click on Restart kernel from IDE since it's the only way to clear all existing widgets while also close the kivy which takes about 10 to 30 seconds which is really annoying.

**Expected Fix**
Add the command clear_all_existing_widgets() to clear existing widgets.

https://user-images.githubusercontent.com/59511669/104919883-ba811700-5975-11eb-8341-3bc6543a666e.mp4

**Comment by matham** [comment]
You seem to be running python multiple times from your IDE and somehow attaching to the existing kivy window. Or maybe that's just how it appears as it's hard to make out from the video. Either way, you can't just run python multiple times and expect it to edit an existing window from a previous run.

You also definitely cannot edit source code in-place and have the GUI change from that because that's not how python works. You have to run it fresh if you want to run from changed source code.
