### ISSUE TITLE
Could you please support poetry?

### ISSUE THREAD

**Issue by dada0z** [kivy/kivy#7360]
I like poetry.
I like kivy too.
But I don't know how to like them meanwhile.
So, how to install kivy with poetry?

**Comment by matham** [comment]
I'm not familiar with poetry, but from a brief look you do `poetry add kivy[base]==2.0.0`. So basically it's the same as the pip install commands shown in the docs, except you write `poetry add ...` instead of `pip install ...`.

**Comment by shorouq-z** [comment]
`poetry add kivy[base]==2.0.0` did not work for me because neither pip nor poetry are able to find this package. 

What you can do instead, @dada0z is to install this using the `poetry add` command which supports git and also supports downloaded packages. To learn more about these commands, check the poetry docs: https://python-poetry.org/docs/cli/#add

To do this for the stable release of kivy using poetry, try: 

`poetry add https://github.com/kivy/kivy/archive/stable.zip`

You could also use `poetry add git+<.git REPO LINK>#<BRANCH>`
