### ISSUE TITLE
Kivy app can't display text in other languages

### ISSUE THREAD

**Issue by WISEPLAT** [kivy/kivy#7393]
**Software Versions**
* Python: 3.9.1
* OS: Windows 10
* Kivy: 2.0.0
* Kivy installation method: pip install kivy

**Describe the bug**
Hello! Can't display text in other languages, for example in China, Korean and Hindi.

How to set default font to display them correctly in Kivy application?

For example in PyCharm editor with default font JetBrains Mono these text is displayed.

**Expected behavior**
I want this Chinese, Korean, and Hindi text to display correctly in the app.

**To Reproduce**
Run this code to this issue:

**Code and Logs and screenshots**
```python
from kivy.app import App
from kivy.uix.button import Label
from kivy.uix.boxlayout import BoxLayout

class TestApp(App):

    def build(self):
        main_layout = BoxLayout(orientation="vertical", padding=10, spacing=10)
        main_layout.add_widget(Label(text='English'))
        main_layout.add_widget(Label(text='Русский'))
        main_layout.add_widget(Label(text='Deutsch'))
        main_layout.add_widget(Label(text='Français'))
        main_layout.add_widget(Label(text='中文'))
        main_layout.add_widget(Label(text='한국어'))
        main_layout.add_widget(Label(text='िन्दी'))
        return main_layout

if __name__ == '__main__':
    TestApp().run()
```

**Additional context**
![Image](https://i.paste.pics/ae00818474b4eace4a77d98c8c6d0843.png?trs=cf4a8ec8176d601ba21b2adb58577b1bcf857a5d4b0a9c03570c3b6e26c4ad23)

**Comment by Zen-CODE** [comment]
This happens because you need to use a font that is capable of displaying those characters. You need to make sure:
1. You have a font installed that can display those characters.
2. That font is installed and active in Kivy.

Please see the below docs. Please re-open the ticket if you try this and do not come right but let's close the ticket for now as that is almost certainly the issue.

https://kivy.org/doc/stable/api-kivy.core.text.html#font-context-manager
