### ISSUE TITLE
Clarify using of angle_sdl2 backend in documentation

### ISSUE THREAD

**Issue by antkamidiv** [kivy/kivy#7397]
Hello! 
There is one thing I've wanted to clarify with no result. There is no strict answer anywhere inсluding official documentation.
What backend angle_sld2 is meant to do?
Is it meant for workaround  of OpenGL version limitation to 2.0 and above? It uses DirectX for drawing as I get. For example, for VM's with OpenGL 1.1.
If It's not for that, what's a point to use angle_sdl2 if we can use glew on any PC where OpenGL 2.0 is installed?

**Comment by tshirtman** [comment]
Indeed, it's to support windows computers with directx drivers but not an up to date opengl implementation, because after so many years, it's still common for windows to only ship with OpenGL 1.1, so it's unlikely to ever change. Asking users to update their drivers is not a great solution, and in some situations, like VMs, it can be really daunting, even for technical users.
On computers where both options are available, hopefuly there should be no difference.

**Comment by antkamidiv** [comment]
Thank you for reply. It's clear now. 

I have used user environment variable KIVY_GL_BACKEND with value angel_sdl2 set before all kivy imports.
I have many vm's and even physical pc's with only opengl 1.1 version support, and neither of them can successfuly run kivy with angle. Mostly I see such error "Kivy sdl2 - RuntimeError: b'Could not initialize EGL".

Is there any common approach to run kivy app with angle_sdl2? Instructions? May be voodoo code?

**Comment by matham** [comment]
I think it's better to ask these questions on discord, because github issues don't function well for this kind of support.

But my best guess is that either you didn't set `KIVY_GL_BACKEND` correctly, kivy is not installed correctly, or more likely, the VM isn't setup to allow graphics correctly. But that's not something we can really help with. A good place to look at is how we run the unit tests on Github Actions (although we don't do anything special beyond setting `KIVY_GL_BACKEND`).
