### ISSUE TITLE
Kivy Lang Documentation Missing for #:include

### ISSUE THREAD

**Issue by DaytonaJohn** [kivy/kivy#7431]
**Software Versions**
* Python: v3.8.5
* OS: Ubuntu 20.04
* Kivy: v2.0.0

**Describe the bug**
A bit of documentation is missing from kivy.lang. If a root widget is defined in a file included via the _#:include_, that root widget is silently ignored. Perhaps a line should be added to the documentation for _#:include_ that states that root widgets may not be defined in files referenced by _#:include_.

**Expected behavior**
The current documentation leads the user to expect that root widgets defined in an included kv file will be honored, but that is not the case

**To Reproduce**
Simple code to illustrate:

main.py:
```
from kivy.app import App


class SillyApp(App):
    pass

SillyApp().run()
```
silly.kv:

`#:include moreSilly.kv`

moreSilly.kv:

```
Label:
    text: 'Abba'
```

**Comment by matham** [comment]
When you include a root widget in a KV file, the widget is created and returned. This happens also for included kv files.

It's just that when a kv file is included, the widget is created but then dropped because it's not part of the API for a kv file that includes another kv file to return the widget created by the included kv file. I don't think we need to include this in the docs, because it's not suggested anywhere that it would be returned and it also hasn't come up before and it would just be distracting in the docs.
