### ISSUE TITLE
Numlock modifier is unexpected on non-numlock keys

### ISSUE THREAD

**Issue by jabdoa2** [kivy/kivy#7436]
**Software Versions**
* Python: 3.9
* OS: Win, Mac and Linux
* Kivy: 2.0.0
* Kivy installation method: pypi

**Describe the bug**
When registering a `on_key_down` handler in Kivy 2.0.0 we receive a "numpad" modifier on all keys. Not just the numpad keys. This has caused a lot of bug reports in the Mission Pinball Framework. Especially from notebook users which got numpad enabled by default for some reason. In Kivy 1.10 this modifier has not been supported - it was added in commit 574887be6ffcbbff0fde532c8f6b427ba6e64507 for Kivy 1.11 and 2.0

**Expected behavior**
We would expect to receive numlock only on numlock keys (and not on all keys).

Our current workaround:
```
        if "numlock" in modifiers and not keycode[1].startswith("num"):
            modifiers.remove("numlock")
```

**To Reproduce**
Register a handler an press `a` with `numlock` enabled:

```
class Keyboard(KivyWidget):

    def __init__(self, **kwargs):
        self.keyboard = Window.request_keyboard(callback=None, target=self)
        self.keyboard.bind(on_key_down=self._on_keyboard_down)

    def _on_keyboard_down(self, keyboard, keycode, text, modifiers):
        print(keycode, modifiers)
        return True
```

**Comment by matham** [comment]
Do you have an example where this is a problem? Because to me this exactly how it should be. I.e. modifiers is a list of all modifier keys currently pressed/active (including fn keys if we sdl sends it) and as a user you have to check if the specific modifier key you're interested in is present. So having extra keys should never be an issue. 

After all we are just passing on they modifiers that sdl2 tells us and the user has to decide if a specific modifier has meaning, rather than us filtering it out in some way as we are just passing on the info to be used as needed.

I suspect users probably previously checked `if {'some_modifier'} == modifiers`. But the correct pattern is to check `if 'some_modifier' in modifiers`.

**Comment by jabdoa2** [comment]
We allow users to bind keys to actions to simulate their pinball. For instance ctrl+g or shirt+1. We used to just match all modifiers. This kind of broke with this change. I guess caps would also break it for us. Maybe we should just change the logic on our side.

**Comment by matham** [comment]
>Maybe we should just change the logic on our side.

Yeah, I think that is the correct course because you can't really know which other modifiers may be active or added in the future.
