### ISSUE TITLE
install-failed-on-win10-amd-cpu

### ISSUE THREAD

**Issue by SuboFrank** [kivy/kivy#7530]
**Software Versions**
* Python:3.8
* OS:win10
* Kivy:2.0
* Kivy installation method:pip install kivy

**Describe the bug**
when i execute command : pip install kivy (venv python3.8)

The issue tracker is a tool to address **bugs only** (search known bugs: https://git.io/vM1iE).
Please use the #support Discord channel at https://chat.kivy.org/ or Stack Overflow for
support questions, more information at https://git.io/vM1yQ.

**Expected behavior**
only execute the command "pip install kivy"

**To Reproduce**
A short, *runnable* example that reproduces the issue with *latest kivy master*.

**Code and Logs and screenshots**
 full logs: 
pip install kivy

Collecting kivy
  Downloading https://files.pythonhosted.org/packages/12/96/091ddacafb84dd18555a32d860dbfaf9c806147aa30c6f3c8b93cb7bab97/Kivy-2.0.0.tar.gz (23.7MB)
    100% |████████████████████████████████| 23.7MB 988kB/s
  Installing build dependencies ... error
  Complete output from command D:\workspace\tndvenv\Scripts\python.exe D:\workspace\tndvenv\lib\site-packages\pip-19.0.3-py3.8.egg\pip install --ignore-installed --no-user --prefix C:\Users\kukeg\AppData\Local\Temp\pip-build-env-epuslqp0\overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython>=0.24,<=0.29.21,!=0.27,!=0.27.2 "kivy_deps.gstreamer_dev~=0.3.1; sys_platform == \"win32\"" "kivy_deps.sdl2_dev~=0.3.1; sys_platform == \"win32\"" "kivy_deps.glew_dev~=0.3.0; sys_platform == \"win32\"" "kivy_deps.gstreamer~=0.3.1; sys_platform == \"win32\"" "kivy_deps.sdl2~=0.3.1; sys_platform == \"win32\"" "kivy_deps.glew~=0.3.0; sys_platform == \"win32\"":
  Collecting setuptools
    Downloading https://files.pythonhosted.org/packages/d0/15/5041473f5d142ee93bf1593deb8f932e27a078f6f04e2020cf44044f72c5/setuptools-56.2.0-py3-none-any.whl (785kB)
  Collecting wheel
    Downloading https://files.pythonhosted.org/packages/65/63/39d04c74222770ed1589c0eaba06c05891801219272420b40311cd60c880/wheel-0.36.2-py2.py3-none-any.whl
  Collecting cython!=0.27,!=0.27.2,<=0.29.21,>=0.24
    Downloading https://files.pythonhosted.org/packages/ad/4b/9e53bcce3c959fd0db143626e573210bba07be810fe8d7296373948c4183/Cython-0.29.21-py2.py3-none-any.whl (974kB)
  Collecting kivy_deps.gstreamer_dev~=0.3.1
    Could not find a version that satisfies the requirement kivy_deps.gstreamer_dev~=0.3.1 (from versions: )
  No matching distribution found for kivy_deps.gstreamer_dev~=0.3.1

  ----------------------------------------
Command "D:\workspace\tndvenv\Scripts\python.exe D:\workspace\tndvenv\lib\site-packages\pip-19.0.3-py3.8.egg\pip install --ignore-installed --no-user --prefix C:\Users\kukeg\AppData\Local\Temp\pip-build-env-epuslqp0\overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython>=0.24,<=0.29.21,!=0.27,!=0.27.2 "kivy_deps.gstreamer_dev~=0.3.1; sys_platform == \"win32\"" "kivy_deps.sdl2_dev~=0.3.1; sys_platform == \"win32\"" "kivy_deps.glew_dev~=0.3.0; sys_platform == \"win32\"" "kivy_deps.gstreamer~=0.3.1; sys_platform == \"win32\"" "kivy_deps.sdl2~=0.3.1; sys_platform == \"win32\"" "kivy_deps.glew~=0.3.0; sys_platform == \"win32\""" failed with error code 1 in None

**Comment by matham** [comment]
We need the full and complete uncut logs including the full command you ran.

**Comment by SuboFrank** [comment]
> We need the full and complete uncut logs including the full command you ran.

yes, i had update

**Comment by instantrice** [comment]
I have the same issue. When I run:
python -m pip install kivy

I get the following output (you'll notice I canceled at the end because once I get one failure, I get 30 more):

Collecting kivy
  Using cached Kivy-2.0.0.tar.gz (23.7 MB)
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\Skip\Documents\Training\git\instantrice\kivy_venv\Scripts\python.exe' 'C:\Users\Skip\AppData\Local\Temp\pip-standalone-pip-v72y_2cv\__env_pip__.zip\pip' install --ignore-installed --no-user --prefix 'C:\Users\Skip\AppData\Local\Temp\pip-build-env-b8wr3fyf\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel 'cython>=0.24,<=0.29.21,!=0.27,!=0.27.2' 'kivy_deps.gstreamer_dev~=0.3.1; sys_platform == "win32"' 'kivy_deps.sdl2_dev~=0.3.1; sys_platform == "win32"' 'kivy_deps.glew_dev~=0.3.0; sys_platform == "win32"' 'kivy_deps.gstreamer~=0.3.1; sys_platform == "win32"' 'kivy_deps.sdl2~=0.3.1; sys_platform == "win32"' 'kivy_deps.glew~=0.3.0; sys_platform == "win32"'
       cwd: None
  Complete output (10 lines):
  Collecting setuptools
    Using cached setuptools-59.3.0-py3-none-any.whl (952 kB)
  Collecting wheel
    Using cached wheel-0.37.0-py2.py3-none-any.whl (35 kB)
  Collecting cython!=0.27,!=0.27.2,<=0.29.21,>=0.24
    Using cached Cython-0.29.21-py2.py3-none-any.whl (974 kB)
  Collecting kivy_deps.gstreamer_dev~=0.3.1
    Using cached kivy_deps.gstreamer_dev-0.3.2-cp310-cp310-win_amd64.whl (3.9 MB)
  ERROR: Could not find a version that satisfies the requirement kivy_deps.sdl2_dev~=0.3.1 (from versions: 0.4.2, 0.4.3)
  ERROR: No matching distribution found for kivy_deps.sdl2_dev~=0.3.1
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/12/96/091ddacafb84dd18555a32d860dbfaf9c806147aa30c6f3c8b93cb7bab97/Kivy-2.0.0.tar.gz#sha256=d25e44eb44e43762b2fd0c5874e51954e0f1181fd9800d8a6756be6d084812d8 (from https://pypi.org/simple/kivy/). Command errored out with exit status 1: 'C:\Users\Skip\Documents\Training\git\instantrice\kivy_venv\Scripts\python.exe' 'C:\Users\Skip\AppData\Local\Temp\pip-standalone-pip-v72y_2cv\__env_pip__.zip\pip' install --ignore-installed --no-user --prefix 'C:\Users\Skip\AppData\Local\Temp\pip-build-env-b8wr3fyf\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel 'cython>=0.24,<=0.29.21,!=0.27,!=0.27.2' 'kivy_deps.gstreamer_dev~=0.3.1; sys_platform == "win32"' 'kivy_deps.sdl2_dev~=0.3.1; sys_platform == "win32"' 'kivy_deps.glew_dev~=0.3.0; sys_platform == "win32"' 'kivy_deps.gstreamer~=0.3.1; sys_platform == "win32"' 'kivy_deps.sdl2~=0.3.1; sys_platform == "win32"' 'kivy_deps.glew~=0.3.0; sys_platform == "win32"' Check the logs for full command output.
  Using cached Kivy-1.11.1.tar.gz (23.6 MB)
  Preparing metadata (setup.py) ... canceled
ERROR: Operation cancelled by user
