### ISSUE TITLE
Window.fullscreen documentation error

### ISSUE THREAD

**Issue by petaflot** [kivy/kivy#7531]
**Describe the bug**
https://kivy.org/doc/stable/api-kivy.core.window.html says:

```fullscreen: str, one of (‘0’, ‘1’, ‘auto’, ‘fake’)```

Window.fullscreen says 

```ValueError: WindowSDL.fullscreen is set to an invalid option '1'. Must be one of: [True, False, 'auto', 'fake']```

**Comment by ElliotGarbus** [comment]
@Julian-O 
This issue can be closed.  The Window property fullscreen is properly documented: https://kivy.org/doc/stable/api-kivy.core.window.html#kivy.core.window.WindowBase.fullscreen

I suspect the root cause of this issue is that @petaflot was referring to the documentation for the WindowBase parameter fullscreen as documented here: https://kivy.org/doc/stable/api-kivy.core.window.html#kivy.core.window.WindowBase
when using the property Window.fullscreen.

**Comment by petaflot** [comment]
looking forward to see if I actually manage to put my window in fullscreen mode :-)
