### ISSUE TITLE
On Android keyboard/TextInput doesn't work properly: backspace has no effect and input doubles randomly

### ISSUE THREAD

**Issue by olek5andr** [kivy/kivy#7545]
Python == 3.9.1
kivy == 2.1.0.dev0
KivyMD == 0.104.2.dev0

Here are the requirements from buildozer.spec:
`requirements = python3,kivy==master,https://github.com/kivymd/KivyMD/archive/master.zip,sdl2_ttf==2.0.15,requests,urllib3,chardet,idna,android,plyer,jnius,pillow`

The keyboard doesn't work properly with TextInput fields. Backspace doesn't work at all, and the already inputed text just doubles at random, e.g. by typing 'qwerty123' you would get 'qwerty123qwerty123'. (And you can't delete it, because backspace doesn't work).

The bug is very similar to what is described [here](https://groups.google.com/g/kivy-users/c/ZuHsbOjcmwU), although the proposed solution doesn't work in my case.

IMPORTANT: 
- In buildozer.spec I'm specifying 'p4a.branch == develop'. Because with the default 'p4a.branch == master' the app crashes on Android when you just focus on a TextInput.
- This bug does not appear when using kivy == 2.0.0. BUT using kivy == 2.0.0 is not an option because it lags extensively on Android.

Thanks in advance!

https://user-images.githubusercontent.com/22771286/120924851-6b4a4180-c6de-11eb-82d2-e521ef62d426.mp4

**Comment by FilipeMarch** [comment]
I'm having this same problem, I found different issues also. 
On loading the first screen of the app, I got this (crash) once:
`File "/home/filipemarch/compile/cafe-compile/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/login2/kivymd/material_resources.py", line 20, in <module>
06-09 03:43:25.083 18566 18606 I python  :  AttributeError: 'NoneType' object has no attribute 'width'
`
and pressing backspace on textinput causes this crash:
`File "/home/filipemarch/compile/cafe-compile/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/login2/kivy/uix/textinput.py", line 2878, in window_on_textedit
06-09 03:45:19.392 18647 18687 I python  :  IndexError: list index out of range`
even trying to write on a textinput
`06-09 03:37:07.898 16088 16088 I python  :    File "kivy/graphics/instructions.pyx", line 662, in kivy.graphics.instructions.Canvas.add
06-09 03:37:07.899 16088 16088 I python  :    File "kivy/graphics/instructions.pyx", line 88, in kivy.graphics.instructions.Instruction.flag_data_update
06-09 03:37:07.900 16088 16088 I python  :  TypeError: Cannot change graphics instruction outside the main Kivy thread
`
I want to use kivy 2.1.0 so much because this is the only version I got `TextInput(input_type: 'number')` working:
![image](https://user-images.githubusercontent.com/23220309/121318750-eaf42e00-c8e1-11eb-9276-46c2f8302dea.png)

Let me know if there is a different kivy version that I could use to be able to compile an app that shows this numeric keyboard when you click on a textinput! Thanksss

**Comment by rqsrdco** [comment]
Backspace not working on android !
