### ISSUE TITLE
Feature Request: extended grid/table functionality

### ISSUE THREAD

**Issue by dernhelm7** [kivy/kivy#763]
Kivy is brilliant. We'd like to use it for a warehouse management program we're building in python, but Kivy's GridLayout functionality is minimal...and we display a lot of grids. We'd like to build a more comprehensive grid module that's geared towards displaying data. Is there anyone working on grids already that we could help, or anyone interested in helping us accomplish this?
##

**Comment by vital-fadeev** [comment]
Up.
Need database table editor too.
There are Russian-speaking developers exists?

**Comment by ivlevdenis** [comment]
@vital-fadeev, exist :)

**Comment by grapemix** [comment]
Since it is 2015 and kivy 1.9 is out, this feature requested from 2012 was supposed to be in the 2.0.0 roadmap. I just want to make sure this feature is not being ignored. Some users still want this feature to be done, especially this feature is there in QT and GTK.

BTW, @pedrodgcouto, thanks for your work.

**Comment by namkazt** [comment]
it's a simple datagrid : https://github.com/namkazt/Kivy-Datagrid-plugin

**Comment by CreamyCookie** [comment]
So, will this still become part of Kivy?

**Comment by dgoadby** [comment]
I need to link a MySQL database to a Kivy grid. So I'm watching this thread too...

**Comment by dessant** [comment]
We are closing some of the stale issues, please create a new issue/pr if you'd like to work on this feature, or get in touch with us on #kivy-dev.
