### ISSUE TITLE
Adding the option to play a sound from a URL

### ISSUE THREAD

**Issue by zPy52** [kivy/kivy#7818]
**Is your feature request related to a problem? Please describe**
There is not a direct way to play a sound given a URL, instead of a path. If I can suggest so, it would be great to have that option, since the inability to do it affects some of us.

**Describe the solution you'd like**
Similar to the _playsound_ module in Python. Look at this [GitHub Gist](https://gist.github.com/zJar84/cca63aff20a057463f9b191280e244e7).

**Describe alternatives you've considered**
I am currently using the _requests_ module to download the file, immediately play and then remove it with the _Path/os_ module. I have seen you have a _UrlRequest_ module that can do the work, but I am not familiarised with it (that would be the point of this feature: a common, straightforward function that will be used by plenty of developers).

**Additional context**
I think it's not necessary.

**Comment by kuzeyron** [comment]
If you set `ffpyplayer` to be the provider instead of Gstreamer it will work just fine.

I was working on a prototype which is using ffpyplayer, Youtube_dl and pafy for streaming videos with Kivy.
Demo app that is not running on my end at the moment because I have packages that is failing to install: [My Gist](https://gist.github.com/kuzeyron/74123a5b93f88f61d60cc60fb221d6c6)
I hope it's useful with your own research.

**Comment by Julian-O** [comment]
If this is to be a feature suggestion, please show it is worthwhile to a lot of people to save 5 lines of code.

**Comment by baseplate-admin** [comment]
> If this is to be a feature suggestion, please show it is worthwhile to a lot of people to save 5 lines of code.

maybe it should be documented somewhere, no?
