### ISSUE TITLE
cursor's index returned by method 'cursor_index' (of TextInput) changes while using backspace key

### ISSUE THREAD

**Issue by ApuCoder** [kivy/kivy#7948]
I'm using Kivy (v-2.0.0) [Python (v-3.9.7)].

**The problem**

The method `cursor_index` of `TextInput` seems to produce wrong index while backspace key is used. It works normal (correct 0-based index) while inserting new text but if any character(s) is deleted the index increased (by 1). Even when all chars are deleted (i.e. `len(self._lines)` is 0) by backspace the index becomes 1 instead of 0 (but not if deleted with 'select all').

**Minimal reproducible code to demonstrate the problem**

```py
from kivy.app import runTouchApp
from kivy.lang import Builder

kvlang = """
BoxLayout:
	orientation: "vertical"

	TextInput:
		text: "01234"
		on_text: lbl.text = "Cursor index = {}".format(self.cursor_index())

	Label:
		id: lbl
"""

runTouchApp(Builder.load_string(kvlang))
```

**Comment by kmcasi** [comment]
This issue is because you call the :mod:`~kivy.textinput.cursor_index` on text event and will have same result and on key down event, This events do they job after you tell them to do something like in your case captured the cursor index. So is not an issue, if you want to get the cursor index after you typed something use :mod:`~kivy.clock.Clock.schedule_once` or you can use :mod:`~kivy.core.window.Window` and bind it with "on_key_down" event instead of your "on_text".

**Comment by ApuCoder** [comment]
Thank you @kmcasi for the suggestion. It turns out `cursor_index` is actually determined by the no. of characters as opposed to 0-based index (that I found from event `on_text`). That just confused me.

```py
kvlang = """

#: import Clock kivy.clock.Clock

BoxLayout:
	orientation: "vertical"

	TextInput:
		text: ""
		size_hint_y: 0.25
		on_text:
			Clock.schedule_once(lambda *_ : setattr(lbl1, "text", "With Clock\\nCursor index = {}".format(self.cursor_index())))
			lbl2.text = "Without Clock\\nCursor index = {}".format(self.cursor_index())

	Label:
		id: lbl1

	Label:
		id: lbl2
"""
```
