### ISSUE TITLE
Not much to say, Can you provide colspan or rowspan feature more efficient, than using layouts nesting. 

### ISSUE THREAD

**Issue by gensart-ai** [kivy/kivy#8161]
a title may sums all i want to say.
this is just my opinion.

**Comment by misl6** [comment]
Hi @gensart-ai , can you provide some more context to add to this feature-request?

Due to the open-source nature of the project, we're always open to new features and enhancements, and something more specific ( even if concise ) would help our maintainers and supporters a lot.

Feel free to add more context here.

**Comment by gensart-ai** [comment]
Firstly, thank you for your attention,
Mm, i mean like, when i want to make some colspan like 
![www](https://user-images.githubusercontent.com/58139648/224590728-7f1af66e-0995-4d02-84c9-7fe871755637.png)

I did it by nesting layouts. I just wondered if it will impact on the performance of the app. Maybe you have some good solution ? Or is it just like that.

**Comment by misl6** [comment]
Hi @gensart-ai !

This is not gonna affect the performance of your app, so nesting layouts is absolutely fine.
If you want to, we can add a feature-request label for an HTML-like table.
