### ISSUE TITLE
Modifying logger to somehow make it customisable even with the singleton approach 

### ISSUE THREAD

**Issue by Lucifer516-sudo** [kivy/kivy#8219]
I am very new to programming, i quite got some grip with python basics. I tried to create an ledger for my personal use , i wanted to use kivy for GUI . But i just got stuck to modify the logger in the way i wanted to log

Provide an way to use an custom logger. The project that i tried using kivy is https://github.com/Lucifer516-sudo/simple_ledger/tree/release/simple_ledger

I tried searching on internet. Nothing seems to be compromising. Maybe i don't have enough knowledge about loggers in general it seems.

**Comment by Julian-O** [comment]
Hi @Lucifer516-sudo, and a belated welcome to the work of programming.

Python comes with a built-in "batteries-included" logging system, which is very flexible - it can handle the very simplest cases, with one module printing to the screen, up to major systems. The logging system allows you to add customised handlers and formatters, so you choose where your output goes and how it looks. It allows you to change us config files, and even reconfigure the logging system while it is still running.

Since Kivy 2.2.0, Kivy has worked with the Python logging system, with [three levels of integration](https://kivy.org/doc/stable/api-kivy.logger.html) - from a ready-to-use out-of-the-box mode with zero configuration needed to a take-complete-control mode, where you can set up the loggers as your heart desires.

So, in that sense, it is *already possible* to create a custom log handler, and customise how Kivy logging appears.

I looked briefly at your code, and it looks like you are trying to build a new logging from scratch. I strongly recommend against that - use [the logging system in Python](https://docs.python.org/3/library/logging.html). 

If you write your own logging system, you can't expect third-party components, including Kivy, to use them. There are standard Python approaches.

[I would recommend this issue be closed as there is no bug, and no need that is not being met.]

**Comment by Lucifer516-sudo** [comment]
Issue closed

**Comment by Lucifer516-sudo** [comment]
Actually, I am very much glad that you took time and saw my small piece of work, and gave me some handful of advice. And I am sorry for an late response, I've been offline for some months as I was concentrating on my public examination, which i successfully ruined, and let it be ...

I understood what you meant, actually I got so much frustrated, since I was only programming in my mobile, which lead me to loose some confidence and recently I just read about flet module somewhere , and I am currently trying it out , and after sometime I am a bit confident on trying out kivy again, when I get myself an laptop, which is a bit tough one for me as for an descent spec lap, i have to spend an minimum amount of INR 35k to 40k.

And what you said about logging is absolutely right and i understood it a bit , which using the RichHandler for an simple app that I made with flet, 

And once again, thanks a lot for your response,
With regards, 😄
Harish
