### ISSUE TITLE
need help in adding authentication using azure B2C in Kivy

### ISSUE THREAD

**Issue by venkataraja705** [kivy/kivy#8247]
**Is your feature request related to a problem? Please describe.**
I have developed a mobile application using kivy and kivymd
we are trying to add authentication in kivy using Azure AD B2C
we have found AZURE documentations on B2C authentication in python web application but could not find anything for kivy mobile application.

if we use userflows from mobile app on sign in we will need to launch a browser window inside the mobile application itself.
but we do not want to do that.
please suggest any other alternatives or samples

reference: https://learn.microsoft.com/en-us/azure/active-directory-b2c/enable-authentication-android-app?tabs=kotlin
reference-python-web-app: https://learn.microsoft.com/en-us/azure/active-directory-b2c/configure-authentication-sample-python-web-app?tabs=windows

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by misl6** [comment]
> OpenID Connect (OIDC) is an authentication protocol that's built on OAuth 2.0. You can use OIDC to securely sign users in to an application. This web app sample uses the [identity package for Python](https://pypi.org/project/identity/) to simplify adding authentication and authorization support to Python web apps.

Since is OIDC, I would suggest https://github.com/openid/AppAuth-Android (via `pyjnius`) and https://github.com/openid/AppAuth-iOS (via `pyobjus`).

However, we use the issue tracker exclusively for bug reports and feature requests. However, this issue appears to be a support request. Please use our [support channels](https://github.com/kivy/kivy/blob/master/README.md#support) to get help with the project.
