### ISSUE TITLE
Color error while drawing lines

### ISSUE THREAD

**Issue by orklann** [kivy/kivy#8632]
**Software Versions**
* Python: 3.12.2
* OS: Ubuntu 22.04.4 LTS
* Kivy: v2.3.0
* Kivy installation method: pip install kivy

**Describe the bug**
Drawing a simple line with black color in a root widget, but the black color line looks not exact black, see attachment with screenshot

**Expected behavior**
A line should be drawn fully black

**To Reproduce**
After install kivy, just run `python demo.py`

**Code and Logs and screenshots**
```python
from kivy.app import App
from kivy.core.window import Window
from kivy.graphics import Rectangle
from kivy.graphics import Color
from kivy.uix.widget import Widget
from kivy.graphics import Line

class Touch(Widget):
    def __init__(self, **kwargs):
        super(Touch, self).__init__(**kwargs)

        with self.canvas:
            Color(1, 1, 1, 1, mode="rgba")
            Rectangle(pos=(0, 0), size=Window.size)
            Color(0, 0, 0, 1, mode="rgba")
            Line(points=(20,30,300,60))

class DrawingApp(App):
    def build(self):
        return Touch()

DrawingApp().run()
```
![Screenshot from 2024-02-25 13-56-34](https://github.com/kivy/kivy/assets/5492042/b5cede1c-be95-4e31-895d-ed82079b3c1a)

**Comment by misl6** [comment]
This is a known artifact due to how the line is created.

But the nice news is that you can circumvent with issue via https://kivy.org/doc/stable/api-kivy.graphics.html#kivy.graphics.Line advanced options, or by using https://kivy.org/doc/stable/api-kivy.graphics.vertex_instructions.html#kivy.graphics.vertex_instructions.SmoothLine

Please check out the docs, and feel free to join us on our support channels.
